### ISSUE TITLE
Feature elimination to screen for multiple models using tidymodels

### ISSUE THREAD

**Issue by gundalav** [tidymodels/recipes#1024]
Hi, 

I am currently performing regression modeling, with a dataset that has number of features (*p*) higher than observations (*n*).
Typically `p = 10000` and `n = 30`. Furthermore, I'd like to [test many models][1] and find the best one. 

What I'm doing now is first to eliminate those features. Reducing it from 10K to 20-30, using
 [step_select_mrmr()][2] or [step_select_vip()][3].  I achieved that by placing it at the top of my pipeline.
Then I would proceed with testing many models.

Is this approach reasonable? If not is there any step in recipes package I can use?

G.V.

  [1]: https://www.tmwr.org/workflow-sets.html
  [2]: https://stevenpawley.github.io/recipeselectors/reference/step_select_mrmr.html
  [3]: https://stevenpawley.github.io/recipeselectors/reference/step_select_vip.html

**Comment by EmilHvitfeldt** [comment]
That seems reasonable! you would of-cause want to do some validation from time to time to make sure you are not overly aggressively removing features.
