### ISSUE TITLE
`tidy.recipe` doesn't correctly process steps that have more complex inheritance structure

### ISSUE THREAD

**Issue by mobius-eng** [tidymodels/recipes#1058]
The issues arises if one wants to extend an existing step (normal thing in OOP world). Say, I want to extend `step_select` that does some pre- or post- processing. For now, I will purely delegate all functionality to `step_select` (I am using it as an example, but use-case is wider; warning: I am using unexported functions).

```r
step_new_select <- function(
    recipe,
    ...,
    role = NA, 
    trained = FALSE, 
    loc_scale = NULL,
    skip = FALSE,
    id = rand_id("robust_scale")
) {
  # collect terms
  terms <- ellipse_check(...)
  # call actual constructor & add to a recipe
  add_step(
    recipe,
    step_new_select_new(
      terms = terms,
      role = role,
      trained = trained,
      skip = skip,
      id = id
    )
  )
}

step_new_select_new <- function(terms, role, trained, skip, id) {
  # use underlying step_select; WARNING: use private function here
  select <- recipes:::step_select_new(
    terms = terms,
    role = role,
    trained = trained,
    skip = skip,
    id = id
  )
  # add class
  class(select) <- c("step_new_select", class(select))
  return(select)
}

prep.step_new_select <- function(x, training, info = NULL) {
  # for now - delegate
  NextMethod()
}

bake.step_new_select <- function(object, new_data) {
  NextMethod()
}
```

A recipe that uses this step works:

```r
data(mtcars)
rec_ex <- recipe(~ ., data = mtcars) %>% step_new_select(-gear) %>% step_mutate(Phony = am + carb) %>% prep()
bake(rec_ex, mtcars)
```

But breaks if `tidy`-ed:

```
> tidy(rec_ex)
Error:
! Tibble columns must have compatible sizes.
• Size 2: Existing data.
• Size 3: Column `operation`.
ℹ Only values of size one are recycled.
Run `rlang::last_error()` to see where the error occurred.
```

The reason for the error is how the classes for steps are extracted and processed in `recipes:::tidy.recipe`:

```r
function (x, number = NA, id = NA, ...) 
{
    num_oper <- length(x$steps)
    pattern <- "(^step_)|(^check_)"
    if (!is.na(id)) {
        <...>
    }
    if (is.na(number)) {
        skipped <- vapply(x$steps, function(x) x$skip, logical(1))
        ids <- vapply(x$steps, function(x) x$id, character(1))
        oper_classes <- lapply(x$steps, class)
        oper_classes <- grep("_", unlist(oper_classes), value = TRUE)
        oper <- strsplit(oper_classes, split = "_")
        oper <- vapply(oper, function(x) x[1], character(1))
        oper_types <- gsub(pattern, "", oper_classes)
        is_trained <- vapply(x$steps, function(x) x$trained, 
            logical(1))
        res <- tibble(number = seq_along(x$steps), operation = oper, 
            type = oper_types, trained = is_trained, skip = skipped, 
            id = ids)
    }
    else {
       <...>
    }
    res
}
```

When `unlist()` is applied to `oper_classes` it stitches together `step_new_select` and `step_select`. Hence, it sees more operaions (`oper`) and operations types (`oper_types`) than necessary.

Can the whole `grep` be replaced with taking the first item from each list entry in `oper_classes`?

**Comment by mobius-eng** [comment]
Hi @EmilHvitfeldt 

Thanks for the comment.

My version: 1.0.1, R 4.2.1

So, it could be that the new version works fine.

I would like to make a request though that step extension (in some way) should be an option, if not by inheritance, than by composition (in this case `*_new` constructors should be exposed). Although inheritance is easier to use (and why not?)

My actual use-case was: I needed GMM with MClust step. But then I wanted to tweak which model parameters to choose to minimise number of clusters and then add Mahalanobis distance calculation for a selected cluster -- all these fall under feature engineering. So, I created a step from scratch to perform GMM. The second part, however, I couldn't achieve just by adding an extra step (if I was not willing to break "tibble in" - "tibble out" data flow through recipe steps as I would need to pass MClust object from GMM step). So, I would have needed to either created a new step from scratch that would do GMM and add extra features on top of it (no code re-use) or extend existing step. Extension worked, even though it is a bit hacky, but it is the nature of S3.

Right now, I cannot re-use existing step functionality:

* Inheritance doesn't seem to be supported as per comment
* Composition requires raw step constructors to be exposed (exported), otherwise I am using non-public interface.

Thoguhts?

**Comment by EmilHvitfeldt** [comment]
The example you showed in the initial post, does work with current versions of recipes. So in that sense you are able to do step extension in your proposed fashion.

> Inheritance doesn't seem to be supported as per comment

This work in the current versions of recipes. What I meant earlier was that we do not see the need to make any additional changes to the current infrastructure, with regards to extensions, as we are happy with the functionality and extensibility at this point.

> Composition requires raw step constructors to be exposed (exported),

the `step_*_new()` functions are very shallow wrappers around `step()`, if I were you, I would just copy over the code directly. This way, you have `step_new_select_new()` looking like this:

```r
step_new_select_new <- function(terms, role, trained, skip, id) {
  select <- step(
    subclass = "select",
    terms = terms,
    role = role,
    trained = trained,
    skip = skip,
    id = id
  )
  # add class
  class(select) <- c("step_new_select", class(select))
  return(select)
}
```

Having written many recipes myself. I do see that there is a lot of boilerplate. In my mind, most of what we do in recipes is what happens inside `prep.step_*()` and `bake.step_*()`. having good designed functions for these would allow you to at least use that in multiple steps.
