### ISSUE TITLE
request `all_complete_predictors()`

### ISSUE THREAD

**Issue by joeycouse** [tidymodels/recipes#1059]
``` r
> model_train <- training(splits)
> model_test <- testing(splits)
> 
> win_recipe <- recipe(win ~ .,
+                        data = model_train) |> 
+   update_role(track, date, race, new_role = "id") |> 
+   step_select_mrmr(all_numeric_predictors(), outcome = 'win', top_p = 13)
> prep(win_recipe) |> 
+   bake(new_data = NULL) |> 
+   glimpse()
Error in praznik::MRMR(X = ~training[, x_names], Y = ~training[[y_name]],  : 
  Non-finite numeric values are not allowed
``` 
I've been testing the `colino` package's feature selection methods, and come across this case where the step wants all numeric predictors but can only handle complete cases. I think an `all_complete()`, `all_complete_predictors()`, `all_complete_numeric()`, etc helper functions would be useful. Unless there is a better way to do this.

**Comment by EmilHvitfeldt** [comment]
hello @joeycouse 👋 thank you for your suggestion and interest in this project.

I would be hesitant to add these functions as I think they would be misleading for the user. A recipe step can have problems with missing values at two different places; During `prep()` and during `bake()`. `all_complete_predictors()` would only let you deal with not passing missing values to `prep()`, it can't do anything about what happens doing `bake()`. I think this would be overly confusing to use a recipe with `all_complete_predictors()` and still get errors about missing data.

The package itself could do a better job showing which columns contain missing data. I wrote this for a similar problem in themis, where they also require complete information.
https://github.com/tidymodels/themis/blob/c590dbab0d909d5e1b7da648a2cd945f019712f0/R/misc.R#L7-L15
