### ISSUE TITLE
`step_range()` fails when baking old recipe

### ISSUE THREAD

**Issue by AshesITR** [tidymodels/recipes#1090]
I have stored pre-trained recipes with recipes version <= 1.0.2 (when `step_range()` had no `clipping = TRUE` argument).
These stored recipes can no longer be baked because the old data structure contains no information on `clipping`, causing

```
Error in if (object$clipping) {: argument is of length zero
```

I can manually fix these old recipes by setting `recipe$steps[[...]]$clipping <- TRUE`, but it would be nice if there was backward compatibility out of the box.

**Comment by EmilHvitfeldt** [comment]
Here is a reprex:

``` r
library(recipes)

data(biomass, package = "modeldata")
biomass_tr <- biomass[biomass$dataset == "Training", ]
biomass_te <- biomass[biomass$dataset == "Testing", ]
rec <- recipe(
  HHV ~ carbon + hydrogen + oxygen + nitrogen + sulfur,
  data = biomass_tr
)
ranged_trans <- rec %>%
  step_range(carbon, hydrogen)
ranged_obj <- prep(ranged_trans, training = biomass_tr)

# Simulate old recipe
ranged_obj$steps[[1]]$clipping <- NULL

transformed_te <- bake(ranged_obj, biomass_te)
#> Error in if (object$clipping) {: argument is of length zero
```

<sup>Created on 2023-02-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
