### ISSUE TITLE
Feature suggestion: include steps for spectral pre-treatment 

### ISSUE THREAD

**Issue by tellyshia** [tidymodels/recipes#1099]
## Feature

I've created some recipe step functions for spectral pre-treatment from `prospectr` packages.
Can I contribute the codes to `recipes`?

**Comment by EmilHvitfeldt** [comment]
Hello @tellyshia 🧇 

This has been suggest before, and while we don't plan on adding spectral pre-treatment steps directly into {recipes}, there is an extension package https://github.com/JamesHWade/measure that might have what you need, or who might be willing to take issues/pull requests for more features.
