### ISSUE TITLE
unnecessary re-deduplication of variable names takes a lot of time

### ISSUE THREAD

**Issue by StevenWallaert** [tidymodels/recipes#1104]
## The problem

I'm having trouble with recipes that handle datasets with deduplicated variable names. 

For example variable names that have been handled (i believe by tibble's default, but not sure) like this or similar: 

```varA varB varA --> varA varB varA...2 ```

The problem I am having is that even though the column names are unique, it seems that recipes is giving them a different name while preping/baking the recipe. This 're-deduplication' proliferates if you add an na_indicator step (or dummy step).

While this may be trivial for small datasets, this takes a lot of time when the number of such columns is relatively high. 

The reprex just shows what happens when one column has a deduplicated but similar name to another column name.

As you can see, although there is (from my point of view) no need for it, the recipe does in total 4 name changes. This problem exacerbates as the number of such columns gets higher. I encountered this problemn when working with a much larger dateset with many of those columns. It takes a lot of time.

To give an idea: there are about 330 columns in my data set of which about 30 have a deduplicated name (the reason for is something technical and not relevant here). 
Baking the recipe shows 660 renamings, and i'm not sure if i catched them all. The whole process takes minutes, which is problematic in a resampling context.

## Reproducible example

``` r
library(tidymodels)

set.seed(42)
missing_id <- sample(1:nrow(iris), size = 10)

iris[missing_id, 1] <- NA

iris <- iris %>% 
  rename(Sepal.Length...1 = Sepal.Width)

reciris <- recipe(Species ~ ., data = iris) %>% 
  step_indicate_na(all_predictors()) %>% 
  step_impute_median(all_predictors())

prep(reciris) %>% bake(NULL)
#> New names:
#> • `Sepal.Length` -> `Sepal.Length...1`
#> • `Sepal.Length...1` -> `Sepal.Length...2`
#> • `na_ind_Sepal.Length` -> `na_ind_Sepal.Length...6`
#> • `na_ind_Sepal.Length...1` -> `na_ind_Sepal.Length...7`
#> # A tibble: 150 × 9
#>    Sepal.Lengt…¹ Sepal…² Petal…³ Petal…⁴ Species na_in…⁵ na_in…⁶ na_in…⁷ na_in…⁸
#>            <dbl>   <dbl>   <dbl>   <dbl> <fct>     <int>   <int>   <int>   <int>
#>  1           5.1     3.5     1.4     0.2 setosa        0       0       0       0
#>  2           4.9     3       1.4     0.2 setosa        0       0       0       0
#>  3           4.7     3.2     1.3     0.2 setosa        0       0       0       0
#>  4           4.6     3.1     1.5     0.2 setosa        0       0       0       0
#>  5           5       3.6     1.4     0.2 setosa        0       0       0       0
#>  6           5.4     3.9     1.7     0.4 setosa        0       0       0       0
#>  7           4.6     3.4     1.4     0.3 setosa        0       0       0       0
#>  8           5       3.4     1.5     0.2 setosa        0       0       0       0
#>  9           4.4     2.9     1.4     0.2 setosa        0       0       0       0
#> 10           4.9     3.1     1.5     0.1 setosa        0       0       0       0
#> # … with 140 more rows, and abbreviated variable names ¹​Sepal.Length...1,
#> #   ²​Sepal.Length...2, ³​Petal.Length, ⁴​Petal.Width, ⁵​na_ind_Sepal.Length...6,
#> #   ⁶​na_ind_Sepal.Length...7, ⁷​na_ind_Petal.Length, ⁸​na_ind_Petal.Width
```

<sup>Created on 2023-03-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by EmilHvitfeldt** [comment]
After some talk, we think the best move forward is to recommend you clean up the names beforehand. You can do this fairly easily with the `janitor::clean_names()` function. This should ideally be applied to your data before you do your data splitting.

If your workflow doesn't allow for these changes to happen before the recipe, you could start your recipe with this step [textrecipes::step_clean_names()](https://textrecipes.tidymodels.org/reference/step_clean_names.html)

We are choosing the recommendation because it would be a lot of work and guard railing to prevent this problem, that is caused by that is essentially bad input.

Let me know if this works for you! 😄

**Comment by StevenWallaert** [comment]
Thanks for your feedback. 

I agree that this in essence a bad input problem. Though, it felt a bit strange to see all those name changes happening.

The proposed solution of using janitor works for me, thank you for this!
The speed-up is huge :)
