### ISSUE TITLE
check_classes

### ISSUE THREAD

**Issue by EdwinTh** [tidymodels/recipes#111]
Description:
`prep.check_classes` will learn the classes of each of the colums.
`bake.check_classes` breaks when:
- column of which the class is learned is missing from `newdata`
- column is a of a different class than was learned in `prep`

Choices to make:
- do we consider `integer` and `numeric` as the same class? (I would say yes)
- do we consider `factor` and `character` as the same class? (I would say maybe add an argument for this that defaults to `TRUE`)
- do we allow for date time variables? (I would say yes).

**Comment by alexpghayes** [comment]
Having something like `check_numeric` would be nice. Then `check_numeric` together with `check_missing` would be enough to validate a dataset for most modelling packages.

**Comment by topepo** [comment]
How about a general `check_class` that uses `inherits`?

**Comment by EdwinTh** [comment]
Maybe we can combine the two? A `check_class` that defaults to learning the classes of all the variables in `prep`, when the `class` argument is left to be `NULL`. If it is provided it will check for that class instead.

**Comment by topepo** [comment]
That is a good idea.

**Comment by EdwinTh** [comment]
Ok will start working on it as soon as job and baby allow it...

**Comment by EdwinTh** [comment]
Have it almost ready, see [here](https://github.com/EdwinTh/recipes/tree/check-class), but there is one major hurdle.

When running `prep` with `stringsAsFactors = TRUE` (the default) the following will happen. In `prep.recipe` the coercion to factors happens before the calling of the `prep` methods of the individual steps and checks. When we run `prep.check_class` with the `class` arg to be `NULL` it will thus save the class factor here for the variables that went in as a character, because they have already been converted. 

In `bake` however, we first run the `bake` methods of the steps and checks, and only then start coercing the characters to factors. This then will break the baking on character variables, where it shouldn't.

I can of course try and fix this in some way in this specific step, but that is not trivial. Like to discuss first why the factor coercion block is after the application of the `bake` methods in the first place in `bake.recipe`. It seems cleaner to have the order to be similar to `prep.recipe`. This problem might occur again when developing future steps and checks. Are there pressing reasons to keep it in this order?

**Comment by EdwinTh** [comment]
@topepo, friendly reminder to look into this so we can wrap-up this check.

**Comment by EdwinTh** [comment]
This one is implemented
