### ISSUE TITLE
check distribution shift continuous variables

### ISSUE THREAD

**Issue by EdwinTh** [tidymodels/recipes#112]
A learned effect can be invalid when the distribution of the feature as a whole shifts. For instance if we regress the square feet of a house to its price, we would systematically overestimate house size when house prices rise.

How should we check for distribution shifts? Simple implementation might be allow a location measure like mean or median to shift only with a certain proportion of the total range. Or allow it to shift by a factor of the standard deviation. Alternatively, look at distributions as a whole, for instance with a Kolmogorov-Smirnov test.

**Comment by topepo** [comment]
For this (and #113) it would be better to add something to the applicable package (since it already does similar things).
