### ISSUE TITLE
step_winsorize 

### ISSUE THREAD

**Issue by Sade154** [tidymodels/recipes#1198]
Is it possible to implement a step_winsorize from the package : https://search.r-project.org/CRAN/refmans/DescTools/html/Winsorize.html ?

Would be very helpful to handle outliers.

**Comment by EmilHvitfeldt** [comment]
Hello @Sade154 👋 

Have you looked at the {healthyR.ai} package? It contains a couple of steps to perform winsorization, namely

- [step_hai_winsorized_move()](https://www.spsanderson.com/healthyR.ai/reference/step_hai_winsorized_move.html)
- [step_hai_winsorized_truncate()](https://www.spsanderson.com/healthyR.ai/reference/step_hai_winsorized_truncate.html)

**Comment by Sade154** [comment]
Did not know it / try it. 
That will probably helps, thanks.
