### ISSUE TITLE
step_novel Example looks out of date

### ISSUE THREAD

**Issue by bcadenato** [tidymodels/recipes#1248]
## The problem

I'm trying to reproduce the example in the `step_novel` [function documentation](https://recipes.tidymodels.org/reference/step_novel.html#ref-examples). However when assigning a new value to the `city` predictor as per the example, instead of a new factor being added to the data set, it's automatically converted to `NA`. 

The example loses relevance after this since `step_novel` doesn't come into play. I suggest that the example is reviewed.

(Incidentally I'm having my own troubles with `step_novel` but I haven't built yet a reprex example I can show, I'll follow up with that).

**Comment by EmilHvitfeldt** [comment]
thank you @bcadenato ! This is correct, and we will fix it. Good eye!

> (Incidentally I'm having my own troubles with step_novel but I haven't built yet a reprex example I can show, I'll follow up with that).

We would greatly prefer if you are able to post that in a separate issue once you develop the reprex!

**Comment by alexpghayes** [comment]
Related: it might be nice to add that example or a related code example to https://recipes.tidymodels.org/articles/Dummies.html#novel-levels, showing how to use `step_novel()` (or any other step) to resolve fit-time errors about novel factor levels
