### ISSUE TITLE
Recipes documentation unclear on how to pass data for CV

### ISSUE THREAD

**Issue by jxu** [tidymodels/recipes#1258]
In `?recipes`, the `data` passed to `recipes()` in the example is the training split. But it is unclear what should be passed if we split data using `vfold_cv`. Is it the entire dataset? The docs seem to suggest the actual data doesn't matter for the recipe, just the column names.

https://www.tidymodels.org/start/resampling/ does not show how to use a recipe, just formula.

**Comment by EmilHvitfeldt** [comment]
We typically don't use a `vfold_cv` fold object directly with a `recipe()` object. packages like [tune](https://tune.tidymodels.org/) knows how to handle both recipes and `vfold_cv` objects.

The dataset passed to `recipe()` does a couple of things. It is used to denote the column names, and their types. This information is used to detect whether some variables are missing, or if they have the wrong types.

When you go to `prep()` a recipe it will use that data by default, if the `training` argument of `prep()` has not been set.

**Comment by jxu** [comment]
So only the column names and types of the data passed in matter? It's not clear in the documentation.
