### ISSUE TITLE
step_interact documentation is not correct

### ISSUE THREAD

**Issue by millermc38** [tidymodels/recipes#1276]
For documentation (see page below), the argument `keep_original_cols` defaults to `TRUE` not `FALSE`. Of course, I personally prefer `TRUE` as the default behavior.

https://recipes.tidymodels.org/reference/step_interact.html

**Comment by EmilHvitfeldt** [comment]
thank you for reporting! This is much similar in content to https://github.com/tidymodels/recipes/issues/1267
