### ISSUE TITLE
offset role

### ISSUE THREAD

**Issue by jdonland** [tidymodels/recipes#1281]
There's a new package on CRAN called `offsetreg`, which extends `tidymodels` with some additional model types and engines that use an offset, i.e., a variable which should always have a coefficient of 1 in the model. Maybe `recipes` could implement `"offset"` as a special role and automagically pass them to model engines that want them?

**Comment by EmilHvitfeldt** [comment]
Hello @jdonland 👋  Thank for your interest and request!

I would be hesitant to create a new special type of role. I made this decision based on a maintenance / benefit ratio.

For this to be implemented, we need to make `"offset"` a special role in {recipes}. This part isn't actually that hard. But it wouldn't do anything by itself. So we would also need to do a lot of changes in {workflows} (case weights was one such example https://github.com/tidymodels/workflows/pull/118) which are non-trivial, and {parsnip} would need a change too, to be able to denote which model types want offsets and which doesn't. This is the minimum change needed for this to work. But i assume that some changes other places such as in {tune} would be needed as well.

This to me feels like too much additional code we have to maintain for the benefit it gives.

also, in case you haven't seen, I think you would find this interesting: https://github.com/tidymodels/tidymodels.org/issues/59

**Comment by EmilHvitfeldt** [comment]
if you have any further questions or issues, please feel free to file an issue!
