### ISSUE TITLE
options are ignored in step_ns

### ISSUE THREAD

**Issue by DemetriPananos** [tidymodels/recipes#1297]
Possible bug as the `options` argument is not returning the same output as `splines::ns`.

I'd like to specify a spline for a continuous variable using `step_ns`.  The docs say I can pass arguments `k` (knot locations) and `Boundary.knots` via `options` argument to `step_ns`.

However, doing so does not return the same number of basis vectors that I would get were I to use `model.matrix` and `spline::ns`.  See below

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

d <- tibble(x = seq(-2, 2, 0.01))

recipe(~., data=d) %>% 
  step_ns(x, options = list(k = seq(-1, 1, 0.125), Boundary.knots = c(-1.5, 1.5))) %>% 
  prep %>% 
  bake(new_data=d) %>% 
  ncol
#> [1] 2


model.matrix(~splines::ns(x, k = seq(-1, 1, 0.125), Boundary.knots = c(-1.5, 1.5)), data=d) %>% 
  ncol 
#> [1] 19
```

<sup>Created on 2024-04-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DemetriPananos** [comment]
@EmilHvitfeldt is this an actual bug?  If so I'd like to know so I can take a different approach on a problem

**Comment by EmilHvitfeldt** [comment]
I'm pretty sure this is a bug, or at least an unintuitive interface. It appears that the `deg_free` argument is taking over, 

https://github.com/tidymodels/recipes/blob/main/R/ns.R#L106-L130

If you need things working now, I would suggest you use [step_spline_natural()](https://recipes.tidymodels.org/reference/step_spline_natural.html)

cross-posted from https://stackoverflow.com/questions/78317941/step-ns-is-not-returning-expected-number-of-basis-functions

**Comment by DemetriPananos** [comment]
Ouch.  Ok, will try another approach.  @EmilHvitfeldt happy to contribute if you cc me on the ticket

**Comment by EmilHvitfeldt** [comment]
a fix is here with https://github.com/tidymodels/recipes/pull/1338.

A related issue is that you are using partial matching of `knots` by using the argument name `k`. This is not supported in `options` argument for recipes steps, and a plan to fix that issue is listed here https://github.com/tidymodels/recipes/issues/1269

``` r
library(recipes)

d <- tibble(x = seq(-2, 2, 0.01))

recipe(~., data = d) %>% 
  step_ns(x, options = list(knots = seq(-1, 1, 0.125), 
                            Boundary.knots = c(-1.5, 1.5))) %>% 
  prep() %>% 
  bake(new_data = d) %>%
  dim()
#> [1] 401  18

# -1 in `model.matrix()` to avoid intercept
model.matrix(~splines::ns(x, 
                          knots = seq(-1, 1, 0.125), 
                          Boundary.knots = c(-1.5, 1.5)) - 1, data = d) %>%
  dim()
#> [1] 401  18
```

<sup>Created on 2024-06-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
