### ISSUE TITLE
replace `check_nominal_data()` with `recipes_ptype_validate()`

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#1332]
the two functions essentially do the same thing, with `check_nominal_data()` providing a weaker check.

to be done after https://github.com/tidymodels/recipes/pull/1330. I didn't do it as part of that PR because it started to feel like too much in one PR

**Comment by simonpcouch** [comment]
@lgibson7 spent some time with this and noted that the helper had been written out in the meantime—will go ahead and close.
