### ISSUE TITLE
`recipes:::strings2factors` should be restricted by the role

### ISSUE THREAD

**Issue by dajmcdon** [tidymodels/recipes#1358]
## Feature

`prep.recipe()` calls `recipes:::strings2factors()` to convert character columns to factors (when true). It would be better if this operated, not on all columns but only on those with certain roles (likely just predictors + outcomes).

Context: I'm working on an extension that would accommodate panel data. This involves keeping around a `key` column which needs to remain a character regardless of the decisions for predictor columns. 

I'm happy to do a PR for this if it would be helpful. I think it requires only minor changes, but hopefully would cause few downstream issues.

**Comment by EmilHvitfeldt** [comment]
I think that sounds reasonable. If you feel like it, feel free to start the PR 😄

**Comment by dajmcdon** [comment]
Closed by #1376
