### ISSUE TITLE
missing declension in abort message

### ISSUE THREAD

**Issue by corybrunson** [tidymodels/recipes#1399]
The abort message [here](https://github.com/tidymodels/recipes/blob/59345e145351e636250412a5d3c4c52a6577d3ee/R/selections.R#L207) does not declense "do" according to the the quantity of `offenders`, so i prepared a fix [here](https://github.com/tidymodels/recipes/compare/main...corybrunson:recipes:declense) that i'll be glad to PR. Below is an inline demo.

``` r
abort_offenders <- function() cli::cli_abort(
  "The following argument{?s} {?was/were} specified but do{?es/} not exist: \\
      {.arg {offenders}}."
)

offenders <- c("one")
abort_offenders()
#> Error in `abort_offenders()`:
#> ! The following argument was specified but does not exist: `one`.

offenders <- c(offenders, "two")
abort_offenders()
#> Error in `abort_offenders()`:
#> ! The following arguments were specified but do not exist: `one` and
#>   `two`.
```

<sup>Created on 2024-11-25 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by EmilHvitfeldt** [comment]
Hallo @corybrunson 👋 

good catch! please open a PR, and update the snapshot if available! thanks

**Comment by corybrunson** [comment]
Just noticed that this wasn't closed. Sorry!
