### ISSUE TITLE
Add `step_cut` or equivalent

### ISSUE THREAD

**Issue by aaron-horowitz** [tidymodels/recipes#157]
`discretize` as it's currently implemented, isn't quite equivalent to base R's `cut` function, in that in the latter you can specify explicit cutpoints _or_ a single integer reflecting the number of intervals.  For interpretability of variables, it's often useful to set boundaries that are more "human readable". Would it be worth it to add a `step_cut` discretization alternative and/or build that capability into the core function itself, a la `cut`.

Since recipes are often meant to be used with multiple variables, this may not ideal, so an alternative is some sort of rounding parameters for cleaner breaks (ie round to neareast N).

**Comment by EdwinTh** [comment]
I think this is a good idea (I need it myself now and then :)). @topepo I am happy to do this if you want to have it added.

**Comment by juliasilge** [comment]
Closed in #452
