### ISSUE TITLE
Adding a duration step

### ISSUE THREAD

**Issue by EdwinTh** [tidymodels/recipes#160]
I think the following would be a nice addition. Calculate the time between a date or posix column and some reference date or time. See following code (that does not run of course).

```r
a <- data.frame(member_since = as.Date(c("2008-04-01", "2011-03-05")))
recipe(a) %>% 
  step_duration(member_since, 
                  unit = "year", 
                  rounding = "floor",
                  reference = as.Date("2018-06-13")) %>% 
  prep() %>%
  bake(a)
```

This then would result in the following column:
```r
floor((as.Date("2018-06-13") - a$member_since) / 365)
```

What do you think?

PS step_duration is not a great name, just working title

**Comment by topepo** [comment]
I think that the next big step for `recipes` is to add some `dplyr` commands like `mutate`, `filter`, `select`, and so on. That would reduce the total number of steps that we'll need. 

The idea is you could have:

```r
recipe(y ~ ., data = dat) %>%
  step_center(all_numeric()) %>%
  dplyr_mutate(time_diff = lubridate::difftime(d1, d2))
```

(I'm not completely sold on `dplyr` as a prefix so suggestions are welcome)

**Comment by EdwinTh** [comment]
That seems like a good idea, since many preparation steps will be done on a single column in the first place. (Or will you even combine them with `tidyselect`.)

Maybe call it `recipes_mutate` or `rec_mutate`? By now, everybody knows the verbs in dplyr, so I don't think a reference to it is necessary. Rather, indicate these methods are specific to`recipes`.

**Comment by alexpghayes** [comment]
Once we have this it might also make sense to deprecate `step_lag`, unless the vectorization there is convenient enough to keep. If we do decide the vectorization is convenient I think we should also consider a `step_diff` operator to round out some basic time series functionality.

**Comment by EdwinTh** [comment]
Closing this issue,  because allowing for the dplyr verbs will solve it.
