### ISSUE TITLE
export set_current_info()

### ISSUE THREAD

**Issue by galalH** [tidymodels/recipes#161]
Currently only the getter method current_info() is exported in selections.R. Would be good to have set_current_info() exported as well for when one wants to add additional columns of metadata to term_info from inside custom steps.

EDIT: I just realized that set_current_info() only copies over the usual fields from its argument. Perhaps that could be changed too?

**Comment by topepo** [comment]
> one wants to add additional columns of metadata to `term_info` from inside custom steps

Can you give an example of that? You would probably need to have other selectors too (analogous to `has_role` and others).

**Comment by galalH** [comment]
I work with survey data a lot so I'd like to have a step that loads parts of the codebook into term_info which could later be referenced from custom check_*() functions to validate that the data takes on valid values only. It's also common when working with survey data to get NAs that result from skip logic in the survey questionnaire rather than missing responses. Being able to add a column to term_info that flags variables where NAs are benign would allow for writing a variant of check_missing(all_predictors()) that doesn't choke on these columns.

I realize that it's possible to implement similar functionality by passing the codebook as an argument to the different check functions, but the code would be cleaner if there's just one step to ingest it and make it available to all the following steps and checks in a recipe.

**Comment by juliasilge** [comment]
This is not currently in our development plans in the short to medium term, so we're going to close out this issue. Thank you for sharing your feedback! 🙌
