### ISSUE TITLE
Compatibility issue  0.1.2 / 0.1.3

### ISSUE THREAD

**Issue by nibortolum** [tidymodels/recipes#162]
Hi all,

just to mention that I have compatibility issues between recipes 0.1.3 and recipes 0.1.2.
I have a recipe object defined with recipes 0.1.2 and saved within an Rdata file.

The recipe is fairy simple : 
rec_obj <- recipe(Churn ~ ., data = train_tbl) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_center(all_predictors(), -all_outcomes()) %>%
  step_scale(all_predictors(), -all_outcomes()) %>%
  prep(data = train_tbl)

but whenever I load rec_obj and try to bake() with recipes 0.1.3, i got an error "wrong argument type"

the following example works fine if entirely executed with whether 0.1.2 or 0.1.3.
bake() fails with 0.1.3 if rec_obj was defined under 0.1.2

Cheers,
nibor

```{r}
library(caret)
library(tidyr)
library(recipes)
library(rsample)

### load data (file is in the zip attached)
churn_data_raw <- read.csv("data/WA_Fn-UseC_-Telco-Customer-Churn.csv")
# Remove unnecessary data
churn_data_tbl <- churn_data_raw %>%
  drop_na() %>%
  select(Churn, everything())

# Split test/training sets
set.seed(100)
train_test_split <- initial_split(churn_data_tbl, prop = 0.8)
train_test_split

# Retrieve train and test sets
train_tbl_with_ids <- training(train_test_split)
test_tbl_with_ids  <- testing(train_test_split)

train_tbl <- select(train_tbl_with_ids, -customerID)
test_tbl <- select(test_tbl_with_ids, -customerID)


# Create recipe
rec_obj <- recipe(Churn ~ ., data = train_tbl) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_center(all_predictors(), -all_outcomes()) %>%
  step_scale(all_predictors(), -all_outcomes()) %>%
  prep(data = train_tbl)

x_train_tbl <- bake(rec_obj, newdata = train_tbl) %>% select(-Churn)
x_test_tbl  <- bake(rec_obj, newdata = test_tbl) %>% select(-Churn)
```
[WA_Fn-UseC_-Telco-Customer-Churn.zip](https://github.com/topepo/recipes/files/2114808/WA_Fn-UseC_-Telco-Customer-Churn.zip)

**Comment by juliasilge** [comment]
Thanks for your discussion here! 🙌  We are closing out older issues. If you have a similar problem after updating to the current version of recipes, please open a new issue.
