### ISSUE TITLE
imbalance sampling methods

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#165]
Start another add-on package that has these methods:

- [ ] `DMwR::SMOTE`
- [ ] `ROSE::ROSE`
- [ ] assorted functions from the `imbalance` function. 
- [ ] move/replicate `step_downsample`
- [ ]  look into the `smotefamily` and `ebmc` packages

**Comment by topepo** [comment]
`balance` sounds great.

**Comment by EmilHvitfeldt** [comment]
For reference, work on this issue is done in https://github.com/EmilHvitfeldt/themis

**Comment by EmilHvitfeldt** [comment]
This issue should be closed with the release of themis on CRAN 🎉

**Comment by juliasilge** [comment]
themis is now on CRAN 👍
