### ISSUE TITLE
Oblique principle components clustering / varclust step?

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/recipes#173]
I'm curious if a step for [oblique principle components clustering][1] would see much use:

```r
step_varclus(recipe, ...)
```

I'm not sure if many people would use this, but Harrell pushes it pretty hard in his book and [`Hmisc::varclus()`][2] implements something related (a quick look seems to me like just hierarchical clustering on top of a similarity matrix but no oblique rotation?). So far as I know that's the only R implementation, although there's also [PROC varclus][3] in SAS.

Mostly I'm just curious how well this sort of thing works. If it gets used a lot in biostats might be worth having a step for, and also potentially including in the feature engineering book.

Would love to see this written up into a small package for people to experiment with. Doesn't seem like that much work but would want to see enthusiasm/interest from others before starting to take that on.

[1]: https://www.researchgate.net/profile/Ton_Schaik/publication/242249665_A_Note_on_Oblique_Principal_Component_Cluster_Analysis/links/0c960520b7323d2cc3000000/A-Note-on-Oblique-Principal-Component-Cluster-Analysis.pdf
[2]: https://github.com/harrelfe/Hmisc/blob/master/R/varclus.s
[3]: https://www.listendata.com/2015/03/proc-varclus-explained.html

**Comment by alexpghayes** [comment]
Also relevant: `Hmisc::transcan()`

**Comment by topepo** [comment]
Can the clustering defined on the training data be projected/applied to a new data set?

**Comment by alexpghayes** [comment]
Yes. The new variables are still linear combinations of the original predictors.

**Comment by topepo** [comment]
It looks like this will happen if someone puts in a PR. Closing for now but hope that someone implements this (it should probably go in the `embed` package though).
