### ISSUE TITLE
What is `step_name()`?

### ISSUE THREAD

**Issue by rorynolan** [tidymodels/recipes#182]
What is `step_name()`? I see it in https://tidymodels.github.io/recipes/articles/Simple_Example.html but it doesn't seem to be an exported function.

**Comment by topepo** [comment]
It is a generic placeholder for whatever step you are using (e.g. `step_{X}`).

**Comment by rorynolan** [comment]
Ah right, I stupidly thought `rec_obj %>% step_name(arguments)` was a (re)naming of some of the model variables (arguments) in `rec_obj`. 
Perhaps `step_{X}` as you have it above would be clearer, as that couldn't be a real function name, or perhaps I'm the only fool who didn't understand. 
Thanks for the reply and for all of your work on modelling in R. I stand on your shoulders every day :-)

**Comment by topepo** [comment]
> Perhaps `step_{X}` as you have it above would be clearer,

That is better and you shouldn't feel bad about assuming that there was a `step_name`.

**Comment by rorynolan** [comment]
Thanks  Max :-)
