### ISSUE TITLE
step_dummy: separator option for naming

### ISSUE THREAD

**Issue by mdancho84** [tidymodels/recipes#183]
Max,

Loving working with this package. One thing I run into from time to time is to associate the dummy variable with the original variable name. It might make things easier if you include a separator option similar to `stringr::str_c(sep = "_")` for the `step_dummy()` function. 

It would make it easy to `str_split()` the base name from the appended dummy piece of the name. 

Let me know if you agree.

Thanks, Matt

**Comment by topepo** [comment]
Would the `names` argument to `step_dummy` solve this? It defaults to:

```r
recipes::dummy_names <- function (var, lvl, ordinal = FALSE) {
    if (!ordinal) 
        nms <- paste(var, make.names(lvl), sep = "_")
    else nms <- paste0(var, names0(length(lvl), "_"))
    nms
}
```

but you could pass your own function.

**Comment by topepo** [comment]
Should I close this? Does it work for you?

**Comment by mdancho84** [comment]
I can work up a PR hopefully next week. With Jonathan at S&P this week. Also congrats on the Davis hire. He's a great add, and he'll be a big benefit to your team.

**Comment by topepo** [comment]
That's simple enough; done. 

Yeah, Davis is great. I feel like we have 4 people instead of 2.5.
