### ISSUE TITLE
factor2integer or arbitrary transformations

### ISSUE THREAD

**Issue by kevinykuo** [tidymodels/recipes#185]
Could we have a `step_factor2int()` or something similar to convert factors into integers? Ideally with a `from` parameter that specifies the indexing (e.g. 0- or 1- based). Use case here is feeding data into embedding layers of keras models.

Alternatively, maybe there can be a `step_lambda()` that takes a user defined function for random use cases like this?

**Comment by topepo** [comment]
> Could we have a `step_factor2int()` 

This goes against every notation that I hold dear... but I know why you need it for sparks so okay. 

> Alternatively, maybe there can be a `step_lambda()` that takes a user defined function for random use cases like this?

We'll be adding some `dplyr` steps like `mutate` and that would solve the issue too.

**Comment by kevinykuo** [comment]
Actually, what we really need is a `step_stringindexer()` or a `step_labelencoder()`, which should be less cringy than `step_factor2int()`. These also exist in sklearn and Spark.

Either way, we'll be in a better state than the current workaround in the wild which is "`step_string2factor(ordered = TRUE) %>% step_ordinalscore()`".
