### ISSUE TITLE
step_dummy allow all_predictors()

### ISSUE THREAD

**Issue by kagray** [tidymodels/recipes#186]
Reminder to review all_predictors() to be used in step_dummy

**Comment by topepo** [comment]
What was the alternative that we discussed? It would be easy to ignore those that are not factors (and write a warning).

**Comment by kagray** [comment]
I think that is exactly what we discussed. To simplify the process allow all_predictors and ignore numeric values.

On Sep 1, 2018, at 5:49 PM, Max Kuhn <notifications@github.com<mailto:notifications@github.com>> wrote:


What was the alternative that we discussed? It would be easy to ignore those that are not factors (and write a warning).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/a/1/1IDDNYoNMwcSeKkMWAngX5zy2gatE5aJcAsGxpl3fy8=?d=7N-K9GMA0spvLeBrpOk4mM01On_VfLBn0BOnjq5I9cyJdK49-La7GucDssO53awLmISPemtmupZkBMQA83FNjuqaYNVSUCpYGYJaYr0BY35mqlLRD9IKVNL9f8UV2ridwWKuxdkYSfQUeQWuQr12d2puCNppnDqxmsAEHrO6KbxYfNGWtCRpR3u4rshSJR8Colbu9hSP9DoZBJaU6o6wOk-cUI_kB2Z9jwwlpdXVlCSargj58zP7emUod75QICJ_6fmegT0ncKz_5P4i2qiTD4fAT-qUOIArEeBT5zJ9SZx_Ntvd-EvgbcUTm447-x7n3WAuIGsYycFtI2IhA1Y7zJ2XaeUHjmeG2UM9fd1K5lhnPbaLLx4zJU7s8b5Vnk_0wnT2nVWJvLM8di3Aue_I3t9x5jjGYuY9ixWuzsG6yZU%3D&u=https%3A%2F%2Fgithub.com%2Ftidymodels%2Frecipes%2Fissues%2F186%23issuecomment-417889387>, or mute the thread<https://clicktime.symantec.com/a/1/DRIxBmvpA15XfmvuVPjf9JER9cii_cBmPTwyigmlhiM=?d=7N-K9GMA0spvLeBrpOk4mM01On_VfLBn0BOnjq5I9cyJdK49-La7GucDssO53awLmISPemtmupZkBMQA83FNjuqaYNVSUCpYGYJaYr0BY35mqlLRD9IKVNL9f8UV2ridwWKuxdkYSfQUeQWuQr12d2puCNppnDqxmsAEHrO6KbxYfNGWtCRpR3u4rshSJR8Colbu9hSP9DoZBJaU6o6wOk-cUI_kB2Z9jwwlpdXVlCSargj58zP7emUod75QICJ_6fmegT0ncKz_5P4i2qiTD4fAT-qUOIArEeBT5zJ9SZx_Ntvd-EvgbcUTm447-x7n3WAuIGsYycFtI2IhA1Y7zJ2XaeUHjmeG2UM9fd1K5lhnPbaLLx4zJU7s8b5Vnk_0wnT2nVWJvLM8di3Aue_I3t9x5jjGYuY9ixWuzsG6yZU%3D&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKfU5bmqwN7IiwtTkQ0V4B-UTwhET7SSks5uWwDOgaJpZM4WKC3D>.

This communication (including any attachments) is confidential and is intended to be privileged pursuant to applicable law. If you are not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, then you are hereby notified that the dissemination, distribution or copying of this communication is prohibited. If you received this communication in error, please notify Smithfield Foods, Inc. immediately by telephone (+1 757-365-3000) and then delete this communication and destroy all copies thereof.

**Comment by topepo** [comment]
> I think that is exactly what we discussed. To simplify the process allow all_predictors and ignore numeric values.

Non-factors includes character data too (fyi)

**Comment by topepo** [comment]
Give that a try and test on your own data.

**Comment by kagray** [comment]
Ok will do thanks



Kent Gray, Ph.D.
Director of Genetic Research and Development
Smithfield Premium Genetics

Office: (910) 282-4227
Cell: (919) 609-6858
kgray@smithfield.com
