### ISSUE TITLE
tidyr::fill analogue

### ISSUE THREAD

**Issue by grayskripko** [tidymodels/recipes#187]
Is it possible to create such a step?

I thought about ```step_lag``` and ```step_rollimpute(statistics = dplyr::first, window = 3)``` but both cases definitely don't have enough vision for a long row of missing values ```c(1, rep(NA, 100), 3)```

**Comment by topepo** [comment]
Would `step_meanimpute` work for this? If not, we are going to add a simple `mutate` ability in `recipes` that would be a better solution than another step.

**Comment by grayskripko** [comment]
``` r
library(tidymodels)
library(tidyverse)

tibble(a = c(1, NA, 2, NA)) %>% tidyr::fill(a)
#> # A tibble: 4 x 1
#>       a
#>   <dbl>
#> 1     1
#> 2     1
#> 3     2
#> 4     2
tibble(a = c(1, NA, 2, NA)) %>% recipe(~ .) %>% step_meanimpute(a) %>% prep(retain = T) %>% juice()
#> # A tibble: 4 x 1
#>       a
#>   <dbl>
#> 1   1  
#> 2   1.5
#> 3   2  
#> 4   1.5
```

Created on 2018-08-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by grayskripko** [comment]
I dont see the reason why it can not be a step. In fact, it's another one kind of imputation.
It would be great to have something like step_accumulate as a flexible function for many purposes
``` r
library(tidyverse)
# here .x can be treated as "previous" element, .y - current
c(1, NA, 2, NA) %>% accumulate(~{if (is.na(.y)) .x else .y})
#> [1] 1 1 2 2

# it can be useful to count the amount of NAs in a row as a new feature for your model
c('a', NA, NA, 'b') %>% accumulate(~{if (is.na(.y)) .x + 1 else 0}, .init = 0) %>% tail(-1)
#> [1] 0 1 2 0
```

Created on 2018-08-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I like ```step_rollimpute(..., statistic = ...)``` because of its flexibility and wish to see more flexible steps like this. Construction of your own custom step is something very bulky and expensive. But I'm definitely don't see obstacles and problems and maybe it's impossible to implement this step.

**Comment by topepo** [comment]
I'm not saying that it couldn't be done but the overhead is much smaller if it can be done via `mutate`. That would have eliminated the log, sqrt, and other steps in the package and generally reduced overhead and complexity.

**Comment by grayskripko** [comment]
Maybe I've got your idea. Will wait for that release. Thank you
