### ISSUE TITLE
enable set.seed for any recipe steps that are not deterministic

### ISSUE THREAD

**Issue by sheffe** [tidymodels/recipes#188]
This is a cross-post from a [`caret` issue](https://github.com/topepo/caret/issues/928) that affects `recipes`.

Right now, `caret` preps a `recipe` twice: once to generate the dataset that `finalModel` is trained on, and, in a second step outside the `finalModel` training, it generates a second prepped recipe that is returned with the rest of the `train` output. The latter is what `caret` uses for transforming new data during later predictions out.

This means that any `recipes` steps that are not deterministic - I think the main cases that would affect users now are `step_upsample` and `step_downsample` - will lead to a caret `finalModel` that is not trained on the same dataset as the preprocessing recipe included for later. This is likely to be an invisible bug, except in cases where the difference between randomly-generated up/down-samples during the different recipe preparations becomes large enough to cause some downstream changes in (eg) which features are retained.

**Comment by topepo** [comment]
The way to solve this would be to add `seed` arguments (and to default them to something like `sample.int(10^5, 1)`) and execute the code using `withr::with_seed`.
