### ISSUE TITLE
Helpers for boolean/logical columns

### ISSUE THREAD

**Issue by ClaytonJY** [tidymodels/recipes#193]
There's a weird friction with modeling-in-R and logical columns; I'd argue that logical encoding is much more informative than 1/0 for most cases, but we can't trust modeling functions to convert those to 1/0 as needed. This means I often prepare a dataset to include logical columns (e.g. `is_foobar`) where appropriate, but then need to do something like `mutate_if(is.logical, as.integer)` just before moving into the `recipes` part of a modeling workflow.

Would it make sense to allow `recipes` to have helpers for logical columns?

I can imagine a few additions that would be helpful:
1. add a selector like `all_logical`, `all_boolean`, or even `all_bin`/`all_binary` (which might also grab 1/0 int cols and other 2-valued columns, though perhaps this is dangerous)
2. allow `step_bin2factor` to work with `logical` columns. This is often what I want to do, possibly followed by something like `step_dummy`, but I can't currently do that without making it an integer first, which can't be done in `recipes` AFAICT. Depending on interpretation of `bin`, I could also imagine this step handling _anything_ with only 2 values; strings, ints, doubles, logicals, etc.
3. add steps like `step_lgl2int`, `step_lgl2factor` (would be superceded by above)

My gut says that being overly broad in interpretation of "binary" is probably dangerous, and also untidy; best to stick with the type-safety encouraged by `purrr` and `rlang`? I think this also suggests `bin2factor` is not a great name; `int2factor` would be both more informative, and could be more broadly useful (would _have_ to give levels when >2, perhaps).

I suspect there might be other good ways to encode logical columns, but I think the core of the problem is allowing easy selection of them, and allowing conversion to 1/0 integers.

If this is a reasonable proposal I'm happy to do the implementation once a scope is determined.

**Comment by reisner** [comment]
@ClaytonJY I agree this would be useful in general. 

For my particular use, I only had one logical column, so I was able to add this to my recipe:
```
step_mutate(logical_column = as.numeric(logical_column))
```

**Comment by vspinu** [comment]
Why is there no `step_mutate_if`?

**Comment by DavisVaughan** [comment]
Ideally you'd be able to use `step_mutate()` with `across(where(is.Date), fn)` but this bug keeps you from being able to do that https://github.com/tidymodels/recipes/issues/759

`mutate_if()` and `mutate_at()` are superseded in favor of `across()`, so I'd prefer not to add `step_mutate_if()` to recipes, and to mark `step_mutate_at()` as superseded

**Comment by EmilHvitfeldt** [comment]
Once https://github.com/tidymodels/recipes/pull/1064 is merged, then you can use `step_bin2factor()` with logical variables. Together with the addition of `all_logical()` and `all_logical_predictors()` from https://github.com/tidymodels/recipes/pull/993, I think we have enough to close this issue.

``` r
library(recipes)

mtcars$vs <- as.logical(mtcars$vs)
mtcars$am <- as.logical(mtcars$am)

recipe(~., data = mtcars) |>
  step_mutate(across(where(is.logical), as.numeric)) |>
  prep() |>
  bake(new_data = NULL)
#> # A tibble: 32 × 11
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # … with 22 more rows

recipe(~., data = mtcars) |>
  step_bin2factor(all_logical_predictors()) |>
  prep() |>
  bake(new_data = NULL)
#> # A tibble: 32 × 11
#>      mpg   cyl  disp    hp  drat    wt  qsec vs    am     gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <fct> <fct> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5 no    yes       4     4
#>  2  21       6  160    110  3.9   2.88  17.0 no    yes       4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6 yes   yes       4     1
#>  4  21.4     6  258    110  3.08  3.22  19.4 yes   no        3     1
#>  5  18.7     8  360    175  3.15  3.44  17.0 no    no        3     2
#>  6  18.1     6  225    105  2.76  3.46  20.2 yes   no        3     1
#>  7  14.3     8  360    245  3.21  3.57  15.8 no    no        3     4
#>  8  24.4     4  147.    62  3.69  3.19  20   yes   no        4     2
#>  9  22.8     4  141.    95  3.92  3.15  22.9 yes   no        4     2
#> 10  19.2     6  168.   123  3.92  3.44  18.3 yes   no        4     4
#> # … with 22 more rows
```

<sup>Created on 2022-12-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
