### ISSUE TITLE
referencing/using previous steps

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#198]
There are a variety of applications where it would be helpful for the current step to be able to reference the previous step (examples are #155 and [EmilHvitfeldt/textrecipes#3](https://github.com/EmilHvitfeldt/textrecipes/issues/3)). 

For example, if we center a column but want to uncenter it later, we would need the means from the previously executed `step_center`. 

The issue is in how the steps are executed. A simplified version of this is:

```r
for (i in seq(along = x$steps)) {
  if (!x$steps[[i]]$trained | fresh) {
    x$steps[[i]] <- prep(x$steps[[i]], training = training, info = x$term_info)
    training <- bake(x$steps[[i]], newdata = training)
  }
}
```

The most simplistic solution would be to pass _all of the previous_ steps to `prep` so that they can be referenced. Even with this access, there is no good way to refer to a previous step. The index could be used but is a poor choice. 

This thread is to start a discuss on how this can be solved in future versions that doesn't wreck objects created form the previous version. 

[edit] fixed link

**Comment by EmilHvitfeldt** [comment]
One consideration is that currently some `textrecipes` workflows requires the same step to appear multiple times in the same pipeline.

If you want the tf-idf of the stemmed trigrams you would want to do 

```r
library(recipes)
library(textrecipes)

data(okc_text)
okc_rec <- recipe(~ ., data = okc_text) %>%
  step_tokenize(essay0, token = "words") %>%  # Tokenizes into words
  step_stem(essay0) %>%                       # Stems the words
  step_untokenize(essay0) %>%                 # pastes the stemmed words back together
  step_tokenize(essay0, token = "ngrams") %>% # tokenizes into trigrams
  step_tfidf(essay0)                          # Calculates tfidf of trigrams
# step_itidf not finish as of time of this comment
```

This would mean that simply a reference to the name of the step isn't enough. Furthermore you would also need to include something that invalidates references if intermediate steps are taken.

**Comment by topepo** [comment]
(somewhat off-topic for this thread but...)

You might consider doing a check for tokenization in the other steps and automatically do an untokenize process  if that is needed in the minority of the steps. `step_untokenize` is still needed but doing it when needed (with a warning) is probably a good idea.

**Comment by EmilHvitfeldt** [comment]
Should the decision of reference be placed in the step to be references or the step that references?

**Comment by topepo** [comment]
My thought was to add `id` as the last argument in the steps and default it to `stringi::stri_rand_strings(1, 11)`. Please can use `id = "my_cool_step"` but otherwise use a jumble. 

`prep`, on first call, would check for uniqueness.

**Comment by topepo** [comment]
Implementations of this are in the [`id_field` branch](https://github.com/tidymodels/recipes/tree/id_field). I'll merge in a few days. `rand_id` creates the ID values. I'll probably not automatically do the uniqueness check but instead check when people make references to the ID fields. 

One other thing that I did in this branch was to remove the default argument values for the constructor functions (e.g. `step_center_new`).

**Comment by juliasilge** [comment]
Finished now ✅
