### ISSUE TITLE
Adding step_select()

### ISSUE THREAD

**Issue by lorenzwalthert** [tidymodels/recipes#199]
It would be nice to have an analogue of `step_rm()` to select variables (much like `dplyr::select()`). If it already exists (I could not find it), it seems meaningful to reference it in the documentation of `step_rm()`. What do you think?

**Comment by topepo** [comment]
We will be adding some `dplyr` verbs like `mutate`, `filter`, and `select` to recipes. I believe that those will take care of the request.

**Comment by lorenzwalthert** [comment]
Yes thanks.

**Comment by DavisVaughan** [comment]
Reopening at the request of @edgararuiz. @topepo why wasn't `step_select()` implemented?

The use case was just to be able to intuitively do `step_select(all_numeric())`
