### ISSUE TITLE
Feature proposal: progress bar

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#204]
I was wondering if it would be possible to add a progress bar to indicate what step/variable is currently being worked on.

**Comment by topepo** [comment]
I'm probably in the minority but I haaaaate progress bars. There's the current `verbose` option which logs progress with more information.

**Comment by EmilHvitfeldt** [comment]
I'm so sorry! I overlooked that option. It is what I was looking for. 

Would it be possible to include a `verbose` argument In `bake` too?

**Comment by EmilHvitfeldt** [comment]
Perfect!
