### ISSUE TITLE
roles and possible type to list columns

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#221]
In the spirit of breaking changes for the next version...  ☹️

For example:

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
recipe(Sepal.Length ~ ., data = iris) %>%
  summary()
#> # A tibble: 5 x 4
#>   variable     type    role      source  
#>   <chr>        <chr>   <chr>     <chr>   
#> 1 Sepal.Width  numeric predictor original
#> 2 Petal.Length numeric predictor original
#> 3 Petal.Width  numeric predictor original
#> 4 Species      nominal predictor original
#> 5 Sepal.Length numeric outcome   original
```

Created on 2018-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

There are certainly occasions where a column can play more than one role. 

We also might want to have more granular `type` attributes. For example, should a date field have types of "numeric" and "date"?

This would affect the functionality of `add_role` and we might need an additional `change_role` since the former should append and the latter should reset.

**Comment by EmilHvitfeldt** [comment]
This change would also need changes to the various check functions that now expect a single type/role. 

Would you ever need to have exclusive selections?
Selection all the numeric types that aren't date types.

Additionally, should `change_role` replace a single type with another or replace the entire list of types? Having the `change_role` reset the types might remove type information not considered in said step.

Maybe having `add_role`, `change_role` and `reset_role` might work.

``` r
roles <- c("numeric", "date")

add_role(roles, "fun")
#> [1] "numeric" "date" "fun"

change_role(roles, from = "numeric", to = "character")
#> [1] "character" "date"

reset_role(roles, "character")
#> [1] "character"
```
