### ISSUE TITLE
Dummies when the values may be in many columns

### ISSUE THREAD

**Issue by melondonkey** [tidymodels/recipes#228]
Maybe I missed how to do this in the documentation, but it'd be nice to have a step for creating dummies when the values may be held in multiple columns.  For example, diagnosis codes may be in many columns (Secondary Dx 1--X) but we don't really care which one it's in. 

My usual (messy) workflow for this would be something like: 

``` r
library(reshape2)
df <- rbind.data.frame( c('a', 'b', 'c'), c('d', 'a', 'c'), c('b', 'd', 'a'), stringsAsFactors = FALSE)
colnames(df) <- c('v1', 'v2', 'v3')

head(df)
#>   v1 v2 v3
#> 1  a  b  c
#> 2  d  a  c
#> 3  b  d  a

df$id <- c(1,2,3)


df2 <- dcast( melt(df ,id.var='id'), 
              id ~ value, 
              length)

head(df2)
#>   id a b c d
#> 1  1 1 1 1 0
#> 2  2 1 0 1 1
#> 3  3 1 1 0 1
```

<sup>Created on 2018-10-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by topepo** [comment]
You could solve this using `step_mutate()` with a `case_when()`.
