### ISSUE TITLE
Is there a function to convert the prediction to the original base?

### ISSUE THREAD

**Issue by JiaxiangBU** [tidymodels/recipes#231]
I run a simple `lm`, and get the prediction of `cyl`.  Before I do `lm`, I arrange transformation like `step_BoxCox`,  `step_center`  and `step_scale`. All they make my prediction around `3.09`. 
But the original `cyl` is about `20.09062`. 
Is there any function in `recipes` to inversely convert predictions to the original base.

``` r
library(tidyverse)
library(recipes)
#> 载入需要的程辑包：broom
#> 
#> 载入程辑包：'recipes'
#> The following object is masked from 'package:stringr':
#> 
#>     fixed
#> The following object is masked from 'package:stats':
#> 
#>     step
train_data <- 
    mtcars %>% 
    mutate(cyl = as.factor(cyl))
train_data %>% 
    recipe(
        mpg ~ cyl + disp
        ,data = .
    ) %>% 
    step_BoxCox(mpg,disp) %>% 
    step_dummy(cyl) %>% 
    step_center(all_predictors()) %>% 
    step_scale(all_predictors()) %>% 
    prep(training=train_data,retain=TRUE,verbose=TRUE) %>% 
    bake(newdata = train_data) %>% 
    lm() %>% 
    augment() %>% 
    summarise(mean(mpg))
#> oper 1 step BoxCox [training] 
#> oper 2 step dummy [training] 
#> oper 3 step center [training] 
#> oper 4 step scale [training]
#> # A tibble: 1 x 1
#>   `mean(mpg)`
#>         <dbl>
#> 1        3.09
mtcars %>% 
    summarise(mean(mpg))
#>   mean(mpg)
#> 1  20.09062
```

<sup>Created on 2018-10-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by topepo** [comment]
For now there isn't but it is on the list of activities to start on after the upcoming release. 

One note though. The use of the Box-Cox procedure in `recipes` is aimed towards predictors and not the outcome (which is was originally devised for). If you want to use it for the outcome, it would have to be incorporated into the linear model fit itself. For that, I'd recommend the [`boxCox`](https://www.rdocumentation.org/packages/car/versions/2.1-4/topics/boxCox) function.
