### ISSUE TITLE
export additional helper functions

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#250]
`format_selectors` and `format_ch_vec`

**Comment by khailper** [comment]
I'll claim this one.

**Comment by khailper** [comment]
`format_selectors` has a `wdth` parameter, but `format_ch_vec` uses `width` for the same purpose. Should I edit the source code to make the variable names consistent?

**Comment by DavisVaughan** [comment]
For the issue solver:

- Unify the argument names: `wdth` -> `width`
- Remove the `...` from `format_selectors()`
- Can the name of `format_ch_vec()` be more informative?
- These changes mean you will also have to modify the internal usage of these functions to make sure they are still working correctly

**Comment by topepo** [comment]
@khailper If you want, go ahead and export them then I can edit the PR with the documentation (after I get out of a meeting in about an hour).

**Comment by khailper** [comment]
Post export, I assume that these functions should have separate tests (instead of simply being tested as part of the functions that call them). Should I include those as part of this PR, or does that belong in a seperate issue?

**Comment by khailper** [comment]
> * Can the name of `format_ch_vec()` be more informative?

@DavisVaughan maybe `format_chr_vec()` as an alternative? (in the vein of `purrr::map_chr()`)

**Comment by khailper** [comment]
I'm going to submit the PR without changing the name of `format_ch_vec()`, but if we can converge on a new name, then I'd be happy to update the relevant internal usage.
