### ISSUE TITLE
protection against deletion

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#252]
We should be able to whitelist columns so that none of the filtering steps can remove certain variables. 

If a step is used (`step_protect`? `step_whitelist`? ) to specify the variables, I think that we'd need to keep the column list outside of the steps and have then refer to the variable list.

**Comment by simonpcouch** [comment]
Totally on board for this! +1 to `step_protect()` or otherwise. Let's [not use "whitelist"](https://www.splunk.com/en_us/blog/learn/blacklist-whitelist-inclusivity.html).

**Comment by EmilHvitfeldt** [comment]
don't let this happen to outcomes, case weights

**Comment by hfrick** [comment]
and by now it's a `role`, not a `step` :D

**Comment by EmilHvitfeldt** [comment]
I tried getting it to work, and in the end it didn't feel right.
