### ISSUE TITLE
Design question: keeping/deleting variables in steps at will

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#253]
In the future I plan on creating some steps that will extract information out of a variable (text listcolumn in textrecipes) and create new variables with them, much in the same way `step_pca` works. However I would like to be able to keep the original variables for later use.

So in this example `step_sentiment` would create a sentiment variable based on the text variable without deleting it as it is needed in `step_tfidf`. 
```r
okc_rec <- recipe(~ ., data = okc_text) %>%
  step_tokenize(text) %>%
  step_sentiment(text, keep_var = TRUE) %>%
  step_tfidf(text)
```

However in this example we would like  `step_sentiment` to create a sentiment variable and delete the text variable as it is no longer needed.

```r
okc_rec <- recipe(~ ., data = okc_text) %>%
  step_tokenize(text) %>%
  step_sentiment(text)
```

Is this something that you think should be supported within the recipe framework?

**Comment by topepo** [comment]
You could use `step_rm` to get rid of it or you could add an option to steps like `step_sentiment` that removes the input variable after it is processed.

**Comment by EmilHvitfeldt** [comment]
Perfect! 👍
