### ISSUE TITLE
Better naming for step_classdist and step_depth

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#262]
From #261 add an options similar to `step_dummy` or `step_pca` that allows for more flexibility when naming the new variables. Do the same for `step_depth`.

**Comment by gdequeiroz** [comment]
On it!

**Comment by gdequeiroz** [comment]
Progress
--------------------------------
- [ ] Add argument prefix to the`step_classdist` function
- [ ] Add document to reflect the change
- [ ] Add tests
- [ ] Add argument prefix to the `step_depth` function
- [ ] Add document to reflect the change
- [ ] Add tests

**Comment by juliasilge** [comment]
This is closed in #468. Thank you so much @gdequeiroz! 👯‍♀️

**Comment by gdequeiroz** [comment]
@juliasilge Thank you for doing the work and closing this!
