### ISSUE TITLE
Add ID interface to `tidy()` method for steps

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/recipes#273]
At rstudioconf, I got a question about extracting the information from an individual estimated step. For example, with box cox, maybe you wanted to know the exact value of lambda for the estimated step.

We could have a new verb that accepts a prepped recipe, and extracts the step information by `id` name. It would be as simple as `rec$steps[[1]]` for the first step (or a more specialized way that finds the right id name and returns that step).

I don't think we need to return the information in any special way, just return the list of info corresponding to that step, and let the user process it however they want.

**Comment by ericlecoutre** [comment]
If I am correct, you access step output using "res" slot.
then function is: implement 

`step_result <- function(recipe,id) recipe$steps[[id]]$res`

**Comment by topepo** [comment]
We already have this:

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

recipe(~ ., data = as.data.frame(state.x77)) %>% 
  step_BoxCox(all_numeric()) %>% 
  prep(training = as.data.frame(state.x77)) %>% 
  tidy(number = 1)
#> # A tibble: 7 x 3
#>   terms          value id          
#>   <chr>          <dbl> <chr>       
#> 1 Population  0.000966 BoxCox_fYTWp
#> 2 Income      0.524    BoxCox_fYTWp
#> 3 Illiteracy -0.379    BoxCox_fYTWp
#> 4 Life Exp    4.59     BoxCox_fYTWp
#> 5 Murder      0.606    BoxCox_fYTWp
#> 6 HS Grad     1.92     BoxCox_fYTWp
#> 7 Area        0.250    BoxCox_fYTWp
```

Created on 2019-01-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

I haven't added an `id` interface yet though. `number` is the step number in the recipe

**Comment by DavisVaughan** [comment]
A `id` interface would probably be useful. I changed the title to reflect that.
