### ISSUE TITLE
Suggestion: add a keep_vars arguments (for some steps)

### ISSUE THREAD

**Issue by ericlecoutre** [tidymodels/recipes#282]
I am thinking in particular on multivariate steps such as pca or ica.
Sometimes, I am interested in feature engineering so that I would like to generate PCA plus keep source variables.
As PCA allows adding prefix such as "PCA_", one may still manipulate source variables with a `-starts_with("PCA")`.
Same for `embed` package.

**Comment by topepo** [comment]
We'll add a `retain` options for 

- [ ] `step_pca`
- [ ] `step_ica`
- [ ] `step_nnmf`
- [ ] `step_kpca`
- [ ] `step_pls`
- [ ] `step_spatialsign`
- [ ] `step_isomap`

This should be pretty straightforward

**Comment by jonthegeek** [comment]
Working on this for tidy-dev-day
