### ISSUE TITLE
`n` argument for `step_other`

### ISSUE THREAD

**Issue by brshallo** [tidymodels/recipes#289]
Would like if `threshold` argument within `step_other()` could be specified by an integer (rather than just by proportion), or had a separate `n` argument to specify the minimum sample size before it is collapsed into the "other" category.  
E.g. to specify minimum sample size of 30:
```r
recipe(price ~ clarity + color + carat, data = diamonds) %>% 
  step_other(all_nominal(), n = 30)
```

I'm curious what the best way of doing this is currently? ([Link](https://gist.github.com/brshallo/a25cc71fc66cbdee4e8ce51b1f74d5ca) to hack for specifying consistent sample size to `step_other` across datasets of different sizes.)

**Comment by brshallo** [comment]
Using a `step_mutate()` with `forcats::fct_lump_min()` it seems would accomplish this.  Though is there a way to apply `step_mutate()` over `all_nominal()`, in the way one might with `mutate_if()`/`_at()`/`_all()` ?

**Comment by topepo** [comment]
Instead of adding a new argument, we could just use `threshold` and, if it is >1, treat it as a frequency.
