### ISSUE TITLE
allow empty selections for some steps

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#290]
If `step_other`, `step_dummy`, `step_corr`, `step_linearcomb` and a few others have selectors that do not return any columns, go ahead and return the data as-is.

**Comment by AnselmJeong** [comment]
Yes, `step_dummy` allows empty selection, so you can define like `step_dummy(all_nominal())` with a data.frame containing no factor variables. But it did not help anyway, because it still fails at the `prep` stage.

**Comment by topepo** [comment]
@AnselmJeong please test; I just committed a PR that may have solved this for you.
