### ISSUE TITLE
Custom step work fine while baking but not while used in caret::train 

### ISSUE THREAD

**Issue by dcornet** [tidymodels/recipes#294]
I developped a custom step in order to include it in some caret models.  While applying prep and bake on my new step, everything works fine. But when I try to include the unprepared recipe in caret::train I got the following error: "Error: No variables or terms were selected". Any advice welcome. 
Reproducible example and session info hereunder: 

```
packs <- c("tidyverse", "caret", "e1071", "wavelets", "recipes")
InstIfNec<-function (pack) {
    if (!do.call(require,as.list(pack))) {
        do.call(install.packages,as.list(pack)) }
    do.call(require,as.list(pack)) }
lapply(packs, InstIfNec)
```

# Getting data
```
data(biomass)
biomass<-select(biomass, -dataset, -sample)
```

# Custom pretreatment algo
```
HaarTransform<-function(DF1) {
    w<-function(k) { 
        s1=dwt(k, filter="haar")
        return (s1@V[[1]])
    }
    Smt=as.matrix(DF1)
    Smt=t(base::apply(Smt,1,w))
    return (data.frame(Smt))
}
```

# Create the custum step function
```
step_Haar_new<-function(terms=NULL, role=NA, trained=FALSE, skip=FALSE, 
                        columns=NULL) {
    step(subclass="Haar",  terms=terms, role=role,
         trained=trained, skip=skip, columns=columns)
}

step_Haar<-function(recipe, ..., role=NA, trained=FALSE, skip=FALSE,
                    columns=NULL) {
    terms=ellipse_check(...)
    add_step(recipe, 
             step_Haar_new(terms=terms, role=role, trained=trained,  
                           skip=skip, columns=columns))
}

prep.step_Haar <- function(x, training, info = NULL, ...) {
    col_names<-terms_select(terms = x$terms, info = info)
    step_Haar_new(terms = x$terms,  role = x$role, trained = TRUE, 
                  skip = x$skip, columns=col_names)
}

bake.step_Haar <- function(object, new_data, ...) {
    new_data<-HaarTransform(dplyr::select(new_data, object$columns))
    as_tibble(new_data)
}
```

# Test the recipe function
```
Haar_recipe<-recipe(carbon ~ ., biomass) %>% 
    step_Haar(all_predictors()) 

Haar_recipe%>%
    prep(biomass) %>%
    bake(biomass)   # all is fine

fit <- caret::train(Haar_recipe, data=biomass,
                    method="svmLinear")  # Error: No variables or terms were selected.`
```
R session: 
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] recipes_0.1.4    wavelets_0.3-0.1 e1071_1.7-0.1    caret_6.0-81     lattice_0.20-38 
 [6] forcats_0.4.0    stringr_1.4.0    dplyr_0.8.0.1    purrr_0.3.1      readr_1.3.1     
[11] tidyr_0.8.3      tibble_2.0.1     ggplot2_3.1.0    tidyverse_1.2.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0         lubridate_1.7.4    class_7.3-15       utf8_1.1.4         assertthat_0.2.0  
 [6] ipred_0.9-8        foreach_1.4.4      R6_2.4.0           cellranger_1.1.0   plyr_1.8.4        
[11] backports_1.1.3    stats4_3.4.4       httr_1.4.0         pillar_1.3.1       rlang_0.3.1       
[16] lazyeval_0.2.1     readxl_1.3.0       rstudioapi_0.9.0   data.table_1.12.0  kernlab_0.9-27    
[21] rpart_4.1-13       Matrix_1.2-15      splines_3.4.4      gower_0.2.0        munsell_0.5.0     
[26] broom_0.5.1        compiler_3.4.4     modelr_0.1.4       pkgconfig_2.0.2    nnet_7.3-12       
[31] tidyselect_0.2.5   prodlim_2018.04.18 codetools_0.2-16   fansi_0.4.0        crayon_1.3.4      
[36] withr_2.1.2        MASS_7.3-51.1      ModelMetrics_1.2.2 grid_3.4.4         nlme_3.1-137      
[41] jsonlite_1.6       gtable_0.2.0       magrittr_1.5       scales_1.0.0       cli_1.0.1         
[46] stringi_1.3.1      reshape2_1.4.3     timeDate_3043.102  xml2_1.2.0         generics_0.0.2    
[51] lava_1.6.5         iterators_1.0.10   tools_3.4.4        glue_1.3.0         hms_0.4.2         
[56] survival_2.43-3    yaml_2.2.0         colorspace_1.4-0   rvest_0.3.2        haven_2.1.0

**Comment by DavisVaughan** [comment]
There were a couple things off here:

- `step_Haar_new()` should probably not have defaults set. It will get values from `step_Haar()`
- `step_Haar()` should not set the `role = NA` by default. This is one of your big problems. It means that new columns don't have a role. Really this should be `role = "predictor"`
- `bake.step_Haar()` is currently _only_ returning the new columns that you created. This means that you lose all of the other predictors and outcomes that weren't involved in the step. I've tweaked it to remove the columns involved in the step and keep everything else.

``` r
library(tidyverse)
#> Warning: package 'tibble' was built under R version 3.5.2
#> Warning: package 'stringr' was built under R version 3.5.2
library(caret)
#> Loading required package: lattice
#> 
#> Attaching package: 'caret'
#> The following object is masked from 'package:purrr':
#> 
#>     lift
library(e1071)
library(wavelets)
#> Warning: package 'wavelets' was built under R version 3.5.2
library(recipes)
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stringr':
#> 
#>     fixed
#> The following object is masked from 'package:stats':
#> 
#>     step

data(biomass)
biomass <- dplyr::select(as_tibble(biomass), -dataset, -sample)

HaarTransform<-function(DF1) {
  w<-function(k) { 
    s1=dwt(k, filter="haar")
    return (s1@V[[1]])
  }
  Smt=as.matrix(DF1)
  Smt=t(base::apply(Smt,1,w))
  return (data.frame(Smt))
}

step_Haar_new<-function(terms, role, trained, skip, columns) {
  step(
    subclass="Haar",  
    terms=terms, 
    role=role,
    trained=trained, 
    skip=skip, 
    columns=columns
  )
}

step_Haar<-function(recipe, ..., role="predictor", trained=FALSE, skip=FALSE,
                    columns=NULL) {
  terms=ellipse_check(...)
  add_step(
    recipe, 
    step_Haar_new(
      terms=terms, 
      role=role, 
      trained=trained,  
      skip=skip, 
      columns=columns
    )
  )
}

prep.step_Haar <- function(x, training, info = NULL, ...) {
  col_names<-terms_select(terms = x$terms, info = info)
  step_Haar_new(
    terms = x$terms,  
    role = x$role, 
    trained = TRUE, 
    skip = x$skip, 
    columns=col_names
  )
}

bake.step_Haar <- function(object, new_data, ...) {
  transformable <- dplyr::select(new_data, object$columns)
  keepers <- dplyr::select(new_data, -c(object$columns))
  new_data <- HaarTransform(dplyr::select(new_data, object$columns))
  bind_cols(keepers, as_tibble(new_data))
}

Haar_recipe <- recipe(carbon ~ ., biomass) %>% 
  step_Haar(all_predictors()) 

Haar_recipe %>%
  prep(biomass) %>%
  juice()
#> # A tibble: 536 x 3
#>    carbon    X1    X2
#>     <dbl> <dbl> <dbl>
#>  1   49.8  30.7  14.1
#>  2   49.5  29.3  13.6
#>  3   47.8  32.8  13.0
#>  4   45.1  27.5  12.9
#>  5   46.8  29.5  13.1
#>  6   45.4  29.9  13.1
#>  7   47.2  28.9  13.3
#>  8   45.7  29.3  13.1
#>  9   48.8  29.5  13.2
#> 10   47.1  29.1  13.4
#> # … with 526 more rows

fit <- caret::train(
  Haar_recipe, 
  data=biomass,
  method="svmLinear"
)
#> Loading required namespace: kernlab
#> 
#> Attaching package: 'kernlab'
#> The following object is masked from 'package:purrr':
#> 
#>     cross
#> The following object is masked from 'package:ggplot2':
#> 
#>     alpha
```

<sup>Created on 2019-04-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
