### ISSUE TITLE
Object size of recipes

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/recipes#302]
Here's a thought. We currently store the `data` or `x` argument of a call to `recipe()` in the `$template` slot of the recipe. This is used for checking the types of column and the column names.

Other than that, the `$template` slot is not used, except for the rare case of someone calling `prep()` without a `training` argument. In that case, the `template` is used.

I would argue for two things:

- Take a 0-row slice of `data`/`x` as it comes in, and only store that in `$template`
- No longer allow the user to use `prep()` without the `training` argument

This would _always_ result in the __unprepped__ recipe object being small. Currently users have to know to take a 0-row slice and pass that to `recipe()`, which is not intuitive.

To keep the __prepped__ recipe small, you also have to call `retain = FALSE`, but this is much more clear because it is a documented argument, and not a special case.

I would also argue that you should always have to call `prep()` with a `training` argument, for consistency. Otherwise it feels a bit magical. Since it isn't documented that you can even call `prep()` without `training`, I think this would be a minimally painful breaking change with a lot of upside.

**Comment by dimagor** [comment]
Some support for this proposal with my user experience:

> As a user who works with sensitive data, I was under the impression that `retain = FALSE` would be sufficient for removing any underlying data. It was surprising to learn that `$template` also stored a copy of the data. 

At a minimum, this behavior needs to be more transparent. May be add a parameter to `recipe()` that makes it clear that this is the default.

**Comment by vspinu** [comment]
It's not just template which stores the data but every environment captured by language objects in the steps like `step_subset` and `step_other` (#760)

> Since it isn't documented that you can even call prep() without training, 

My impression was that having `prep` at the end of the pipeline is idiomatic. Even the `prep` doc example doesn't use `training` argument. It's likely to break a lot of code. 

Regarding `retain = F` I think it's a complication in the first place to have that argument. No recipe should retain any of the original data, preped or not prepped. The current limitation that  `prepped` recipes with `retain = F` cannot be extended seems artificial to me. 

My current workaround is to recursively map over the steps and clean all the environments. Something like this (where `rmap` is my home backed recursive mapper):

```R
clean_recipe <- function(rp) {
  rp$steps <-
    rmap(rp$steps, .ftail = function(x) {
      if (!is.null(attr(x, ".Environment"))) {
        attr(x, ".Environment") <- .GlobalEnv
      }
      x
    })
  if (!is.null(rp$template))
    rp$template <- head(rp$template, 10)
  rp
}
```

**Comment by EmilHvitfeldt** [comment]
This issue appears to have been resolved by the addition of the [butcher](https://butcher.tidymodels.org/) package.

``` r
library(recipes)

data("ames", package = "modeldata")

rec <- recipe(Sale_Price ~ ., data = ames) |>
  step_dummy(all_nominal_predictors()) |>
  step_zv(all_predictors()) |>
  step_normalize(all_numeric_predictors()) |>
  prep()

library(butcher)

lobstr::obj_size(rec)
#> 7.49 MB

rec_small <- butcher(rec)

lobstr::obj_size(rec_small)
#> 1.05 MB

weigh(rec)
#> # A tibble: 1,523 × 2
#>    object                                     size
#>    <chr>                                     <dbl>
#>  1 steps.naming                             0.772 
#>  2 last_term_info.variable                  0.0262
#>  3 steps.means                              0.0255
#>  4 steps.sds                                0.0255
#>  5 template.Neighborhood_College_Creek      0.0243
#>  6 template.Neighborhood_Old_Town           0.0243
#>  7 template.Neighborhood_Edwards            0.0243
#>  8 template.Neighborhood_Somerset           0.0243
#>  9 template.Neighborhood_Northridge_Heights 0.0243
#> 10 template.Neighborhood_Gilbert            0.0243
#> # … with 1,513 more rows
weigh(rec_small)
#> # A tibble: 1,523 × 2
#>    object                       size
#>    <chr>                       <dbl>
#>  1 steps.naming              0.772  
#>  2 last_term_info.variable   0.0262 
#>  3 steps.means               0.0255 
#>  4 steps.sds                 0.0255 
#>  5 term_info.variable        0.0232 
#>  6 var_info.variable         0.00534
#>  7 steps.levels.Neighborhood 0.00505
#>  8 steps.levels.MS_SubClass  0.00442
#>  9 steps.levels.Exterior_2nd 0.00402
#> 10 steps.levels.Exterior_1st 0.00395
#> # … with 1,513 more rows

rec$template
#> # A tibble: 2,930 × 275
#>    Lot_Frontage Lot_Area Year_…¹ Year_…² Mas_V…³ BsmtF…⁴ BsmtF…⁵ Bsmt_…⁶ Total…⁷
#>           <dbl>    <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
#>  1       2.49     2.74    -0.375  -1.16   0.0610  -0.975  -0.294  -0.269  0.0652
#>  2       0.667    0.187   -0.342  -1.12  -0.566    0.816   0.557  -0.658 -0.384 
#>  3       0.697    0.523   -0.442  -1.26   0.0386  -1.42   -0.294  -0.348  0.630 
#>  4       1.06     0.128   -0.111  -0.780 -0.566   -1.42   -0.294   1.11   2.40  
#>  5       0.488    0.467    0.848   0.658 -0.566   -0.527  -0.294  -0.960 -0.280 
#>  6       0.608   -0.0216   0.881   0.658 -0.454   -0.527  -0.294  -0.535 -0.284 
#>  7      -0.497   -0.663    0.980   0.802 -0.566   -0.527  -0.294   0.371  0.650 
#>  8      -0.437   -0.653    0.683   0.371 -0.566   -1.42   -0.294   1.04   0.519 
#>  9      -0.557   -0.604    0.782   0.562 -0.566   -0.527  -0.294  -0.328  1.23  
#> 10       0.0702  -0.336    0.914   0.706 -0.566    1.26   -0.294   0.990 -0.130 
#> # … with 2,920 more rows, 266 more variables: First_Flr_SF <dbl>,
#> #   Second_Flr_SF <dbl>, Gr_Liv_Area <dbl>, Bsmt_Full_Bath <dbl>,
#> #   Bsmt_Half_Bath <dbl>, Full_Bath <dbl>, Half_Bath <dbl>,
#> #   Bedroom_AbvGr <dbl>, Kitchen_AbvGr <dbl>, TotRms_AbvGrd <dbl>,
#> #   Fireplaces <dbl>, Garage_Cars <dbl>, Garage_Area <dbl>, Wood_Deck_SF <dbl>,
#> #   Open_Porch_SF <dbl>, Enclosed_Porch <dbl>, Three_season_porch <dbl>,
#> #   Screen_Porch <dbl>, Pool_Area <dbl>, Misc_Val <dbl>, Mo_Sold <dbl>, …
rec_small$template
#> # A tibble: 0 × 275
#> # … with 275 variables: Lot_Frontage <dbl>, Lot_Area <dbl>, Year_Built <dbl>,
#> #   Year_Remod_Add <dbl>, Mas_Vnr_Area <dbl>, BsmtFin_SF_1 <dbl>,
#> #   BsmtFin_SF_2 <dbl>, Bsmt_Unf_SF <dbl>, Total_Bsmt_SF <dbl>,
#> #   First_Flr_SF <dbl>, Second_Flr_SF <dbl>, Gr_Liv_Area <dbl>,
#> #   Bsmt_Full_Bath <dbl>, Bsmt_Half_Bath <dbl>, Full_Bath <dbl>,
#> #   Half_Bath <dbl>, Bedroom_AbvGr <dbl>, Kitchen_AbvGr <dbl>,
#> #   TotRms_AbvGrd <dbl>, Fireplaces <dbl>, Garage_Cars <dbl>, …
```

<sup>Created on 2022-12-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
