### ISSUE TITLE
[Feature Request] add more granularity to roles with respect to column type

### ISSUE THREAD

**Issue by alexhallam** [tidymodels/recipes#308]
The role `all_numeric` does not respect a dataframe that has logical, numeric, and integer. 

In addition to `all_numeric` it would be nice to have more granular roles such as `all_integer` , `all_logical` , `all_double`.

**Comment by DavisVaughan** [comment]
Integers and doubles are both treated as `numeric` in recipes (and base R, see `?.MFclass`), but logicals and dates are different and can be extracted with `has_type()`. Do you need something more?

``` r
suppressPackageStartupMessages(library(recipes))

ex <- tibble(x = 1L, y = 2.5, z = 1.5, w = TRUE, a = Sys.Date())

rec <- recipe(y ~ ., ex)
p_rec <- prep(rec, ex)

summary(rec)
#> # A tibble: 5 x 4
#>   variable type    role      source  
#>   <chr>    <chr>   <chr>     <chr>   
#> 1 x        numeric predictor original
#> 2 z        numeric predictor original
#> 3 w        logical predictor original
#> 4 a        date    predictor original
#> 5 y        numeric outcome   original

juice(p_rec, all_numeric())
#> # A tibble: 1 x 3
#>       x     z     y
#>   <int> <dbl> <dbl>
#> 1     1   1.5   2.5

juice(p_rec, has_type("logical"))
#> # A tibble: 1 x 1
#>   w    
#>   <lgl>
#> 1 TRUE

juice(p_rec, has_type("date"))
#> # A tibble: 1 x 1
#>   a         
#>   <date>    
#> 1 2019-03-22
```

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by topepo** [comment]
I think that it might make sense to separate logicals out but, TBH, I can't see a good rationale for having logical values in a data set that you intend to analyze. 

The other thing that you can do for integers is to give them an additional role (see `add_role`) so that you can select them that way too.

**Comment by alexhallam** [comment]
Thanks @DavisVaughan, `has_type` may get me what I need. 

Also, @topepo, I have a time series situations where most of my columns are 1s/0s indicating that an event happened on a given date. These columns can be things such as holidays, day of week, etc. I also have a few numeric columns that are continuous that I want to log.

In this situation I wanted to apply log only to the predictors that were not 0,1.  `step_log(all_numeric())` did not work because my Boolean integers are numeric and they got transformed to [-Inf, 0]. My first reaction was to make all my Boolean integers logicals with `mutate_each(funs(if(is.integer(.)) as.logical(.) else .))`. My plan was to do  `step_log(-all_logical())`, but there is no `all_logical()`. Then I also wished that `all_numeric()` was further divided into `all_integer()` and `all_double()` so I could have just used  `step_log(-all_integer())`. This would have worked in my case since my Boolean predictors were the only integer columns.

**Comment by topepo** [comment]
I'd suggests excluding these via `one_of()`. Here's an example:

``` r
library(tidymodels)
#> ── Attaching packages ──────────────────────────────────────────── tidymodels 0.0.2 ──
#> ✔ broom     0.5.1          ✔ purrr     0.3.2     
#> ✔ dials     0.0.2          ✔ recipes   0.1.4     
#> ✔ dplyr     0.8.0.1        ✔ rsample   0.0.4     
#> ✔ ggplot2   3.1.0          ✔ tibble    2.1.1     
#> ✔ infer     0.4.0          ✔ yardstick 0.0.2     
#> ✔ parsnip   0.0.2.9000
#> ── Conflicts ─────────────────────────────────────────────── tidymodels_conflicts() ──
#> ✖ purrr::discard() masks scales::discard()
#> ✖ dplyr::filter()  masks stats::filter()
#> ✖ dplyr::lag()     masks stats::lag()
#> ✖ recipes::step()  masks stats::step()
library(AppliedPredictiveModeling)
data(solubility)

# Find columns that are binary

binary_cols <- map_lgl(solTrainX, ~length(unique(.x)) == 2 & is.numeric(.x))
binary_cols <- names(binary_cols)[binary_cols]

rec <- 
  recipe(~ ., data = solTrainX) %>% 
  step_YeoJohnson(all_predictors(), -one_of(binary_cols)) %>% 
  prep()

# which were affected? 
tidy(rec, number = 1)
#> # A tibble: 19 x 3
#>    terms                 value id              
#>    <chr>                 <dbl> <chr>           
#>  1 MolWeight          0.000998 YeoJohnson_KY62I
#>  2 NumAtoms           0.0482   YeoJohnson_KY62I
#>  3 NumNonHAtoms       0.0507   YeoJohnson_KY62I
#>  4 NumBonds           0.113    YeoJohnson_KY62I
#>  5 NumNonHBonds       0.152    YeoJohnson_KY62I
#>  6 NumMultBonds       0.358    YeoJohnson_KY62I
#>  7 NumRotBonds       -0.0783   YeoJohnson_KY62I
#>  8 NumDblBonds       -0.577    YeoJohnson_KY62I
#>  9 NumAromaticBonds   0.133    YeoJohnson_KY62I
#> 10 NumHydrogen        0.332    YeoJohnson_KY62I
#> 11 NumCarbon          0.253    YeoJohnson_KY62I
#> 12 NumNitrogen       -1.28     YeoJohnson_KY62I
#> 13 NumOxygen         -0.171    YeoJohnson_KY62I
#> 14 NumChlorine       -3.63     YeoJohnson_KY62I
#> 15 NumHalogen        -2.53     YeoJohnson_KY62I
#> 16 NumRings          -0.00545  YeoJohnson_KY62I
#> 17 HydrophilicFactor -0.319    YeoJohnson_KY62I
#> 18 SurfaceArea1       0.355    YeoJohnson_KY62I
#> 19 SurfaceArea2       0.366    YeoJohnson_KY62I
```

Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)
