### ISSUE TITLE
Documentation of adding and updating a role

### ISSUE THREAD

**Issue by gadenbuie** [tidymodels/recipes#309]
Hi all, I had to update some older scripts today to follow the more strict role setting functions and I'm finding the documentation around `add_role()` and `update_role()` to be very confusing.

The documentation in [Manually Alter Roles](https://tidymodels.github.io/recipes/reference/roles.html) currently opens with

> `add_role()` adds a new role to an existing variable in the recipe. It does not overwrite old roles, as a single variable can have multiple roles.
>
> `update_role()` alters an existing role in the recipe.
>
> `remove_role()` eliminates a single existing role in the recipe.

Reading only these lines, I would confidently flip back to my source code and write

```r
recipe(mtcars) %>%
  add_role(wt, new_role = "predictor")
## Error: No role currently exists for column(s): 'wt'. 
## Please use `update_role()` instead.
```

Because I'd like to add a _new role to an existing variable_ (`wt`). Of course, this would throw an error because `update_role()` should be used to set the role for a column currently without roles.

I'm curious what problem is avoided by not allowing `add_role()` to set the initial role? Somewhat inline with [the discussion in this issue](https://github.com/tidymodels/recipes/issues/283#issuecomment-459059467), I expected `add_role()` to, in essence, add roles to the "stack" of roles associated with a variable, in which case it makes sense intuitively (to me at least) that adding a role to an empty stack would initiate the stack.

Regardless, I have a couple constructive suggestions regarding the documentation that I believe would make it better align with the API.

1. Introducing `update_role()` first rather than `add_role()` would make it clearer which function to start with.
1. Indicate that `update_role()` can be used to initiate the first role of a column -- currently the focus on "alters existing role" makes it seem that `update_role()` is only relevant when a variable already has a role.
1. For `add_role()`, perhaps "additional role" instead of "new role" would better link with the _add_ verb (it seems natural when [used here](https://github.com/tidymodels/recipes/issues/308#issuecomment-475697445)), and instead of "to an existing variable" I think "variables that already have a role..." would further clarify that a variable needs to have  role before `add_role()` is appropriate. I.e.
    
    > `add_role()` adds an additional role to variables that already have a role in the recipe."
1. Finally, in the Details section, I again recommend opening with `update_role()`.

    > `update_role()` should be used to replace an `old_role` with a `new_role` or when no role currently exists for a variable. `add_role()` only adds additional roles to variables that already have roles in the recipe and will throw an error when the current role is missing (i.e. `NA`).
    >
    > When using `add_role()`, if a variable is selected that already has the `new_role`, a warning is emitted and that variable is skipped so no duplicate roles are added.
    >
    > Adding or updating roles is a useful way to group certain variables...

If you're interested in the above, I'd be happy to prepare a PR if it would be helpful.

**Comment by topepo** [comment]
These changes are relatively new and we just added a [new vignette](https://tidymodels.github.io/recipes/articles/Roles.html) that may help. 

Can you take a look at that and make recommendations? For example, we already show `update_role()` before `add_role()`.

**Comment by gadenbuie** [comment]
Thanks @topepo, I think the new vignette does a great job of cleanly explaining how roles are used. One minor point, though. The later examples in the vignette use nonsense roles like `jellyfish` and `flounder`, and I suppose this reinforces the understanding that roles can be _anything_ relevant to the analysis and not just `predictor`, `outcome`, etc, but it might undersell how roles can be useful. @DavisVaughan had a very nice [example in #245](https://github.com/tidymodels/recipes/pull/245#issue-230217536) that clearly demonstrates the motivation behind multiple roles

```r
library(recipes)
recipe(Species ~ ., iris) %>%
  add_role(Sepal.Width, Petal.Length, new_role = "dontcenterme") %>%
  step_center(all_predictors(), -has_role("dontcenterme"))
```

and I think the vignette would greatly benefit from including this or a similar example.

I still think updating the documentation for `add_role()` is worthwhile because it's the most likely landing point for someone trying to debug changes to the role functions. My issue was wordy but the changes are relatively minor and might be easier to evaluate if I submit a PR.

**Comment by topepo** [comment]
Could you do a PR to add the parts that you'd like to see?

**Comment by topepo** [comment]
Thanks. Merged
