### ISSUE TITLE
Bake a recipe on only selected variables for Scoring Data (production)

### ISSUE THREAD

**Issue by mouli3c3** [tidymodels/recipes#321]
### Feature Request:

Use the `recipe` to do the pre-processing on production data (say scoring data) i.e., after finalizing a model with minimal number of variables. 
It would be ideal to be able to use the recipe only on a final set of variables, although the recipe was intended/prepped for all the variables. I do not see any such option in the current version.

Is it possible to introduce a new option (for example `optimize=TRUE` in `bake/prep` method ) to ignore and prep the data even if all variables not present during the baking? It will be handy when we start with many variables (say 200) but end up with a model using 15 variables. We do not want to create scoring data (production level) with all 200 variables.

For example, in the below scenario, I have prepared a recipe using formula method by including 5 variables. However, after modeling, I've finalized a model with only 3 variables. So considering I now have only 3 variables, when I try to bake on test data set with only these 3 variables, `bake` complains with an error. I understand, this is an intended behavior during the modeling process. However, would be helpful to ignore or be able to perform **bake** on only selected variables on a production level data after models are finalized.

This is some what similar to optimized **score code** generated by SAS which includes steps for variables that are present in the input(final) model. 

### Minimal, reproducible example:
```r
library(tidymodels)
#Training and Testing data sets creation
data(biomass)
biomass_tr <- biomass[biomass$dataset == "Training",]
biomass_te <- biomass[biomass$dataset == "Testing",]
```

```r
#Creating a simple recipe with step_center
rec <- recipe(HHV ~ carbon + hydrogen + oxygen + nitrogen + sulfur,data = biomass_tr) %>% 
  step_center(carbon,contains("gen"),-hydrogen)

#Prepping recipe using training dataset
center_obj <- prep(rec, training = biomass_tr)
center_obj
#> Data Recipe
#> 
#> Inputs:
#> 
#>       role #variables
#>    outcome          1
#>  predictor          5
#> 
#> Training data contained 456 data points and no missing data.
#> 
#> Operations:
#> 
#> Centering for carbon, oxygen, nitrogen [trained]
#A simple linear regression model using only some of the variables
mymodel <- lm(HHV~carbon + hydrogen + oxygen,data=juice(center_obj))
mymodel
#> 
#> Call:
#> lm(formula = HHV ~ carbon + hydrogen + oxygen, data = juice(center_obj))
#> 
#> Coefficients:
#> (Intercept)       carbon     hydrogen       oxygen  
#>   18.063365     0.347025     0.206073     0.004804
#Creating test data using bake method prepped recipe including only variables from final model
transformed_test_data <- bake(center_obj, select(biomass_te,-nitrogen ,-sulfur)) 
#> Can't find column `nitrogen` in `.data`.
```

**Comment by topepo** [comment]
I don't think that this is feasible since many of the results of the step calculations would involve/depend on those other variables. For example, if you did PCA, spatial sign, imputation, and others the results would be different. 

If it is a simple recipe with simple calculations you could just re-prep as long as the results would not change. 

You could also contain the variables that will be removed (if you know) in separate steps that use `skip = TRUE`.

**Comment by mouli3c3** [comment]
You're correct. I did not think about PCA, etc. Re-prepping seems to be an ideal alternative solution.
Thanks
