### ISSUE TITLE
Can `step_knnimpute` be parallelized?

### ISSUE THREAD

**Issue by johanneswaage** [tidymodels/recipes#323]
Right now, `step_knnimpute` uses only one thread, and can take a long time for datasets with a large number of features. Could `threads` be passed to the underlying distance function for any gains?
Thanks

**Comment by topepo** [comment]
The underlying function has an option for threading. I'll add a options argument so that you can pass options to `gower::gower_topn()`.

**Comment by hegormse** [comment]
Hi topepo, 
I am still having problems using multiple threads when using the updated function in your commit. 
I hope you can help me resolve this. 

When passing this: 
my_recipe <-  recipes::recipe(feature_outcome ~., data=dataset) %>%
  recipes::step_knnimpute(EMBEDDING_X10, impute_with = imp_vars(feature_A,feature_B,feature_C),
                          neighbors = 5,
                          options = list(nthread_10,eps=1e-08))
 ,
and check the options under:
my_recipe$steps[[1]]$options, I get "NULL", while

my_recipe$steps[[1]]$terms gives 

"[[1]]
<quosure>
expr: ^EMBEDDING_X10
env:  0x7f25f636f6f8

$options
<quosure>
expr: ^list(nthread_10, eps = 1e-08)
env:  0x7f25f636f6f8

From the check's in the commit, it seems to me that this is not expected. 

So when I try to use:
my_recipe %>% recipes::prep(training = dataset) %>% recipes::bake(new_data = dataset) , 
I get the error: "Not all functions are allowed in step function selectors (e.g. 'list'). See ?selections. 

Thank you in advance.

**Comment by topepo** [comment]
Done
