### ISSUE TITLE
reverting back from step_YeoJohnson  

### ISSUE THREAD

**Issue by AtharKharal** [tidymodels/recipes#327]
hi, as I understand presently recipes does not allow for recovering  Y which has been transformed using step_YeoJohnson, whereas it is required 
any idea how to do it?

**Comment by topepo** [comment]
Not right now. You can get the transformation parameter via the `tidy()` method but it wouldn't make much sense to have a recipe step to un-do it. If you are using the recipe before modeling, having such a step would never give the transformed data to the model. 

We hope to make this happen using the `workflows` package. I'll close this issue and reference this when we add that feature.
