### ISSUE TITLE
argument for retaining original in `step_dummy`

### ISSUE THREAD

**Issue by EdwinTh** [tidymodels/recipes#328]
As also noted in the Description, `step_dummy` removes the original variable. I think it would be valuable to have the option to retain it. Personally, I always keep keep my characters/factors in the modelling set to do post-model analyses. 

Happy to do a PR, please let me know how you feel about this.

**Comment by topepo** [comment]
Changes have been checked in if you want to test

**Comment by EdwinTh** [comment]
Great, does look good to me!
