### ISSUE TITLE
Profiling time spend at each step

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#332]
This is not much of an issue and more for future users having the same problem as me.

Problem: Finding out how much time is spend in each step of the recipe. Figuring out which steps are slow.

Solution: I wrote this little function

``` r

library(tidyverse)

recipe_prof <- function(expr, rate = 0.01) {
  prof_output <- tempfile()
  Rprof(prof_output, interval = rate)
  expr
  Rprof(NULL)
  
  second_scale <- function(rate) {
    function(x) {
      paste0(x * rate, "s")
    }
  }
  
  lines <- read_lines(prof_output)
  
  layer1 <- lines %>%
    str_extract("bake.step|prep.step") %>%
    replace_na("other") %>%
    str_extract("^[[:alnum:]]+")
  
  split(lines, layer1) %>%
    map_dfr(~ list(step = str_extract(.x, "step_[[:alnum:]]+")), .id = "layer") %>%
    ggplot(ggplot2::aes(x = step)) +
    geom_bar() +
    facet_wrap(~ layer) +
    coord_flip() +
    scale_y_continuous(labels = second_scale(rate)) +
    labs(y = "time")
}
```

that you can then wrap around your prep line to get the time spend baking and prepping.

```r
library(tidymodels)

big_diamods <- sample_n(diamonds, 400000, replace = TRUE)

rec <- recipe(price ~ ., data = big_diamods) %>%
  step_dummy(cut, color, clarity) %>%
  step_scale(all_numeric()) %>%
  step_center(all_numeric()) %>%
  step_pca(all_numeric())


recipe_prof(
  prepped <- prep(rec)
)
```

![](https://i.imgur.com/9iqOFYp.png)

<sup>Created on 2019-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by bennour007** [comment]
Hello, than you for this, I have the same issue.
I discovered tidymodels few days ago and loved it, but comparing to caret workflow, or base R, this meta package is VERY VERY slow. It is true however that I work with large data sets locally, but It's used to be way faster than this. bake, and prep are somewhat the core of the problem it seems. 
Can you recommend me any alternative that is tidy, and %>% friendly.? maybe I am missing.?

**Comment by topepo** [comment]
@bennour007 Based on your #396, we need a reproducible example to verify this computationally challenging approach that you have described.

**Comment by juliasilge** [comment]
Thanks for your contributions on this issue!
