### ISSUE TITLE
Error in .subset2(x, i) : no such index at level 1

### ISSUE THREAD

**Issue by mlduarte** [tidymodels/recipes#337]
Hi - I just upgraded to R 3.6 and packages and code is no longer working. .. Here is an example that gives same error message:

```
library(recipes)
library(caret)
library(forcats)
data(okc)

rec_okc <- recipe(okc) %>%
  update_role(diet, height, new_role = "predictor") %>%
  update_role(Class, new_role = "outcome") %>%
  step_mutate(diet = fct_explicit_na(diet, "missing")) %>%
  step_rm(-has_role("predictor"), -all_outcomes()) 

okc_glm1 <- train(rec_okc, 
                  data = okc, 
                  method = "glm",
                  family = "binomial",
                  trControl =  trainControl(method = "cv", 
                                            number = 3,
                                            classProbs = TRUE,
                                            summaryFunction = defaultSummary, 
                                            verboseIter = TRUE))
```

Error Message: 

> Preparing recipe
> Error in .subset2(x, i) : no such index at level 1
 

Session Info:

> > sessionInfo()
> R version 3.6.0 (2019-04-26)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows Server 2012 R2 x64 (build 9600)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
> [3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
> [5] LC_TIME=English_Australia.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] forcats_0.4.0      caret_6.0-84       ggplot2_3.1.1      lattice_0.20-38   
> [5] recipes_0.1.5.9000 dplyr_0.8.1       
> 
> loaded via a namespace (and not attached):
>  [1] tidyselect_0.2.5        slam_0.1-45             NLP_0.2-0              
>  [4] reshape2_1.4.3          purrr_0.3.2             splines_3.6.0          
>  [7] rJava_0.9-11            colorspace_1.4-1        generics_0.0.2         
> [10] stats4_3.6.0            XML_3.98-1.19           survival_2.44-1.1      
> [13] prodlim_2018.04.18      rlang_0.3.4             ModelMetrics_1.2.2     
> [16] pillar_1.4.1            glue_1.3.1              withr_2.1.2            
> [19] foreach_1.4.4           plyr_1.8.4              lava_1.6.5             
> [22] stringr_1.4.0           timeDate_3043.102       munsell_0.5.0          
> [25] gtable_0.3.0            tm.plugin.webmining_1.3 codetools_0.2-16       
> [28] tm_0.7-6                parallel_3.6.0          class_7.3-15           
> [31] Rcpp_1.0.1              scales_1.0.0            ipred_0.9-9            
> [34] stringi_1.4.3           RJSONIO_1.3-1.1         grid_3.6.0             
> [37] tools_3.6.0             bitops_1.0-6            magrittr_1.5           
> [40] RCurl_1.95-4.12         lazyeval_0.2.2          tibble_2.1.2           
> [43] tidyr_0.8.3             crayon_1.3.4            pkgconfig_2.0.2        
> [46] MASS_7.3-51.4           Matrix_1.2-17           data.table_1.12.2      
> [49] xml2_1.2.0              lubridate_1.7.4         gower_0.2.1            
> [52] iterators_1.0.10        assertthat_0.2.1        rstudioapi_0.10        
> [55] R6_2.4.0                rpart_4.1-15            nlme_3.1-139           
> [58] nnet_7.3-12             boilerpipeR_1.3         compiler_3.6.0   

Previous working version was on R 3.5.3 with caret_6.0-81    ggplot2_3.1.0   recipes_0.1.5   dplyr_0.8.0.1

**Comment by mlduarte** [comment]
The issue seems to be with the caret package.  Keeping the all packages as in session Info above.  I removed both recipes and caret and installed as follows (i.e. latest version of recipes is fine, but not caret):

install.packages("recipes")

packageurl <- "https://cran.r-project.org/src/contrib/Archive/caret/caret_6.0-81.tar.gz"
install.packages(packageurl, repos=NULL, type="source")

Recipe is now able to be fit.

**Comment by topepo** [comment]
It's a bug but you can get around it for the time being by using the formula method for the recipe.

**Comment by EmilHvitfeldt** [comment]
This is related to what will end up happening in https://github.com/tidymodels/recipes/pull/865
