### ISSUE TITLE
step_upsample on a multi-class classification.

### ISSUE THREAD

**Issue by Ronen4321** [tidymodels/recipes#339]
I trdied to train a model with a recipe that include a step_upsample,
and i am getting the following error:

> Error in { : task 1 failed - "'x' must be numeric"
> 6.stop(simpleError(msg, call = expr))
> 5.e$fun(obj, substitute(ex), parent.frame(), e$data)
> 4.foreach(iter = seq(along = resampleIndex), .combine = "c", .packages = pkgs, .export = export) %:% foreach(parm = 1L:nrow(info$loop), .combine = "c", .packages = pkgs, .export = export) %op% { ...
> 3.train_rec(rec = x, dat = data, info = trainInfo, method = models, ctrl = trControl, lev = classLevels, ...)
> 2.train.recipe(blueprintA, data = train, method = "rpart", trControl = fitControl)
> 1.train(blueprintA, data = train, method = "rpart", trControl = fitControl)

training with a recipe without step_upsample doesn't result in an error.
I was wondering if based on the error you can point me to what is potentially wrong.

**Comment by topepo** [comment]
This looks like an issues that should be in the `caret` repo. 

Also, can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.

**Comment by Ronen4321** [comment]
Hi,
here is a reprex:

```
data(okc)

okc <- okc %>% 
  filter(diet!="NA") %>% 
  mutate(diet = make.names(diet))

up_rec <- recipe( ~ ., data = okc) %>%
  update_role(diet, new_role = "outcome") %>%
  step_rm(date) %>%
  step_dummy(all_predictors(), -all_numeric(), one_hot = TRUE) %>% 
  step_upsample(segment, ratio = 1)
  

library(rpart)
set.seed(123)
cart.fit <- train(blueprint,
                  data = train,
                  method = "rpart",
                  trControl = trainControl(method = "cv",
                                           number = 5,
                                           classProbs = TRUE,
                                           summaryFunction = multiClassSummary))

I think it fails with the cross-validation iteration, since without it is not producing the error.
```

**Comment by topepo** [comment]
Please file it in the `caret` repo since it uses `caret`. The code helps but I can't reproduce it without some data.

**Comment by Ronen4321** [comment]
I did so here is the title and the number of the new issue.
caret with a recipe that include step_upsample() #1044.

Thank you.
