### ISSUE TITLE
tidyr development version warnings

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/recipes#341]
The development version of tidyr will be released soonish, and much work has been put into making things work as they did before, but with warnings to upgrade. When I run tests with dev tidyr installed, almost everything throws this warning:

```
All elements of `...` must be named.
Did you want `data = c(type, role, source)`?
```

This is likely from a call to `unnest()`

**Comment by jennybc** [comment]
I'm going to add this issue as the one tracking the revdep problems we see for recipes, which has been assigned to you @DavisVaughan 😁

https://github.com/tidyverse/tidyr/blob/master/revdep/problems.md#recipes

It's not just warnings. We see several test failures.

**Comment by DavisVaughan** [comment]
On my calendar for Monday!
