### ISSUE TITLE
enable 0 terms for projection methods

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#347]
For model tuning, we might want to turn on/off some recipe steps. One way that we could do this is to enable `num_comp = 0` (which would just return the original data as-is). 

This would affect

- [x] `step_pca`
- [x] `step_ica`
- [x] `step_nnmf`
- [x] `step_kpca`
- [x] `step_pls`
- [x] `step_isomap`

**Comment by DavisVaughan** [comment]
Why would we be turning off steps?

**Comment by alexpghayes** [comment]
Without understanding the reason for this I'm opposed

**Comment by jyuu** [comment]
Maybe by "turning off" steps, we're getting at the desire to eliminate steps that are not useful? Possible twist: provide some kind of output metrics, printed to console, suggesting the elimination of (because of the lack of) differences due to specific pre-processing steps

**Comment by alexpghayes** [comment]
@jyuu I think that's a really good point, and gets at some that recipes is really bad at. A lot of unsupervised transformations are not just plug and play, there's some modeling choices that need to be made (number of components in PCA being a prime example), a key one of which: is this transformation just trash.

Currently my impression is that `recipes` doesn't worry about this from an inference point of view and really just enables preprocessing to get resampled error estimates. So if users want good transformations, it's on them to put in the modeling work outside the `recipes` pipeline.

My preferred workflow for this is not to turn off various parts of the recipe, which I find confusing. Instead, I think it's better to build the recipes up in steps: the first recipe does centering and scaling, the second adds additional steps to the first and adds PCA, the third....

And then I think users can investigate the requests of the first `k` steps for each `k` to validate modeling decisions being encoded in the pipeline. Again this is rough, but it's sort of the difference between `recieps` being a full fledged multivariate statistics library versus a preprocessing pipeline

**Comment by topepo** [comment]
So you think that PCA might be a good idea but you're not sure.  You can tune across the number of components (that includes zero) to make that assessment. Otherwise, you'd have to do the process twice, with two different recipes, workflows, and calls to the tuning code.

@jyuu  Yes. At minimum I'd alter the `print` method for those steps saying that they were ignored. 

My main concern wasn't is this a good idea for model tuning. I was more apprehensive that, for some values of `num_comp`, the variable names would be different. This would probably only affect recipes where a specific subset of predictors were reduced (instead of `step_pca(all_predictors())`), which is probably a small percentage of use cases. Either way, steps after the reduction would be doable but there would need to be some care. 

For example: 

```r
recipe(HHV ~ ., data = biomass) %>% 
  step_pca(contains("gen"), num_comp = varying()) %>% 
  # Just as an example... catch these predictors no matter the value of `num_comp`
  step_bs(starts_with("PCA"), contains("gen"))
```

**Comment by topepo** [comment]
Here's other examples: 

1) If you wanted to empirically compare dimensionality reduction versus a correlation filter on a data set that has a lot of highly correlated predictors, you might want to use:

```r
recipe(y ~ ., data = dat) %>% 
  step_corr(all_predictors(), threshold = varying()) %>% 
  step_pca(all_predictors(), num_comp = varying()) 
```

and tune over:

```r
tribble(
  ~threshold, ~num_comp,
  0.0,         1,
  0.0,         2,
  0.0,         3,
  0.0,         4,
  0.9,         0,
  0.8,         0,
  0.7,         0
)
```

2) Is PCA better than PLS? 

```r
recipe(y ~ ., data = dat) %>% 
  step_pls(all_predictors(), threshold = varying()) %>% 
  step_pca(all_predictors(), num_comp = varying()) 
```

Enabling zero values would allow you to do one or the other...
