### ISSUE TITLE
Generalization of `step_holiday()`?

### ISSUE THREAD

**Issue by uribo** [tidymodels/recipes#350]
`step_holiday()` is provided to create holiday features, but there are some old holiday lists (But this is the task of `timeDate::listHolidays()` which depends). For example, in Japan, August 11th, 2016 was established as a new public holiday.

https://ja.wikipedia.org/wiki/%E5%B1%B1%E3%81%AE%E6%97%A5 (Sorry, Japanese page)

``` r
library(tidyverse)
library(recipes)

tibble(
  date = lubridate::ymd("2018-08-07") + seq.int(0, 6)) %>% 
  recipe(~ .) %>% 
  step_holiday(date,
               holidays = timeDate::listHolidays("JP")) %>% 
  step_rm(date) %>% 
  prep() %>% 
  juice(starts_with("date")) %>% 
  transmute(is_holidays = rowSums(select(., starts_with("date")))) %>% 
  distinct(is_holidays)
#> Warning: All elements of `...` must be named.
#> Did you want `data = c(type, role, source)`?

#> Warning: All elements of `...` must be named.
#> Did you want `data = c(type, role, source)`?

#> Warning: All elements of `...` must be named.
#> Did you want `data = c(type, role, source)`?
#> # A tibble: 1 x 1
#>   is_holidays
#>         <dbl>
#> 1           0

timeDate::listHolidays("JP") %>% 
  stringr::str_subset("Yama")
#> character(0)
```

Is there a way to make this new holiday a feature?

Also, I think it would be useful to be able to use a specific day (event day) other than the holidays included in the list as a flag.

e.g.

```r
tibble(
  date = lubridate::today() - seq.int(10, 0)) %>% 
  recipe(~ .) %>% 
  # not defined
  step_eventday(eventdays = c("2019-06-19", "2019-06-20", "2019-06-27")) %>% 
  prep() %>% 
  juice()
#> # A tibble: 11 x 2
#> date       is_event
#> <date>        <dbl>
#> 1 2019-06-18        0
#> 2 2019-06-19        1
#> 3 2019-06-20        1
#> 4 2019-06-21        0
#> 5 2019-06-22        0
#> 6 2019-06-23        0
#> 7 2019-06-24        0
#> 8 2019-06-25        0
#> 9 2019-06-26        0
#> 10 2019-06-27        1
#> 11 2019-06-28        0
```

<sup>Created on 2019-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by topepo** [comment]
You might be able to: 

 * Make a new holiday that the `timeDate` package can use. There are lots of examples in that package but I don't know if it would work with holiday objects in your global environment. 

 * Ask the `timeDate` maintainers to add it (_probably the better idea_). Rmetrics is on [r-forge](https://r-forge.r-project.org/projects/rmetrics/)

`recipes` simply uses their infrastructure so there's not anything that we can change here.

**Comment by uribo** [comment]
Thank you for your quick response.
I will consider contacting the administrator of `timeDate`.

On a side note, [`prophet`](https://github.com/facebook/prophet/tree/master/R) also has data available for holidays judgment :)

```r
glimpse(prophet::generated_holidays)
#> Observations: 70,654
#> Variables: 4
#> $ ds      <fct> 1995-01-01, 1995-02-27, 1995-02-28, 1995-03-24, 1995-04-02, 1995-04-13, 1995-04-14…
#> $ holiday <fct> Ano Nuevo [New Year's Day], Dia de Carnaval [Carnival's Day], Dia de Carnaval [Car…
#> $ country <fct> AR, AR, AR, AR, AR, AR, AR, AR, AR, AR, AR, AR, AR, AR, AR, AR, AR, AR, AR, AR, AR…
#> $ year    <int> 1995, 1995, 1995, 1995, 1995, 1995, 1995, 1995, 1995, 1995, 1995, 1995, 1995, 1995…
```
