### ISSUE TITLE
Issues with CRAN checks 

### ISSUE THREAD

**Issue by Nelson-Gon** [tidymodels/recipes#359]
I do maintain a package that depends on `caret` which in turn depends on `recipes`.  I am not sure how to best make a reproducible example because everything works fine locally but the package that I maintain [errors](https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64/manymodelr-00install.html) which has something to do with `recipes`.  

This is a summary(truncated for conciseness) of the test results:

```
Warning: S3 methods 'bake.recipe', 'bake.step_BoxCox', 'bake.step_YeoJohnson', 'bake.step_arrange', 'bake.step_bagimpute
Error in namespaceExport(ns, exports) : 
  undefined exports: add_check, add_role, add_step, all_nominal, all_numeric, a

```

I did take a look at checks for `recipes` and only found a single warning:

```
Found the following significant warnings:
  Warning: Passing an environment wrapper like a function is deprecated.

```

I have looked at the `upcoming release` tag but couldn't readily find mention of this issue. My apologies if it has already been addressed.  
 It appears that the warning is on version 0.1.5 that has probably not yet been upgraded.

**Comment by topepo** [comment]
The "Passing an environment wrapper" warning is related to new versions of `rlang` and `recipes` on CRAN. That should go away in a day or so once new binaries are build and they start testing with the current versions of everything. 

I've never seen the other error. It makes me think that something went really wrong with the file that they are loading. I think that _nothing_ is being exported from `recipes`. Can you submit yours to win-builder to see if you get the same thing?

**Comment by Nelson-Gon** [comment]
Thank you for the update regarding `rlang`. I did submit to `win-builder` and everything does work fine. I only get a warning about an already existing version(reasonably so). I'll wait and see what happens in a few days. Thanks again.
