### ISSUE TITLE
update a recipe

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#367]
For model tuning, we need an `update()` method to change parameter arguments in an existing recipe (for model tuning). 

Perhaps a tidyish function to extract the existing ones could be a basis for the input. The argument will probably need to reference the arguments by step `id`.

**Comment by DavisVaughan** [comment]
`recipes` already has:
https://github.com/tidymodels/recipes/blob/f287e4accedf7d6224ec696c3441ab881b665f85/R/update.R

And I was using it in a `unique-id` branch in dials:
https://github.com/tidymodels/dials/blob/unique-id/R/merge.R

**Comment by jonthegeek** [comment]
I don't have a suggestion for *how* to do this, but it would definitely be nice if the `update()` could "figure out" which step the parameter with that name is in. `dials::param_set` could find the `tune()` steps  in the workflow, it'd be nice if there were a really clean way to put the values back in. I'm... not sure what that would mean, but this is definitely the thing that I'm finding most confusing when implementing `tune`. The current update is forcing me to think about my recipes in a way that isn't how I think about them for any other parts of the process ("Wait, what step number is this? Let me count... and I hope I don't construct this particular recipe from a couple functions that will make it really hard to sort that out...")

If it isn't feasible to do it automatically, maybe tweak the print method(s) for recipes to show the information necessary to find the `tune()`s easily?

**Comment by topepo** [comment]
The `tidy()` method now shows the step ID and has an `id` argument: 

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

set.seed(332)
rec <- 
  recipe( ~ ., data = USArrests) %>%
  step_center(all_numeric()) %>%
  step_scale(all_numeric()) %>%
  step_pca(all_numeric(), num_comp = 3) %>% 
  prep()

tidy(rec)
#> # A tibble: 3 x 6
#>   number operation type   trained skip  id          
#>    <int> <chr>     <chr>  <lgl>   <lgl> <chr>       
#> 1      1 step      center TRUE    FALSE center_YMSZ5
#> 2      2 step      scale  TRUE    FALSE scale_dtg4z 
#> 3      3 step      pca    TRUE    FALSE pca_BEC9o

tidy(rec, id = "pca_BEC9o")
#> # A tibble: 16 x 4
#>    terms      value component id       
#>    <chr>      <dbl> <chr>     <chr>    
#>  1 Murder   -0.536  PC1       pca_BEC9o
#>  2 Assault  -0.583  PC1       pca_BEC9o
#>  3 UrbanPop -0.278  PC1       pca_BEC9o
#>  4 Rape     -0.543  PC1       pca_BEC9o
#>  5 Murder    0.418  PC2       pca_BEC9o
#>  6 Assault   0.188  PC2       pca_BEC9o
#>  7 UrbanPop -0.873  PC2       pca_BEC9o
#>  8 Rape     -0.167  PC2       pca_BEC9o
#>  9 Murder   -0.341  PC3       pca_BEC9o
#> 10 Assault  -0.268  PC3       pca_BEC9o
#> 11 UrbanPop -0.378  PC3       pca_BEC9o
#> 12 Rape      0.818  PC3       pca_BEC9o
#> 13 Murder    0.649  PC4       pca_BEC9o
#> 14 Assault  -0.743  PC4       pca_BEC9o
#> 15 UrbanPop  0.134  PC4       pca_BEC9o
#> 16 Rape      0.0890 PC4       pca_BEC9o
```

<sup>Created on 2020-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@jonthegeek I think that's what you want?

**Comment by jonthegeek** [comment]
It looks like that would allow me to easily figure out what I want, so, yes, that closes my portion of this thread! Thanks!
