### ISSUE TITLE
Feature request: check_n_cols()

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#372]
It would be nice to have a step that would alert if the number of columns stays within a bound. This way we can check that the number of columns doesn't hit zero and doesn't explode to 10000000 columns https://github.com/tidymodels/textrecipes/issues/23.

This is the same kind of problem the Check functions are trying to solve with `check_cols()` etc

Below is a toy example where we unknowingly are trying to do PCA on zero columns.

``` r
library(recipes)
data <- tibble(v1 = 1,
               v2 = 1, 
               v3 = 1,
               v4 = 1, 
               v5 = 1)

recipe(~ ., data) %>%
  step_zv(all_predictors()) %>%
  step_pca(all_predictors()) %>%
  prep()
#> All columns in a tibble must be 1d or 2d objects:
#> * Column `variable` is NULL
#> * Column `type` is NULL
```

Suggested workflow:

``` r
library(recipes)
data <- tibble(v1 = 1,
               v2 = 1, 
               v3 = 1,
               v4 = 1, 
               v5 = 1)

recipe(~ ., data) %>%
  step_zv(all_predictors()) %>%
  check_n_cols(min > 0) %>%
  step_pca(all_predictors()) %>%
  prep()
```

**Comment by EdwinTh** [comment]
> It would be nice to have a step that would alert if the number of columns stays within a bound.

Wouldn't it make more sense to alert when the number is outside the bound?


This would be a new check rather than an extension of `check_cols` I guess?  Shouldn't be hard to do.

**Comment by EmilHvitfeldt** [comment]
Going back, I don't think this is needed. I'm going to close this issue
