### ISSUE TITLE
Feature Request: Specifying the suffix for variables as well as option to keep non modified variable

### ISSUE THREAD

**Issue by DarkShadeKnigh** [tidymodels/recipes#373]
We are working on a package and need control over the suffix of each step as well as the ability to keep unmodified versions. We were wondering if this is something your team would be interested in. We are currently using it in some impute functions through 2 additional arguments: append and suffix. Suffix specifies the suffix attached to the modified variable and append is responsible for weather the source variable is kept or not.

**Comment by DarkShadeKnigh** [comment]
https://github.com/Big-Life-Lab/bllflow/blob/step-function-recoding/R/step-function-recoding.R This is the current implementation.

**Comment by topepo** [comment]
If you want to have altered copies of the original, can you do this with [`step_mutate_at()`](https://tidymodels.github.io/recipes/reference/step_mutate_at.html) in the devel version of `recipes`? Also, there is a [`step_rename_at()`](https://tidymodels.github.io/recipes/reference/step_rename_at.html) if this is about renaming the existing variables in-place?

**Comment by DarkShadeKnigh** [comment]
Does this work with passing your existing steps as the function argument? And if passed is the step properly added to the log? Also Ill detail a sample case below, in case I'm missing some arguments in your existing functions.

**Comment by DarkShadeKnigh** [comment]
For our purpose some analysts prefer to log transformations in variable names as a suffix in case it has to be later sent as a csv. In case of using step_meanimpute they have no way of specifying the suffix to indicate that the variable was meanimputed. For this case the step_rename_at() can be used after the transformation to rename the variable however for cases where multiple steps are done this becomes tedious. Also sometimes they might wish to keep an original variable for reference however step_meanimpute overwrites that variable is there a way to create a new variable with your existing meanimpute function?

**Comment by topepo** [comment]
`step_mutate()` can be used to make copies. The `dplyr` steps were added so we don't have to add `retain` and rename options to every step.  

> Does this work with passing your existing steps as the function argument?

I'm not sure of what you are asking. The `dplyr` selectors are the same as the others so, for an impute function, you could use the same selectors to get the same columns. 

> And if passed is the step properly added to the log?

Do you mean "are these transformations consistently done in `bake()` as they are during `prep()`?" then yes (unless you use the `skip` option).

**Comment by DarkShadeKnigh** [comment]
>I'm not sure of what you are asking. The dplyr selectors are the same as the others so, for an impute function, you could use the same selectors to get the same columns.
>
The step_mutate uses the fn argument to modify the data I was wondering how to pass your already existing step functions as that argument. Example from your step_mutate documentation: `step_mutate_at(contains("Length"), fn = list(log = log, sqrt = sqrt))`. Is there a way to pass your bagimpute step function as one of them? something like: 
`step_mutate_at(contains("Length"), fn = list(bagImpute = step_bagimpute,
meanImpute = step_meanimpute))` 
>The dplyr steps were added so we don't have to add retain and rename options to every step.
>
What do you mean by dplyr steps?
>>And if passed is the step properly added to the log?
>>
I mean the output printed when u print recipe:
>#> Data Recipe
#> 
#> Inputs:
#> 
#>       role #variables
#>    outcome          1
#>  predictor         13
#> 
#> Operations:
#> 
#> K-nearest neighbor imputation for all_predictors
>

**Comment by topepo** [comment]
I get it now...

* The `dplyr` steps are those that just apply a `dplyr` verb (mutate, filter, sample, rename, etc). 
 * You can't pass step specifications to the function argument. `mutate` is meant for self-contained functions (i.e. you don't have to save any estimates as a side-effect, just the result of the function) 
* When printing, selectors like `all_predictors` should be replaced by the variable names after `prep` has been run. If that's not the case, please file an issue.

**Comment by DarkShadeKnigh** [comment]
>When printing, selectors like all_predictors should be replaced by the variable names after prep has been run. If that's not the case, please file an issue.
>
Sorry i should have been more specific would using the step_mutate be part of the operations section
>#> Operations:
#>
#> K-nearest neighbor imputation for all_predictors
>

**Comment by DarkShadeKnigh** [comment]
>You can't pass step specifications to the function argument. mutate is meant for self-contained functions (i.e. you don't have to save any estimates as a side-effect, just the result of the function)
>
So there is no way to use your existing steps with the dplyr steps?

**Comment by topepo** [comment]
No.

**Comment by DarkShadeKnigh** [comment]
Okay thanks we will then continue with our modifications. Thank you for your help.

**Comment by kylegilde** [comment]
I ran into a situation where I needed to make multiple transformations of the same predictors  and specify the suffixes. This approach seems to work:

`r
> data("airquality")
> rec <- 
+   recipe(~ ., data = airquality) %>%
+   update_role(., Ozone, Wind, new_role = "helper") %>% 
+   step_mutate_at(., has_role("helper"), fn = list(normalized = ~(.))) %>%
+   step_normalize(., ends_with("_normalized")) %>% 
+   step_mutate_at(., has_role("helper"), fn = list(min_max_scaled = ~(.))) %>%
+   step_range(., ends_with("_min_max_scaled")) %>% 
+   prep(log_changes = T) 
step_mutate_at (mutate_at_a0gdo): 
 new (2): Ozone_normalized, Wind_normalized

step_normalize (normalize_WUYMd): same number of columns

step_mutate_at (mutate_at_I6osr): 
 new (2): Ozone_min_max_scaled, Wind_min_max_scaled

step_range (range_wx6r3): same number of columns

> 
> rec$term_info
# A tibble: 10 x 4
   variable             type    role      source  
   <chr>                <chr>   <chr>     <chr>   
 1 Ozone                numeric helper    original
 2 Solar.R              numeric predictor original
 3 Wind                 numeric helper    original
 4 Temp                 numeric predictor original
 5 Month                numeric predictor original
 6 Day                  numeric predictor original
 7 Ozone_normalized     numeric predictor derived 
 8 Wind_normalized      numeric predictor derived 
 9 Ozone_min_max_scaled numeric predictor derived 
10 Wind_min_max_scaled  numeric predictor derived 

`
