### ISSUE TITLE
step_integer() change the type of the outcome variable

### ISSUE THREAD

**Issue by Ronen4321** [tidymodels/recipes#384]
step_integer with all_nominal() argument, also change the type the outcome variable from factor to an integer.

Here is an example:
```
library(tidymodels)

data(okc)

print(class(okc$Class))

train <- recipe(Class ~ ., okc) %>% 
  step_integer(all_nominal()) %>% 
  prep(training = okc) %>% 
  bake(okc)

print(class(train$Class))
```

The Class outcome variable was of type factor and after applying the recipe it becomes integer.

**Comment by topepo** [comment]
`all_nominal()` selects _all_ factors or characters regardless of role. Try using `step_integer(all_nominal(), -all_outcomes())`.
