### ISSUE TITLE
Best Practices for steps in packages?

### ISSUE THREAD

**Issue by jonthegeek** [tidymodels/recipes#393]
We want to make [RBERT](github.com/jonathanbratt/RBERT) play nice with tidymodels. For example, we want to make it easy to add a recipe step to use RBERT for feature extraction.

Would it make sense/fit your expected best practices for us to export something like step_rbert_features directly from RBERT, or should that live in a separate package?

**Comment by EmilHvitfeldt** [comment]
(@topepo can overrule me) But [textrecipes](https://github.com/tidymodels/textrecipes) would welcome steps using [RBERT](https://github.com/jonathanbratt/RBERT)!

**Comment by topepo** [comment]
Some initial thoughts: 

 * If that's the only step that you think you would add, then I'd say do a PR into `textrecipes`. If not, `rbertrecipes`? 

 * Would the outputs be features of the input test or predictions based on supervised models? I would think the former but wanted to make sure. 

* Would a recipe step use pre-trained models? 

  - If so, we should kick around the interface a bit. We generally don't want to save a recipe with inputs that are pointers (to files or memory) that may not persist after the R session is done. 

  - if not, how would we store the model puts so that they could be used on new data?

**Comment by jonthegeek** [comment]
For step_rbert_features (or whatever), it would be feature extractions from the input text (using a specified checkpoint, I think).

Which leads to... yeah, it'd use pre-trained models, so we need to think a bit about how to deal with that. This is something RBERT needs to handle a bit better, so we'll probably solve it there. I can imagine it doing something like downloading the checkpoint if an env doesn't tell us where it already is on the users machine, but that's a puzzle that definitely needs to be solved (right now we make you tell us where it is and manually tell us to DL the checkpoint, but I imagine that'd make things tedious in actual use).

The main reason I hesitate to put it directly into `textrecipes` is that it might be a while before we're CRAN-ready, but I'll be using it recipe-style while we get there in order to help solve the issue.

So... maybe both? I can put it in `rbertrecipes` (or whatever) until we're ready to go, then textrecipes could just re-export that step once we're on CRAN?

Still wrapping my head around how this will work, but thanks, this points me in a good direction :)

**Comment by topepo** [comment]
If the pre-trained models will be in the CRAN package then it shouldn't be a big issue. 

There is a similar issue for `textrecipes` and `tidytext` with some text reference data sets (for stop words? I can't remember) so there may be a convention for downloading specific raw data to be used by the package. 

This would be a great addition though. I'm starting to use some text examples in workshops and `textrecipes` has been a huge enabler of that.

**Comment by jonthegeek** [comment]
Now I'm stuck focusing on the best practice for the checkpoints instead of the simple text model I'm working on for a demo, because you're completely not wrong.

Right now we have a function that allows the user to download arbitrary checkpoints, since new ones are released all the time (soon to feature a back-converter from pytorch, since that's where a lot of the work is done). But I can see how that doesn't necessarily play nice with recipes, since those could change between runs. I'm still thinking about the best way to go. A checkpoint is on the order of 300MB+, so including the what could potentially be the "wrong one" for a given user inside RBERT doesn't feel like the right way to go.

**Comment by jonthegeek** [comment]
I need to dig into the process of creating a step function to make sure I'm thinking correctly, but I'm currently leaning toward something like this:
* Put some sort of initialize_checkpoint or set_checkpoint sort of thing in RBERT that sets an option for the checkpoint that's currently "in use" for the rest of RBERT. 
* Save something like an MD5 of the weights file and the vocab file in the prepped step.
* If the working checkpoint doesn't match the checkpoint the step expects, error informatively. 

That would allow you to download a given checkpoint on a new machine or to a different location, but still bake the recipe with confidence that it's doing the same thing. 

Thoughts?

**Comment by topepo** [comment]
Did this get implemented anywhere?

**Comment by jonthegeek** [comment]
It hasn't yet. We started refactoring for TF2 then got pulled onto other projects. We're finally back at work on RBERT, and I'll be back to sort this out soon.

**Comment by juliasilge** [comment]
I'm going to close this older issue but if we need to discuss this further, let us know! 🙌 Feel free to @-mention us on your package for questions.
