### ISSUE TITLE
Issues with speed.

### ISSUE THREAD

**Issue by bennour007** [tidymodels/recipes#396]
Hello,
I am having few issues with the package.
Working on a relatively large data set 20k+ rows and 150+ columns, and trying to implement a tidy approach to my modeling, I am stilll trying to learn step by step.
What seduced me to the tidymodels is the ease of using pipe and getting things done. However I find CARET 12335533K times faster, for example when using KnnImpute for missing values, or for regression in general.

```{r}
tmp_ndf <- ndf %>%
  recipe(target~.) %>%
  step_knnimpute(all_predictors()) %>%
  prep() %>%
  bake(ndf) 
```
this chunk of code takes forever, and I never Know the reason, in caret it's few seconds long.
I need help regarding this.

**Comment by topepo** [comment]
Closed due to inactivity
