### ISSUE TITLE
integer64 support

### ISSUE THREAD

**Issue by jtbates** [tidymodels/recipes#401]
There are cases where values of class integer64 from the bit64 package are treated as double without conversion. I noticed this with [`step_normalize`](https://github.com/tidymodels/recipes/blob/1d3a89a982024c65176a0463f7b2e8bd3a0aa74a/R/normalize.R#L101), but it occurs elsewhere, for example in
 [`step_imputemean`](https://github.com/tidymodels/recipes/blob/05c7410ee2c65d0cef77c015a64bf9bb9331e274/R/meanimpute.R#L103) and [`step_center`](https://github.com/tidymodels/recipes/blob/e155bfb4a27f6c41fa393fbe26f9e23162ba2fe9/R/center.R#L107). In those cases the issue occurs because the `bit64::mean.integer64` generic returns integer64 and `vapply` expects a double.
```r
vapply(tibble(int_col=1:9, int64_col=as.integer64(1:9)), mean, c(mean = 0))
#>       int_col     int64_col 
#>  5.000000e+00 2.470328e-323 
```

If the package maintainers do not intend to support bit64, could we get a warning with these inputs?

### Minimal, reproducible example:

``` r
library(recipes)
data("credit_data")
rec_obj <- recipe(Status ~ Age, data = credit_data) %>%
  step_mutate(Age64 = bit64::as.integer64(Age)) %>%
  step_normalize(all_predictors())
trained_rec <- prep(rec_obj, training = credit_data)
train_data <- bake(trained_rec, new_data = credit_data)
train_data
#> # A tibble: 4,454 x 3
#>    Status     Age        Age64
#>    <fct>    <dbl>        <dbl>
#>  1 good   -0.645  -Inf.Nae-324
#>  2 good    1.90    Inf.Nae-324
#>  3 bad     0.812   Inf.Nae-324
#>  4 good   -1.19   -Inf.Nae-324
#>  5 good   -1.01   -Inf.Nae-324
#>  6 good   -0.0984    0.       
#>  7 good    0.630   Inf.Nae-324
#>  8 good   -0.918  -Inf.Nae-324
#>  9 good   -0.463     0.       
#> 10 bad     0.357     0.       
#> # … with 4,444 more rows
```
<sup>Created on 2019-10-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### Session Info:

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
  [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
  [1] recipes_0.1.7 dplyr_0.8.3   reprex_0.3.0 

loaded via a namespace (and not attached):
  [1] tidyselect_0.2.5   xfun_0.9           purrr_0.3.2        splines_3.6.0      lattice_0.20-38    generics_0.0.2     vctrs_0.2.0        htmltools_0.3.6   
[9] utf8_1.1.4         survival_2.44-1.1  prodlim_2018.04.18 rlang_0.4.0        pillar_1.4.2       glue_1.3.1         withr_2.1.2        bit64_0.9-8       
[17] lifecycle_0.1.0    lava_1.6.6         stringr_1.4.0      timeDate_3043.102  evaluate_0.14      knitr_1.25         callr_3.2.0        ps_1.3.0          
[25] class_7.3-15       fansi_0.4.0        Rcpp_1.0.2         clipr_0.6.0        backports_1.1.4    ipred_0.9-9        fs_1.3.1           bit_1.1-14        
[33] packrat_0.5.0      digest_0.6.21      stringi_1.4.3      processx_3.3.1     grid_3.6.0         cli_1.1.0          tools_3.6.0        magrittr_1.5      
[41] tibble_2.1.3       crayon_1.3.4       tidyr_1.0.0        whisker_0.3-2      pkgconfig_2.0.3    zeallot_0.1.0      MASS_7.3-51.4      Matrix_1.2-17     
[49] lubridate_1.7.4    gower_0.2.1        assertthat_0.2.1   rmarkdown_1.13     rstudioapi_0.10    R6_2.4.0           rpart_4.1-15       nnet_7.3-12       
[57] compiler_3.6.0  
```

**Comment by DavisVaughan** [comment]
In theory there is a `check_type()` check that is supposed to catch this.

https://github.com/tidymodels/recipes/blob/1d3a89a982024c65176a0463f7b2e8bd3a0aa74a/R/misc.R#L408

https://github.com/tidymodels/recipes/blob/1d3a89a982024c65176a0463f7b2e8bd3a0aa74a/R/normalize.R#L99

It runs in `step_normalize()`, but checks for `is.numeric()` and integer64 is a numeric.

``` r
is.numeric(bit64::integer64(1))
#> [1] TRUE
```

I suppose the easiest thing to do would be to call `as.double()` on the input after calling `check_type()`.

**Comment by DavisVaughan** [comment]
There are really two issues here, neither of which are actually recipes' fault, but we can still try and add support anyways.

1st, `vapply()` coerces `x` to a list internally with `as.list()` before iterating, which bit64 doesn't support well. This is the actual issue here.

``` r
as.list(bit64::as.integer64(1:5))
#> [[1]]
#> [1] 4.940656e-324
#> 
#> [[2]]
#> [1] 9.881313e-324
#> 
#> [[3]]
#> [1] 1.482197e-323
#> 
#> [[4]]
#> [1] 1.976263e-323
#> 
#> [[5]]
#> [1] 2.470328e-323
```

2nd, `mean()` with integer64 objects returns another integer64 object, which feels very wrong because it rounds. It really should return a double.

``` r
mean(1:6)
#> [1] 3.5

mean(bit64::as.integer64(1:6))
#> integer64
#> [1] 3
```

**Comment by topepo** [comment]
We are going to table this for a while. I'm not happy with the changes that we would have to make to every step (in `recipes` and the other packages that implement step functions). This is mostly due to how `bit64` works. 

In the meantime, similar to the example in your reprex, you should explicitly convert 64 bit integers to simple numerics using `step_mutate()` or `step_mutate_at()`. 

Once we have a better solution, we'll open another issue.

**Comment by DavisVaughan** [comment]
Leaving the existing work on this in the `int64` branch.
https://github.com/tidymodels/recipes/commits/int64
