### ISSUE TITLE
Pulling contrasts from global options

### ISSUE THREAD

**Issue by tjtnew** [tidymodels/recipes#405]
I see in #137 that you decided to remove the `contrasts` parameter from the `step_dummy` function.  This seems fine if you are only using one encoding method but does seem a little awkward if you want to mix them for different variables (e.g. have some variables with `contr.treatment` and some with `contr.sum`).  Would you be able to expand on why it was better to pull from the global options rather have `contrasts` as a parameter that the user can alter when calling `step_dummy`?  Cheers

**Comment by tjtnew** [comment]
Fair enough.  Thank you for the quick response.  Would the following be the way you envisaged setting different contrasts for different variables?

```
library(recipes)

# save defaults
original_contrasts <- getOption("contrasts")

# different contrasts
treatment_contr <- original_contrasts
treatment_contr["unordered"] <- "contr.treatment"

sum_contr <- original_contrasts
sum_contr["unordered"] <- "contr.sum"

# dummy data
df <- data.frame(value = iris$Sepal.Length,
                 species = iris$Species,
                 species2 = iris$Species)

# create temporary data frame encoding species with contr.treatment
options(contrasts = treatment_contr)
tmp <- recipe(value ~ ., df) %>%
    step_dummy(species) %>%
    prep(training = df) %>%
    juice()

# now encode species2 with contr.sum
options(contrasts = sum_contr)
res <- recipe(value ~ ., tmp) %>%
    step_dummy(species2) %>%
    prep(training = tmp) %>%
    juice()

# restore defaults
options(contrasts = original_contrasts)
```

**Comment by topepo** [comment]
That wasn't a use case that I'd ever seen so we don't have a single-recipe solution for that. That code looks fine to me.
