### ISSUE TITLE
examples and tests are specifying arguments to default values.

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#407]
Since version 0.1.4 retain have defaulted to TRUE in `prep`. However many examples and tests still specify `retain = TRUE`. Do you want me to go through the examples and remove cases like these?

https://github.com/tidymodels/recipes/blob/1d3a89a982024c65176a0463f7b2e8bd3a0aa74a/R/selections.R#L269

https://github.com/tidymodels/recipes/blob/fb44b8611b58aab038a80cb7fbb67be46132530d/vignettes/Dummies.Rmd#L47

https://github.com/tidymodels/recipes/blob/491c175d40447eed18655502a518a70bdf7713a4/tests/testthat/test_nomial_types.R#L141

**Comment by topepo** [comment]
> Do you want me to go through the examples and remove cases like these?

Yes, that would be great.

**Comment by EmilHvitfeldt** [comment]
Case with training in prep too right?

```r
rec <- recipe(Price ~ ., data = credit_tr)
impute_rec <- rec %>%
  step_bagimpute(Status, Home, Marital, Job, Income, Assets, Debt)
imp_models <- prep(impute_rec, training = credit_tr)
```

to

```r
rec <- recipe(Price ~ ., data = credit_tr)
impute_rec <- rec %>%
  step_bagimpute(Status, Home, Marital, Job, Income, Assets, Debt)
imp_models <- prep(impute_rec)
```
