### ISSUE TITLE
better print infrastructure using glue and cli

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#426]
`cli` 2.0.0 has some nice new features the would make our print methods much better.

**Comment by mattwarkentin** [comment]
Hi @topepo,

I would be interested in taking this on. I have noticed a few other print issues (e.g. `print()` methods for non `prep()`'d recipes could use some fixing) and I think it would be fairly straightforward to make both fixes at the same time. I could look over any open issues to see if other print issues need addressing at the same time.

I've used the `cli` package a fair amount and have a pretty good grasp on its functionality. I'm not sure if your "help wanted" sign was supposed to be "outward facing" or if you are looking for an existing contributor to pick this up.

**Comment by topepo** [comment]
Any help would be great; you are welcome to contribute!

The main goal for this particular issue was to consolidate/refactor the print helpers to use these packages.
