### ISSUE TITLE
Drop invariant variables

### ISSUE THREAD

**Issue by EdwinTh** [tidymodels/recipes#441]
I recently had to train many models, each for a subgroup. I built one recipe, which worked fine for all but a handful. They had a single value for on or more categoricals, which (rightly) broke `step_dummy`. It would be helpful to be able to drop invariant variables as part of the recipe. We could build a step for it, but it could also be part of `step_dummy`. I would say the former, so you can run it as a general function at the start of the recipe.

What do you think?

**Comment by EmilHvitfeldt** [comment]
Were you thinking of [step_zv()](https://tidymodels.github.io/recipes/reference/step_zv.html) and [step_nzv()](https://tidymodels.github.io/recipes/reference/step_nzv.html)?

**Comment by EdwinTh** [comment]
Ah, didn't realise it also works on categoricals, great!
