### ISSUE TITLE
Give more steps a preserve argument

### ISSUE THREAD

**Issue by EdwinTh** [tidymodels/recipes#447]
As suggest in #328, and implemented in #351, `step_dummy` has a `preserve` argument to retain the original variable. I think it would make sense to implement this argument in more, if not all, steps. For further feature creation and for post-training analysis.

**Comment by topepo** [comment]
Let's make a specific list: 

- [ ] `step_date()`
- [ ] `step_holiday()`
- [ ] `step_pca()`
- [ ] `step_ica()`
- [ ] `step_pls()`
- [ ] `step_isomap()`
- [ ] `step_kpca_rbf()`
- [ ] `step_nnmf()`
- [ ] `step_ratio()`
- [ ] `step_discretize()`
- [ ] `step_cut()`

**Comment by AndrewKostandy** [comment]
I'd like to add to Max's specific list above:

- [ ] step_center()
- [ ] step_scale()
- [ ] step_normalize()

The reason is that the above steps can be run sometimes only for the benefit of another step such as step_umap. step_umap has a retain argument but it would retain the normalized versions of the features passed to it while the original features would be lost.

Additionally, I noticed that different argument names are used to retain original features. For example, step_dummy uses the argument preserve while step_umap uses the argument retain. Perhaps it makes sense to stick to one argument name for all steps.

**Comment by juliasilge** [comment]
I've been doing work on adding the `keep_original_cols` argument to various steps in #635 and #645.

**One thing to note:** we currently do not plan to add this argument to steps that transform variables _in place_ with no name change. This includes steps like `step_normalize()` and `step_discretize()`. The reason we are not changing this for now is that there are not natural or obvious naming options like for PCA or indicator variables and choices we would make would either be a breaking change compared to the behavior now or inconsistent between `keep_original_cols = TRUE/FALSE`. We are going to give that some time and see if it such a change is really needed for users.

In the meantime, I added some new docs to show how to use our recommended workflow for how to do this now using either `step_mutate()`:

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
df <- data.frame(x = 1:10, y = 5:14)

recipe(df) %>%
  step_mutate(x_orig = x) %>%
  step_cut(x, breaks = 5) %>%
  prep() %>%
  bake(df)
#> # A tibble: 10 x 3
#>    x          y x_orig
#>    <fct>  <int>  <int>
#>  1 [1,5]      5      1
#>  2 [1,5]      6      2
#>  3 [1,5]      7      3
#>  4 [1,5]      8      4
#>  5 [1,5]      9      5
#>  6 (5,10]    10      6
#>  7 (5,10]    11      7
#>  8 (5,10]    12      8
#>  9 (5,10]    13      9
#> 10 (5,10]    14     10
```

<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Or for more complex situations, `step_mutate_at()`:

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
data(biomass, package = "modeldata")

biomass_tr <- biomass[biomass$dataset == "Training",]
biomass_te <- biomass[biomass$dataset == "Testing",]

recipe(HHV ~ carbon + hydrogen + oxygen + nitrogen + sulfur,
       data = biomass_tr) %>% 
  step_mutate_at(all_numeric_predictors(), fn = list(orig = ~.)) %>%
  step_normalize(-contains("orig"), -all_outcomes()) %>% 
  prep() %>% 
  bake(biomass_te)
#> # A tibble: 80 x 11
#>     carbon hydrogen oxygen nitrogen   sulfur   HHV carbon_orig hydrogen_orig
#>      <dbl>    <dbl>  <dbl>    <dbl>    <dbl> <dbl>       <dbl>         <dbl>
#>  1 -0.193    0.176   0.801  -0.643   0.00755  18.3        46.4          5.67
#>  2 -0.490    0.0342  0.881   1.47    0.281    17.6        43.2          5.5 
#>  3 -0.543    0.0342  0.977   1.10    0.190    17.2        42.7          5.5 
#>  4 -0.188    0.535  -0.113   0.602   0.646    18.9        46.4          6.1 
#>  5  0.0390   0.719   0.392  -0.726  -0.494    20.5        48.8          6.32
#>  6 -0.390    0.0342  0.293  -0.311  -0.0380   18.5        44.3          5.5 
#>  7 -0.904   -0.191   1.44    0.0958  0.668    15.1        38.9          5.23
#>  8 -0.601   -0.668  -0.436  -0.103  -0.0380   16.2        42.1          4.66
#>  9 -1.84    -0.885  -0.686  -0.776  10.7      11.1        29.2          4.4 
#> 10 -1.97    -1.41   -1.37    2.95    1.90     10.8        27.8          3.77
#> # … with 70 more rows, and 3 more variables: oxygen_orig <dbl>,
#> #   nitrogen_orig <dbl>, sulfur_orig <dbl>
```

<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
