### ISSUE TITLE
External links to other tidymodels packages/functions don't use other tidymodels pkgdown sites

### ISSUE THREAD

**Issue by apreshill** [tidymodels/recipes#449]
See `add_recipes` for examples:

https://tidymodels.github.io/workflows/reference/add_recipe.html#arguments

Links to:
https://rdrr.io/cran/recipes/man/recipe.html

**Comment by juliasilge** [comment]
I think we have all the steps of this finished, and we need to just rebuild the pkgdown sites (including the workflows site). I don't believe anything else needs to be change in recipes itself.

**Comment by juliasilge** [comment]
The URLs are now set correctly for recipes and workflows, and the pkgdown site for workflows is being built by GH actions. The dev version is up and working, and you can see the [correct `recipes::recipe()` link here](https://workflows.tidymodels.org/dev/reference/add_recipe.html#arguments). A release version of the site will be built at the next CRAN release.
