### ISSUE TITLE
Use of `step_nzv(eveything())` in combination with `step_intercept()`

### ISSUE THREAD

**Issue by EdwinTh** [tidymodels/recipes#453]
I routinely use `step_nzv()` if factors are used in the recipe. This had me puzzled for a few minutes.:
```r
recipe(mtcars) %>% step_intercept() %>% whole bunch of other steps %>% 
step_nzv(everything()) %>% prep() %>% bake()
```
did not have an intercept. 

This is of course because the intercept is invariant. Technically it is completely correct, but it is of course never intended. You could leave this as the responsibility of the user, but I think you should at least throw a warning if `step_nzv()` removes the intercept that was added in that very recipe. Even better imo, is not removing the intercept, even when `everything()` is used. I cannot think of scenario you want to have it removed again, after adding it in the same recipe.

**Comment by topepo** [comment]
We could check to see if there is a column called "intercept" except that 1) it might be called something else (since that is parameterized) and 2) there might be some other context where a user has a legit column called "intercept". Believe it or not, I can think of a use case for the latter.

**Comment by EmilHvitfeldt** [comment]
We could use `recipes:::detect_step(recipe, "intercept")` inside `step_nzv()` to catch if `step_zv/nzv()` comes after `step_intercept()` and emit an warning.

**Comment by topepo** [comment]
I think that we will just close this. The simple solution is to add it as the last step or to deselect it in subsequent steps. The proposed solutions raise the code complexity without a whole lot of benefit.
