### ISSUE TITLE
Why doesn't step_holiday() and step_date() remove the original variable?

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#470]
I can understand why `step_interactions()` doesn't remove the original variable but I don't see why the default for just those two steps is to keep the original variable.

**Comment by konradsemsch** [comment]
Came across the same recently. I guess the original variable should be removed as it is in the case of e.g. `step_dummy()`.

**Comment by EmilHvitfeldt** [comment]
<img width="860" alt="Screen Shot 2020-02-20 at 9 52 04 AM" src="https://user-images.githubusercontent.com/14034784/74963503-ab40c480-53c6-11ea-91a7-e86a2065f1b7.png">

And it is nicely noted that you have to explicitly remove it yourself with `step_rm()`

**Comment by konradsemsch** [comment]
I actually came to realise that this behaviour makes sense: somebody perhaps would like to apply a couple different time preprocessors to the very original 'date' variable. Therefore, it should not be removed by these steps and should be removed at the end of the recipe.

An alternative could be including a `preserve = FALSE/ TRUE` parameter as in e.g.: `step_dummy()`.

**Comment by topepo** [comment]
Admittedly, the behavior is inconsistent between steps. Currently we can (or have the option to) keep the data if 

1. There are other steps that might be used with the original column (as @konradsemsch points out)

1. Someone has put in a PR to retain them for a particular step. 

For the first, I kinda wish this were the case for `step_textfeatures()` and some others in `textrecipes` 😐

**Comment by EmilHvitfeldt** [comment]
I could get around to having a `preserve` argument in the various steps (I seem to remember thinking about doing this for steps in **textrecipes** but I don't remember why I didn't) with this behavior with defaults to keep things from breaking. 

Would it be possible over time to **lifecycle** `preserve = FALSE` to `preserve = TRUE` in `step_textfeatures()?

**Comment by mdancho84** [comment]
I'd leave it up to the user to remove any date features once they are finished with their feature engineering steps. 

Case in point - How would you run `step_date(date) %>% step_holiday(date)` if `date` gets removed? Leave it up to the user to manually remove it after they are finished creating features.

**Comment by topepo** [comment]
I think that `preserve` is a great argument name. I can add it to places where there is a good rationale for wanting to keep the originals.
