### ISSUE TITLE
Cannot install recipes 0.1.10 on a Macbook

### ISSUE THREAD

**Issue by avrenli2** [tidymodels/recipes#483]
We are trying to install and load the caret package on a Macbook, but every time we run library(caret), we receive the following message.  This seems to stem from an issue with the recipes package. We tried to reinstall and update the recipes package, but the recipes package does not load when we run library(recipes).  We would be grateful for any help,

Error: package or namespace load failed for ‘caret’ in get(method, envir = home):
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/recipes/R/recipes.rdb' is corrupt
In addition: Warning messages:
1: package ‘caret’ was built under R version 3.5.2
2: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
3: In get(method, envir = home) :
  restarting interrupted promise evaluation
4: In get(method, envir = home) : internal error -3 in R_decompress1****

**Comment by topepo** [comment]
Close all of your R sessions then start a new session and run: 

```r
install.packages("recipes", repos = "http://cran.r-project.org", type = "binary")
```

How does that go?

**Comment by avrenli2** [comment]
Dear Max
It worked and we are extremely grateful to you for your immediate response
and help.
Hope you have a wonderful day,
