### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by b-rodrigues** [tidymodels/recipes#495]
https://github.com/tidymodels/recipes/blob/23687a85de345b7cc426c2650e1264f3c721cda0/R/recipe.R#L758

This produces the following error message:

`"Use `retain = TRUE` in `prep` to be ableto extract the training set"`

The below should work:

```
 cat(paste("Use `retain = TRUE` in `prep` to be able", 
           "to extract the training set" ,sep="\n"))
```

**Comment by juliasilge** [comment]
Thanks for the report @b-rodrigues! 🙌

**Comment by b-rodrigues** [comment]
No worries! And yes adding a white space is much easier 😂
