### ISSUE TITLE
FeatureRequest:  A new step similar to step_rollimpute but with partition_by and order_by parameters.

### ISSUE THREAD

**Issue by UnclAlDeveloper** [tidymodels/recipes#496]
I'm not sure how roll impute works, but the documentation that it requires an odd numbered period around the point suggests that it applies the function over the future as well as past values.

One easy form of imputation would just be to take the last known value.  Or the average of the previous known values over a period of t.  But this would require two things, an order by variable (you have to know what is previous) and a partition by variable (you don't want to impute your first value as the last value of the previous subject, etc.).

I've already written an "impute last known value" custom step for my own work.  It doesn't use a custom function.  But I would volunteer to try to add this to the tidymodels universe.  I think a partitioned and ordered rolling impute would be quite useful.

**Comment by topepo** [comment]
We are trying to limit new steps for `recipes` and instead have them in recipes-adjacent-packages (like `embed` or `textrecipes`). Can you add to a current package or make one?

**Comment by UnclAlDeveloper** [comment]
It doesn't really seem to fit into any other package, and is probably not important enough to justify it's own package, so I guess i'll just leave it as a nice to have feature request.
