### ISSUE TITLE
Normalize vs Standardize - Naming Convention

### ISSUE THREAD

**Issue by mdancho84** [tidymodels/recipes#497]
Hi @topepo & tidymodels crew,

Fantastic R package. It's a staple for me in all my preprocessing. Also love the new website. You guys are killing it!

## Question?

Should `step_normalize()` be renamed `step_standardize()` or have an option for scaling to the range [0,1]? 

My preference is to keep 1 function, but possibly add functionality to switch to the [0,1] range for those that expect a true normalization process. 

And, please let me know if I'm splitting hairs here, because "Standardization" (centering and scaling) is my preferred method (and thus I use `step_normalize()` for much of my numeric preprocessing routines. 

## Normalize vs Standardize Terminology

You can check out this [Stack Exchange article](https://stats.stackexchange.com/questions/10289/whats-the-difference-between-normalization-and-standardization) for details but basically the terms typically mean different things. 

![image](https://user-images.githubusercontent.com/13734662/80280277-0cd82480-86d1-11ea-9d96-9ad7ab840587.png)

- ___Normalization___ scales to range [0,1] 
- ___Standardization scales___ to mean 0, standard deviation 1 (preferred for preprocessing)

**Comment by topepo** [comment]
I'm happy with the current names. There is no objective/authoritative definition. It's all just "It say that..."

`step_range()` does the `[0, 1]` transform and has the most literal name.

**Comment by mdancho84** [comment]
Gotcha! Thanks for the clarification. Keep up the great work.
