### ISSUE TITLE
Can you supply means/sds to the step_normalize/step_center/step_scale funs?

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/recipes#506]
Hi,

I am wondering if you can pass `means` or `sds` to the relevant step functions so that the centering and scaling is not estimated, but supplied. Maybe I am just doing it wrong, or perhaps this is not possible. I did look for other steps that would allow this sort of thing, but I didn't see anything that seemed appropriate. 

For example, if I wanted the centering to be `3`, rather than the arithmetic mean of `3.057`...I thought if I passed the named list with the centering value it would be used. `means` looks like an argument, but the description seems like it is only used internally when `prep`ing the recipe. Am I wrong about that?
```r
library(recipes)

rec <- recipe(Sepal.Length ~ Sepal.Width, data = iris)

mean_val <- list(Sepal.Width = 3)

rec_steps <-
  rec %>% 
  step_center(Sepal.Width, means = mean_val)

prep(rec_steps) %>% 
  tidy(number = 1)
```
Thanks for your help.

**Comment by topepo** [comment]
Sorry but no. 

The argument to the function is the placeholder for the estimated values. We discourage passing values to them for a few reasons. One is that those values would be overwritten during regular use.

**Comment by mattwarkentin** [comment]
No worries! I sorta figured I was approaching it incorrectly.

Do you see any value for sister functions for `step_normalize`, `step_center`, and `step_scale` where the user can pass their own values?

Maybe suffixed versions that fall back to estimating the mean/SD for any variables which aren't user-supplied?

Something like...
```


rec %>%
  step_center_custom(x1, x2, means = list(x1 = 10, x2 = NULL))
```
So the `prep()` will estimate means for `x2` but use the user value of `x1`. I don't like the `_custom` suffix but couldn't think of a better one at the moment.

**Comment by topepo** [comment]
TBH I'd rather not do that. I think that side-stepping the standard recipes process would lead to more problems than solutions. You can write a custon one.

**Comment by mattwarkentin** [comment]
Okay, no problem.
