### ISSUE TITLE
step_bagimpute parallel?

### ISSUE THREAD

**Issue by hiltbrd** [tidymodels/recipes#519]
Step_bagimpute appears to run some parallelization. Is there a way to control or limit the number of workers?

**Comment by topepo** [comment]
It does not do anything in parallel and we are unlikely to parallelize it. We generally suggest parallelizing high-level functions instead of the lower-level functions (like this one).

**Comment by lbenz-mdsol** [comment]
I am curious how step_bagimpute is utilizing cores. It certainly isn't using all of my cores at 100% but it seems as those all of the cores are somehow being used to a degree, and I don't see a way I can control this. Any thoughts or how this step is utilizing cores and if I can control that behavior in any way? Thanks!

![Screen Shot 2020-06-15 at 3 30 03 PM](https://user-images.githubusercontent.com/54043017/84698066-2fdac400-af1d-11ea-9728-7bc638444c08.png)

**Comment by topepo** [comment]
It calls `ipred::ipredbagg()`, which does not use any parallel processing. Neither does the [wrapper function](https://github.com/tidymodels/recipes/blob/6b891ba618e830e4b1eda0bb5213269e0c0ad785/R/bag_imp.R#L150) that iterates over variables. 

I'm not saying that something is not using those cores, but there are not entry points into parallel processing within the functions that are used.
