### ISSUE TITLE
Feature: as.data.frame

### ISSUE THREAD

**Issue by Bijaelo** [tidymodels/recipes#549]
recipes have a great potential within the R ecosystem. But as discussed in [this question](https://github.com/tidymodels/recipes/issues/543) it seems that `juice` and `prep` are not well received by some users. 

In a subset of very used functions `as.data.frame` is used in cases where `data` arguments are assumed to be `data.frame`'s. One method for letting recipes be more versatile and useful across myriad of packages (without **any** alterations from the package author!) is to simply have a `as.data.frame` method for recipes, which could call `juice(self)` to return the training dataset. 

One such scenario would be for back-compatibility with the existing `model.matrix` and similar functions, which would allow users to do some preprocessing with `recipe` but give a different way to use these outside `tidymodels` for functions that may not be implemented in this ecosystem yet.

A very simple example:
```R
library(recipes)
as.data.frame.recipe <- function(x, ...)
   juice(x)
data(iris)
rec <- recipe(iris)  %>% step_center(all_numeric()) %>% prep()
model.matrix(Species ~ ., data = rec)
```

Another useful example:
```R
library(recipes)
as.data.frame.recipe <- function(x, ...)
   juice(x)
data(mtcars)
rec <- recipe(mtcars) %>% step_center(all_numeric()) %>% prep()
library(e1071)
svm(mpg ~ cyl + hp, data = rec)
```

While this doesn't incentivize the use of tidymodels, it makes the usability much greater for the package.

**Comment by topepo** [comment]
Thanks for the suggestions. I hadn't though of that. 

However, I don't think that we'll do this. We may add another verb (`bake_training()` maybe) to reduce the confusion about how to get the data out of a recipe. Adding another, more traditional, approach will add to the confusion. 

Also, we are trying to avoid `model.matrix()` and as much as possible due to some of its limitations. Using that as the interface would probably result in some errors. 

Your code above shows that, from a base R standpoint, it is a good idea. However, it's bad to mix paradigms. I don't think it would work correctly in some cases and would cause more confusion that it would clear up.

**Comment by Bijaelo** [comment]
Hi @topepo,
Thanks for your response, and that is understandable. I agree that `model.matrix` is an outdated implementation, and this would be more useful for a quick interaction with many modelling of the existing model packages (`MASS`, `lme4`, `glmmTMB`, `e1071`  and so forth). Thus the main argument is to give 'shortcut' so to speak for packages where a `tidymodel` engine is not already implemented. 

As for `bake_[verb]` it might simply be that while one is building a `recipe` one is (pragmatically)  "preparing the food". Eg `prep(recipe)` is confusing, as one has already "prepared it". It is a bit late in the packages life-cycle but one could make `prep -> bake` and `bake -> consume` (throwing [useless] ideas around).  It might be that having two separate functions are just confusing and just having `bake` react differently whether `new_data` was provided (eg. have a function handling "skip" and only call this if `new_data` is provided). 

Regardless thanks for the response and consideration. :-)

**Comment by topepo** [comment]
We decided to use `bake(recipe, new_data = NULL)` to get the training set back (see #561). Thanks for the suggestion though.
