### ISSUE TITLE
step_normalize, step_range and step_standardize

### ISSUE THREAD

**Issue by mt-edwards** [tidymodels/recipes#551]
I think the standard terminology of standardize is to center and scale and the standard terminology of normalize is to rescale values between a range. I checked this with the first five results of searching "standardize vs normalize" on google and this seems to be correct. 

Therefore, would `step_standardize()` be a more appropriate function name for  `step_normalize()` and `step_normalize()` be a more appropriate function name for `step_range()`? Especially since `step_normalize()` could be confused for what is currently `step_range()`.

On a less important note: I am sure `step_stadardise()` and `step_normalise()` functions would be greatly appreciated from those of us from Britain, New Zealand etc. 👍

**Comment by topepo** [comment]
Sorry but we won't be changing the name of `step_normalize()` or `step_range()`. You can make your own version to use though. 

Also, I don't want to support non-US spellings. I'd like to but the number of functions and classes that would be created for recipes wis large enough to be problematic.
