### ISSUE TITLE
FR: `step_lmimpute`

### ISSUE THREAD

**Issue by ttzhou** [tidymodels/recipes#553]
Is it possible to add a step that allows us to impute a variable as the result of a `lm.predict` on a set of variables (passed via `impute_with`, say)? The nice thing about adding this in into `recipes` is that it's then super easy to run this in a CV without assessment set bleed, using the usual tidymodels API.

NB: This may be more appropriate as a `step_*` to be added to another package - but I don't know what package that would be...

**Comment by topepo** [comment]
I agree that this is a good idea. If it were small in scope (e.g. only impute numeric columns, etc), we could put it in `recipes`.

**Comment by juliasilge** [comment]
Closed in #555

**Comment by juliasilge** [comment]
Closed in #555
