### ISSUE TITLE
Bake introduces NAs to ID roles

### ISSUE THREAD

**Issue by Nilafhiosagam** [tidymodels/recipes#565]
Perhaps user error on my part but I was using tidymodels to predict soccer results and created a recipe and model and was happy with it's performance on train and test data

rec <- recipe(result ~ ., data = train) %>% 
  update_role(season_start, date, team_home, team_away, new_role = "ID" ) %>% 
  step_naomit(all_predictors()) %>% 
  prep()

I use the recipe on new data (from the forthcoming season) using bake. The result is that NAs are introduced as there are new teams that were not in the orignal train/test data (team_home, team_away). Given that both of these have the role of ID I would not have thought this would be an issue

Thanks

**Comment by juliasilge** [comment]
Thank you for reporting this! 🙌  This is the same as #287 so I am going to close it here.

**Comment by Nilafhiosagam** [comment]
Ah thanks. I somehow missed that
