### ISSUE TITLE
FR: step_neglog()

### ISSUE THREAD

**Issue by hamedbh** [tidymodels/recipes#573]
This is a feature request for a Neglog transformation step. The formula is `sign(x) * log(abs(x) + 1)`. 

This would be similar to using `step_log(signed = TRUE, offset = 1)`, but without the restriction that `signed = TRUE` means that the offset is ignored. 

This is a transformation I use with variables that include negative values and where those values in (-1, 1) need to be preserved in some form (whereas `step_log(signed = TRUE)` sets them to 0). 

I have written the code to do this, so I'd be happy to create a pull request. As per the [contributor guide](https://www.tidymodels.org/contribute/) I first wanted to check whether this feature seems reasonable to you. Of course even if you think it's a good idea I guess you might prefer allowing `signed` and `offset` together in `step_log()`, but that might be messier and/or be too disruptive to people using that function. 

More info about the transformation and its application in Whittaker, Whitehead, and Somers 2005, [The neglog transformation and quantile regression for the analysis of a large credit scoring database](https://rss.onlinelibrary.wiley.com/doi/abs/10.1111/j.1467-9876.2005.00520.x)

**Comment by topepo** [comment]
I think that this is a perfectly good fit for `step_mutate()` or `step_mutate_at()` (instead of being its own step).

**Comment by hamedbh** [comment]
Fair enough. We are now using it frequently enough at work that it was worth creating a `step_*()` function, but our needs might be a bit niche.

**Comment by juliasilge** [comment]
Thank you so much for this discussion! 🙌 We will plan for folks to use `step_mutate()` for tasks like this for now.
