### ISSUE TITLE
bake with the training data

### ISSUE THREAD

**Issue by RaminZi** [tidymodels/recipes#582]
So, I'm following the tidymodels book written by Max and Julia. In chapter 6.2, they mention to bake the training data, we can set the new_data to NULL. I'm just copying and pasting all the codes in the book and it is all good until I run 
bake(simple_ames, new_data = NULL) %>% nrow() 

It gives me this error: 
Error: Please pass a data set to `new_data`.
Run `rlang::last_error()` to see where the error occurred.

but, when I change the NULL to the ames_train, it works. Any clue what the problem might be?

Thanks.
Ramin

R 4.0.0 (Arbor day)
Rstudio 1.3.1093
windows 10

**Comment by juliasilge** [comment]
We are working on a new recipes release right now, and this is a change in the current development version. If you can install via:

```r
devtools::install_github("tidymodels/recipes")
```

you should be good to go. 👍

**Comment by juliasilge** [comment]
Let us know if you have any further problems!
