### ISSUE TITLE
`predict()` with column name that is also a function name tries to use function

### ISSUE THREAD

**Issue by mpettis** [tidymodels/recipes#583]
Using a dataframe with a column whose name is also a function name confuses the `predict()` function.  Below is an example.  It thinks the column name `ts` is the function named `ts()`.

Related is an issue where I am not getting `step_lag()` to work, even with a column name that is not a function.  See: https://stackoverflow.com/q/64338885/1022967

Possible related tickets:
https://github.com/tidymodels/tune/issues/181
https://github.com/tidymodels/tune/issues/206

``` r
library(tidymodels)
#> -- Attaching packages -------------------------------------------------------------------------------------- tidymodels 0.1.1 --
#> v broom     0.7.1      v recipes   0.1.13
#> v dials     0.0.9      v rsample   0.0.8 
#> v dplyr     1.0.2      v tibble    3.0.3 
#> v ggplot2   3.3.2      v tidyr     1.1.2 
#> v infer     0.5.3      v tune      0.1.1 
#> v modeldata 0.0.2      v workflows 0.2.1 
#> v parsnip   0.1.3      v yardstick 0.0.7 
#> v purrr     0.3.4
#> -- Conflicts ----------------------------------------------------------------------------------------- tidymodels_conflicts() --
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()
library(dplyr)

set.seed(123)

### Create autocorrelated timeseries: https://stats.stackexchange.com/a/29242/17203
work_df <-
    tibble(
        ts = stats::filter(rnorm(1000), filter=rep(1,5), circular=TRUE) %>%
            as.numeric()
    )
# plot(work_df$ts)
work_df
#> # A tibble: 1,000 x 1
#>          ts
#>       <dbl>
#>  1 -0.00375
#>  2  0.589  
#>  3  0.968  
#>  4  3.24   
#>  5  3.93   
#>  6  1.11   
#>  7  0.353  
#>  8 -0.222  
#>  9 -0.713  
#> 10 -0.814  
#> # ... with 990 more rows

## Recipe
the_rec <-
    recipe(ts ~ ., data = work_df) %>%
    step_lag(ts, lag=1:5) %>%
    step_naomit(all_predictors())

the_rec %>% prep() %>% juice()
#> # A tibble: 995 x 6
#>        ts lag_1_ts lag_2_ts lag_3_ts lag_4_ts lag_5_ts
#>     <dbl>    <dbl>    <dbl>    <dbl>    <dbl>    <dbl>
#>  1  1.11     3.93     3.24     0.968    0.589 -0.00375
#>  2  0.353    1.11     3.93     3.24     0.968  0.589  
#>  3 -0.222    0.353    1.11     3.93     3.24   0.968  
#>  4 -0.713   -0.222    0.353    1.11     3.93   3.24   
#>  5 -0.814   -0.713   -0.222    0.353    1.11   3.93   
#>  6  0.852   -0.814   -0.713   -0.222    0.353  1.11   
#>  7  1.65     0.852   -0.814   -0.713   -0.222  0.353  
#>  8  1.54     1.65     0.852   -0.814   -0.713 -0.222  
#>  9  2.10     1.54     1.65     0.852   -0.814 -0.713  
#> 10  2.24     2.10     1.54     1.65     0.852 -0.814  
#> # ... with 985 more rows

## Model
rf_mod <-
    rand_forest(
        mtry = 4,
        trees = 1000,
        min_n = 13) %>%
    set_mode("regression") %>%
    set_engine("ranger")

## Workflow
rf_workflow <-
    workflow() %>%
    add_model(rf_mod) %>%
    add_recipe(the_rec)

## fit
rf_workflow_fit <-
    rf_workflow %>%
    fit(data = work_df)

## Predict
predict(rf_workflow_fit, work_df)
#> Error: Problem with `mutate()` input `lag_1_ts`.
#> x Input must be a vector, not a function.
#> i Input `lag_1_ts` is `dplyr::lag(x = ts, n = 1L, default = NA)`.
```

<sup>Created on 2020-10-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by topepo** [comment]
Is there a reason why you are lagging the outcome? 

I suspect that is the issue. The `ts` column isn't there when predictions are made (since it is an outcome) and lexical scoping finds the next symbol (which is a function).

**Comment by mpettis** [comment]
To be clear, this bug is not harming me.  I am using something else where I am indeed lagging the outcome as a predictor.  For example, I am using random forests predict temperature trends in buildings.  The outcome is the temperature at the current moment, and I get to use lagged temperatures as predictors.  So in this case, I won't get that error (because my column names are things like 'temperature', which isn't a base function).  But I thought I'd log this in case it was unexpected behavior in name lookup.  I stumbled on this problem when trying to make a reprex, and my main question is one I posted to stackoverflow, which is in the original issue comment.

**Comment by mpettis** [comment]
One of the questions I have that the bug and this thread makes me ask: Is lagging something that should be done as part of a recipe, or should it be done on the data prior to a recipe?  On the one hand, it seems obvious that lagging is something that should be part of pre-processing.  On the other hand, lagging is also dependent on some other complex logic, such as sorting the data (which recipes provides with `step_arrange()`), but may also need missing timestep rows created and inserted.  I'm not seeing recipe functions for that last part, and I'm not sure that it would be appropriate for it to be in a recipe api function, so it may not be a deficiency.  It just makes me wonder if either recipes should be powerful enough to compute all features possible, or if there are lines to be drawn between what we should expect recipes to do, and if there are engineered features that should be computed outside of recipes.

**Comment by topepo** [comment]
I think that we've come to the conclusion that pre-lagging is the best approach. 

There was some work in `rsample` to accommodate lags by adding some extra samples in the data (so that lags could be computed). This might have been a bad idea since it could lead to information leakage.

**Comment by DavisVaughan** [comment]
See https://github.com/tidymodels/rsample/pull/168#issuecomment-663189549 for rsample comments about lagging _before_ preprocessing, and why you should do it that way
