### ISSUE TITLE
Step_mutate does not remove level with 0 frequency

### ISSUE THREAD

**Issue by RaminZi** [tidymodels/recipes#591]
I'm using the last version of recipe released recently. One of my columns has missing values, but it is not NA. It is named as "Undefined". So, I can't use step_modeimpute. What I'm doing is to use step_mutate:

step_mutate(meal = replace(meal, meal == "Undefined", "BB"))

to replace it with the mode. It works, but when I check the levels of that column, that "Undefined" level is not removed. It shows 0 but it is there. However, when I did it outside the recipe using only mutate:

mutate(meal = replace(meal, meal == "Undefined", "BB"))

It does remove that "Undefined" level. 

I'm not even sure if this is a problem but just wanted to bring it up.

Thanks.
Ramin

**Comment by topepo** [comment]
Can't tell without a reproducible example but I suspect that, using `mutate()` with a data frame is altering a character vector. In a recipe, we typically convert those to factors. `replace()` does not alter factor levels AFAICT.

**Comment by RaminZi** [comment]
Well, you are absolutely correct Max. I didn't know recipe would automatically convert characters to factors. My column was a character vector, and then after using mutate, I was changing it to a factor. That's why the "Undefined" level would go away. But, is there a way to do what I am trying to achieve inside a recipe (without having left with an empty level)?

Thanks.
Ramin

**Comment by topepo** [comment]
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(recipes)
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
library(forcats)
library(purrr)

dat <- tibble(meal = rep(c("Undefined", "happy", "kosher"), 3))

rec_1 <- recipe(~ ., data = dat)

rec_1 %>% prep() %>% juice() %>% str()
#> tibble [9 × 1] (S3: tbl_df/tbl/data.frame)
#>  $ meal: Factor w/ 3 levels "happy","kosher",..: 3 1 2 3 1 2 3 1 2
rec_1 %>% prep() %>% juice() %>% pluck("meal") %>% levels()
#> [1] "happy"     "kosher"    "Undefined"

rec_2 <- 
  rec_1 %>% 
  step_mutate(
    # meal = ifelse(meal == "Undefined", "BB", meal),
    meal = fct_recode(meal, BB = "Undefined")
  )

rec_2 %>% prep() %>% juice() %>% str()
#> tibble [9 × 1] (S3: tbl_df/tbl/data.frame)
#>  $ meal: Factor w/ 3 levels "happy","kosher",..: 3 1 2 3 1 2 3 1 2
rec_2 %>% prep() %>% juice() %>% pluck("meal") %>% levels()
#> [1] "happy"  "kosher" "BB"
```

<sup>Created on 2020-10-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
