### ISSUE TITLE
What is the exact definition of all_nominal() / has_type("nominal")?

### ISSUE THREAD

**Issue by kylegilde** [tidymodels/recipes#602]
Hi,

I don't really see in any of the docs or code where it says which types of columns that this selects from a data.frame. It seems to select all logical, factor & character columns, but I want to be sure of this.

Thank you!

**Comment by topepo** [comment]
It selects character or factor (not logical).

**Comment by juliasilge** [comment]
I did find this confusing when I first started using recipes, because I couldn't find a specific answer on this in the places I looked. Could we add something to either `selections` or `has_role()`, both in [this file](https://github.com/tidymodels/recipes/blob/master/R/selections.R)?

**Comment by kylegilde** [comment]
Thank you both!
