### ISSUE TITLE
Clarify roles in documentation

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidymodels/recipes#618]
Adding something like the following to the details section of [roles](https://github.com/tidymodels/recipes/blob/master/R/roles.R) might be helpful as currently, it's not clear what various role options are (turns out they're unlimited) and which the special ones are.

I'm happy to do a PR if this sort of addition would be welcome however I'm not sure if there are other special roles.

> `new_role` (and similarly `old_role`) can be any character string. `"predictor"` and `"outcome"` roles are used automatically when fitting a model.

**Comment by juliasilge** [comment]
Thank you! 🙌  

Want to take a look at the changes in this PR and see if you think that covers the confusion?

**Comment by mine-cetinkaya-rundel** [comment]
That's great, thank you!
