### ISSUE TITLE
Challenges using `all_nominal()` and `all_numeric()`

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/recipes#620]
We have lots of examples of folks having trouble with `all_nominal()` and `all_numeric()` when they accidentally select outcomes or other non-predictors. Mine talked about running into this during teaching, and here is [one example of many from the general user base](https://stackoverflow.com/questions/65180483/trying-to-predict-the-probability-of-a-binary-variable-being-equal-to-1-using-ti/65221996#65221996). A significant challenge is that because of how/when these steps are evaluated, the error message is often opaque.

What would be a good way to reduce this friction?

- Should `all_nominal()` and `all_numeric()` only select predictors?
- Should these be replaced by new selectors like `all_nominal_preds()` and `all_numeric_preds()`?
- Some recipe steps are more prone to this problem, like `step_dummy()`. Protections at the step level?
- Something else?

**Comment by mine-cetinkaya-rundel** [comment]
I like the idea of protections at the step level, but if this is not feasible/desirable (or even if it is), I think adding selectors like `all_nominal_preds()` and `all_numeric_preds()` and promoting these in the function docs can help. I think it's also useful to demonstrate using multiple selectors in the function docs (e.g. `step_dummy(all_nominal(), all_predictors(), -all_outcomes())`) though the need for that is lower if the combined selectors are in place.
