### ISSUE TITLE
Should keyword arguments in `step_*()` be preceded by a dot?

### ISSUE THREAD

**Issue by zenggyu** [tidymodels/recipes#639]
Since it's impossible to add/modify variables with the same names as `step_mutate()`'s keyword arguments (e.g., `id`) inside `step_mutate()`, is it more appropriate to change the arguments' names to be preceded by a dot (e.g., `.id`) so that it is less likely to collide with variable names?

For example, suppose I want to create a variable called `id` that stores the row number of each observation for the `iris` data set, this won't work:

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
library(magrittr)
data(iris)

iris %>%
  recipe() %>%
  step_mutate(id = 1:nrow(iris)) %>%
  prep() %>%
  bake(new_data = NULL) %>%
  select(id)
#> Error: Can't subset columns that don't exist.
#> x Column `id` doesn't exist.
```

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Similarly, it's also not possible to add/modify variables using names like `role`, `train`, `inputs`, `skip`.

If changing the names of the keyword arguments is not feasible, there should perhaps be a workaround.

**Comment by DavisVaughan** [comment]
It is likely too late to make this change. The idea of prefixing with a `.` to avoid issues like this came into existence after recipes had already been created. If you really need to do this, you can probably get around it by splicing the expression in, which can avoid the issue

``` r
suppressPackageStartupMessages({
  library(recipes)
  library(magrittr)
})
data(iris)

iris %>%
  recipe() %>%
  step_mutate(!!!list(id = 1:nrow(iris))) %>%
  prep() %>%
  bake(new_data = NULL) %>%
  select(id)
#> # A tibble: 150 x 1
#>       id
#>    <int>
#>  1     1
#>  2     2
#>  3     3
#>  4     4
#>  5     5
#>  6     6
#>  7     7
#>  8     8
#>  9     9
#> 10    10
#> # … with 140 more rows
```

<sup>Created on 2021-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
