### ISSUE TITLE
Difficult to create an ordinal variable from character

### ISSUE THREAD

**Issue by LePeti** [tidymodels/recipes#641]
## Feature

I think it's difficult to create an ordinal variable from a character one. Here is an example:

``` r
library(data.table)
library(recipes)
library(magrittr)

foo <- data.table(bar = c(letters[1:3], NA))

rec_1 <-
    recipe(~., data = foo) %>%
    step_unknown(bar) %>%
    step_string2factor(bar, ordered = TRUE) %>%
    step_ordinalscore(bar)

bake(prep(rec_1), foo)
#> Error: Ordinal factor variables should be selected as inputs into this step.
```

The problem here is that `step_unknown()` converts the string variable `bar` to factor, thus, `step_string2factor` doesn't apply ordering. (This issue is already [mentioned here](https://github.com/tidymodels/recipes/issues/311) but was closed unresolved.)

To me, the factor conversion that `step_unknown` does is not too intuitive and neither is `step_string2factor` skipping factors (thus ordering).

In the referenced issue it's mentioned that even if the character variable doesn't have any `NA`s and `step_unknown` is left out, one needs to use `string_as_factor = FALSE` in `prep`, otherwise the same thing happens. I don't mean to mix in too many different ideas here but think that these are related.

Maybe there is a better way of doing this but I didn't yet find it.

For the record, there are obvious workarounds (here is one) but not as elegant in my opinion:

``` r
rec_2 <-
    recipe(~., data = foo) %>%
    step_unknown(bar) %>%
    step_mutate(bar = factor(bar, levels = c("unknown", letters[1:3]), ordered = TRUE)) %>%
    step_ordinalscore(bar)

baz <- bake(prep(rec_2), foo)

baz$bar
#> [1] 2 3 4 1
```

<sup>Created on 2021-02-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by juliasilge** [comment]
I know this is very fussy, but in this case you can get what you want by switching your order of operations:

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

foo <- tibble(bar = c(letters[1:3], NA))

recipe(~ ., data = foo) %>%
  step_string2factor(bar, ordered = TRUE) %>%
  step_unknown(bar) %>%
  step_ordinalscore(bar) %>% 
  prep(strings_as_factors = FALSE) %>% 
  bake(foo) %>% 
  pull(bar)
#> [1] 1 2 3 4
```

<sup>Created on 2021-02-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

You are right that `step_unknown()` converts from a string to a factor, so the key is to make an ordered factor _before_ you assign missing categories to unknown.

We haven't talked much ([such as in this article](https://recipes.tidymodels.org/articles/Ordering.html)) about the ordering of steps when it comes to factor handling, but it was [important for `step_unknown()` as well](https://github.com/tidymodels/recipes/pull/612). (Also in that case, it turns out you wan to use `step_unknown()` _after_ the other step.)

Is there a way to make a better warning or error here?

**Comment by LePeti** [comment]
Thank you! But what if I want the _unknown_ category to be assigned to the lowest int value?

**Comment by topepo** [comment]
See `?step_ordinalscore` for the `convert` option: 

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

foo <- tibble::tibble(bar = c(letters[1:3], NA))

baz <- function(x) {
   dplyr::case_when(
      x == "unknown" ~ 0,
      TRUE ~ as.numeric(x)
   )
}

recipe(~ ., data = foo) %>%
   step_string2factor(bar, ordered = TRUE) %>%
   step_unknown(bar) %>%
   step_ordinalscore(bar, convert = baz) %>%
   prep(strings_as_factors = FALSE) %>% 
   bake(foo) %>% 
   pull(bar)
#> [1] 1 2 3 0
```

<sup>Created on 2021-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by LePeti** [comment]
Thanks @topepo, I didn't know about this option! To me, this solution is a little bit more complex than using `step_mutate` to add the ordering.

@juliasilge I think the error message is quite clear. May I ask what is the rational behind `step_unknown` converting a string to a factor? I'd say avoiding that behaviour would solve this issue, but I suspect there is good reason behind doing so.

**Comment by topepo** [comment]
> May I ask what is the rational behind `step_unknown` converting a string to a factor? I'd say avoiding that behaviour would solve this issue, but I suspect there is good reason behind doing so.

We try to steer people towards using factors instead of character columns (since they are better for modeling). Although the description in `?step_unknown` says 

> assign a missing value in a factor level to"unknown"

we could throw an error if the column is not already a factor (if that would make it less surprising).

**Comment by juliasilge** [comment]
I'm going to leave this open so we can add some more advice [in this article](https://recipes.tidymodels.org/articles/Ordering.html) on ordering of steps for factor handling.

**Comment by LePeti** [comment]
@topepo to me that seems like a good solution! (I'm hoping it wouldn't cause too much hassle for people less experienced with factors.)

Thanks @juliasilge that'd be very useful!
