### ISSUE TITLE
[Feature Request] Multiple outcomes in step_pls

### ISSUE THREAD

**Issue by BenoitLondon** [tidymodels/recipes#651]
First, I love this package, it s very smart! :D

Although I understand multiple outcomes models are not supported yet but I m wondering why step_pls cannot handle multiple outcomes?

` Error: `step_pls()` only supports univariate models.`

I basicall have another oucome that is correlated with my primary outcome and I wanted to use it through pls components from my predictors. Any possibility to remove that limitation?

**Comment by topepo** [comment]
We can do this (I believe) but we would only return the scores for the predictors (not the outcomes).

**Comment by BenoitLondon** [comment]
Yes the predictor scores would be enough I guess.
