### ISSUE TITLE
Enforce consistent PCA signs

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#653]
PCA rotations and scores are only unique up to their signs. One issue is that minor data modification might change the sign (examples in `?prcomp` actually says "signs are random"). This is sometimes hard to explain to new users. 

We can enforce a consistent sign by changing the sign of the entire eigenvector based on the sign of the first value of the eigenvector. In other words, 

```r
if (eigenvector[1] < 0) {
  eigenvector <- -eigenvector
}
```

The is done column-wise to the rotation matrix. 

This would only change the sign of the PCA scores for recipes that were prepped under this change (i.e., it is backward compatible).

**Comment by topepo** [comment]
Davis found [this bit as a precedent from Matlab](https://www.mathworks.com/help/stats/pca.html): 

> The `pca` function imposes a sign convention, forcing the element with the largest magnitude in each column of `coefs` to be positive. Changing the sign of a coefficient vector does not change its meaning.

**Comment by topepo** [comment]
Here is a comparison of three strategies: 

 * don't do anything (labeled as version 0.1.15)
 * change the sign based on the first value in the eigenvector (0.1.15.9000)
 * change the sign based on the sign of the largest absolute value in the eigenvector (0.15.9001)

It looks like we can ensure consistent signs in the loadings but not the scores. This makes some sense since the scores are a function of all of the eigenvectors at once. 

Here are the [simulation](https://gist.github.com/topepo/5420abecd4f5795b103669a7a29522e7) results that measure the percentage of the signs and loadings (out of 50 loadings) that change when the number of rows are perturbed: 

![image](https://user-images.githubusercontent.com/5731043/112515700-e1d8d380-8d6c-11eb-8368-741380af0e0a.png)

Neither of the strategies affect the sign ambiguity of the PCA scores. I'm interested to know what @bwlewis thinks about this.

**Comment by alexpghayes** [comment]
Sorry to repeat some of what is the slack, but:

- Flipping signs will not solve identification issues when the data matrix has repeated singular values, or singular values that are effectively equivalent numerically
- The ordering of singular values is not stable across data resampling
- In general PCA is not identified for spherical Gaussian data

These issues are not theoretical in the sense that they very much do come up in practice. To enforce identification when it is possible I would use something like a Procrustes or varimax rotation. If the primary issue is teaching I would create a new step "step_pca_identified()` that does PCA followed by a choice of Procrustes/Varimax, defaulting to Procrustes. This would be a nice thing to have in any case.

Alternatively you might just want to go all in on a step for the traditional factor analytic rotations, and then alias one of them to `step_pca_identified()`.
