### ISSUE TITLE
Keep original labels in `step_discretize`

### ISSUE THREAD

**Issue by renanxcortes** [tidymodels/recipes#674]
Hi there!

I'd like to ask for a feature that would keep the original labels generated by the internal `cut` function in discretize, instead of "bin1", bin2", etc. Perhaps adding an argument `keep_cut_labels = TRUE`, for example.

Minimal Reproducible Example:

Current Behaviour:

```
library(modeldata)
data(biomass)

biomass_tr <- biomass[biomass$dataset == "Training",]
biomass_te <- biomass[biomass$dataset == "Testing",]

rec <- recipe(HHV ~ carbon,
              data = biomass_tr) %>% 
  step_discretize(carbon)

rec <- prep(rec, biomass_tr)
binned_te <- bake(rec, biomass_te)
table(binned_te$carbon)
```

![image](https://user-images.githubusercontent.com/22593188/112722861-8b919f00-8eea-11eb-8283-f5f167622dec.png)

Expected behaviour:

```
breaks <- quantile(biomass_tr$carbon, probs = seq(0, 1, length = 4 + 1))
table(cut(biomass_te$carbon, breaks = breaks))
```

![image](https://user-images.githubusercontent.com/22593188/112723000-330ed180-8eeb-11eb-9ed1-dd4405bc33e6.png)

**Comment by juliasilge** [comment]
You can get those values out using the `tidy()` method for a recipe:

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
data(biomass, package = "modeldata")

biomass_tr <- biomass[biomass$dataset == "Training",]
biomass_te <- biomass[biomass$dataset == "Testing",]

rec <- recipe(HHV ~ carbon,
              data = biomass_tr) %>% 
  step_discretize(carbon)

rec <- prep(rec, biomass_tr)
binned_te <- bake(rec, biomass_te)
table(binned_te$carbon)
#> 
#> bin_missing        bin1        bin2        bin3        bin4 
#>           0          22          17          25          16

tidy(rec, 1)
#> # A tibble: 5 x 3
#>   terms   value id              
#>   <chr>   <dbl> <chr>           
#> 1 carbon -Inf   discretize_gclTQ
#> 2 carbon   44.7 discretize_gclTQ
#> 3 carbon   47.1 discretize_gclTQ
#> 4 carbon   49.7 discretize_gclTQ
#> 5 carbon  Inf   discretize_gclTQ
```

<sup>Created on 2021-03-29 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

You can read more about [tidying a recipe here](https://www.tmwr.org/recipes.html#tidy-a-recipe). Can you say more about your use case for wanting factor levels like that in your output?

**Comment by renanxcortes** [comment]
Hi, Julia, thanks for the reply! I didn't know that you can tidy the recipe and get these values!

But to be more clear in my use case, it would be awesome if, after you bake a recipe with new data, you could keep the label of the "step_discretize" steps instead of "bin01", "bin02", "bin03", etc., with the labels being similar of the ones genrated by the "cut" function.

This would facilitate the EDA exploration/understanding of the data after baking.

Is there a workaround for this?

Minimal reprex:

```
library(recipes)
data(biomass, package = "modeldata")

biomass_tr <- biomass[biomass$dataset == "Training",]
biomass_te <- biomass[biomass$dataset == "Testing",]

rec <- recipe(HHV ~ .,
              data = biomass_tr) %>% 
  step_discretize(all_numeric(), 
                  num_breaks = 10,
                  options = list(keep_na = T, na.rm = T)) %>% 
  step_mutate_at(all_numeric(), fn = as.factor) %>% 
  step_other(all_predictors()) %>% 
  step_unknown(all_predictors())

rec <- prep(rec, biomass_tr)
binned_te <- bake(rec, biomass_te) # Perhaps add here keep_original_label = T
head(binned_te)
```

Tibble generated:

![image](https://user-images.githubusercontent.com/22593188/112875275-5e83ee80-909a-11eb-851a-5a5bc7288eff.png)

**Comment by renanxcortes** [comment]
Also related with https://github.com/tidymodels/recipes/issues/157. If `step_cut` could allow the user the number of bins instead of fixed values for cutting, I think this current issue would be solved.

**Comment by renanxcortes** [comment]
I realize that the behaviou of `step_discretize_xgb` of the `embed` package (https://github.com/tidymodels/embed) return the desired labels of this issue.

Minimal reprex:

```
library(modeldata)
library(xgboost)
library(recipes)
data(biomass, package = "modeldata")

biomass_tr <- biomass[biomass$dataset == "Training",]
biomass_te <- biomass[biomass$dataset == "Testing",]

rec <- recipe(HHV ~ .,
              data = biomass_tr) %>% 
  step_discretize_xgb(all_numeric(), 
                      outcome = "HHV") %>% 
  step_mutate_at(all_numeric(), fn = as.factor) %>% 
  step_other(all_predictors()) %>% 
  step_unknown(all_predictors())

rec <- prep(rec, biomass_tr)
binned_te <- bake(rec, biomass_te)
head(binned_te)
```

Which returns:

![image](https://user-images.githubusercontent.com/22593188/113493211-cfb90c80-94b3-11eb-94a2-70033b20f051.png)


The downside of this, is that it does not necessarily return bins with uniform frequencies.

**Comment by renanxcortes** [comment]
Hello, folks, is there some ongoing effort of this improvement? Cheers!
