### ISSUE TITLE
Loading the required packages for `step_nnmf()` makes `fit()` misbehave

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/recipes#681]
I was working on tidymodels/extratests#23 to move the tests for `step_nnmf()` out of recipes here (they are super long) when I noticed [some pretty strange errrors](https://github.com/tidymodels/extratests/runs/2272764312).

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
data(biomass)

rec <- recipe(HHV ~ ., data = biomass) %>%
  update_role(sample, new_role = "id var") %>%
  update_role(dataset, new_role = "split variable") %>%
  step_nnmf(all_numeric_predictors(), num_comp = 2, seed = 473, num_run = 2) %>%
  prep(training = biomass)

linear_reg() %>% fit(mpg ~ ., data = mtcars)
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'fit' for signature '"linear_reg"'
```

<sup>Created on 2021-04-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

This error is happening because for some reasons `NMF::fit` is being called instead of `parsnip::fit`.

The required packages for this recipes step are loaded via `require()` within `prep()`, and once NMF is loaded, it seems to be causing some havoc:

https://github.com/tidymodels/recipes/blob/8152d8ec2419523f92b8217f09b99c70ec0744fe/R/nnmf.R#L150-L154

I am guessing from this that nobody has ever tried using this recipe step in a modeling context?

**Comment by DavisVaughan** [comment]
Is it really required to fully load the NMF package? That feels like a big hammer, but I've got to imagine this was in there for a good reason.

If all else fails we could try something like `require("NMF", exclude = "fit")`

**Comment by juliasilge** [comment]
I think it *is* really required to load it, unfortunately, to get the code to run:

``` r
library(dimRed)
#> Loading required package: DRR
#> Loading required package: kernlab
#> Loading required package: CVST
#> Loading required package: Matrix
#> 
#> Attaching package: 'dimRed'
#> The following object is masked from 'package:stats':
#> 
#>     embed
#> The following object is masked from 'package:base':
#> 
#>     as.data.frame
dat <- loadDataSet("Iris")
factorization <- embed(dat, "NNMF", seed = 2432, nrun = 3)
#> Error in path.package(pkg): none of the packages are loaded
#> Timing stopped at: 0.001 0 0.002

## now load NMF
library(NMF)
#> Loading required package: pkgmaker
#> Loading required package: registry
#> Loading required package: rngtools
#> Loading required package: cluster
#> NMF - BioConductor layer [OK] | Shared memory capabilities [NO: bigmemory] | Cores 7/8
#>   To enable shared memory capabilities, try: install.extras('
#> NMF
#> ')
factorization <- embed(dat, "NNMF", seed = 2432, nrun = 3)
class(factorization)
#> [1] "dimRedResult"
#> attr(,"package")
#> [1] "dimRed"
```

<sup>Created on 2021-04-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I am going to try changing how recipes loads these and see if that fixes this.

**Comment by DavisVaughan** [comment]
Looks like it is NMF that is the actual issue, dimRed seems to be doing all the right things. Check this out, you have to fully attach NMF to run this, you can't use `NMF::`

``` r
x <- NMF::rmatrix(20,10)
res <- NMF::nmf(x, 2, nrun = 3)
#> Error in path.package(pkg): none of the packages are loaded
#> Timing stopped at: 0.002 0 0.002

library(NMF)
x <- rmatrix(20,10)
res <- nmf(x, 2, nrun = 3)
res
#> <Object of class: NMFfitX1 >
#>   Method: brunet 
#>   Runs:  3 
#>   RNG:
#>    10407L, -828850796L, -276540539L, -658922878L, -1670792165L, 1532231840L, 1726783521L 
#>   Total timing:
#>    user  system elapsed 
#>   3.298   0.368   2.395
```

The error seems to be because `NMF:::setupLibPaths()` tries to call the base R function `path.package("NMF")` to get the path to itself, but `path.package()` only finds fully _attached_ packages (i.e. `library()` was called), not _loaded_ packages (i.e. `NMF::` was used).

There is probably a better way for NMF to find the path to itself. Possibly `find.package("NMF")` would work? It seems to find the path to the package even if it isn't loaded or attached.

**Comment by DavisVaughan** [comment]
See also https://github.com/renozao/NMF/issues/114

It seems the mlr folks have hit this too. They found that this issue only comes up when NMF tries to run in parallel, but we probably don't want it to right? If we are tuning in parallel and this runs in parallel, that could be problematic. They just turned it off, we could consider doing the same thing, then we could probably remove the `require()` bit https://github.com/mlr-org/mlr3pipelines/pull/407/commits/fd04b8e789097b0a8b31bf385c7125ed88ae50dd#diff-f90ad15bcbda9161d3d322ace92985b1e70a0db7374abe821d998c0266c07918R93-R94

**Comment by juliasilge** [comment]
I think that would work if we were using NMF directly but I don't know that we can pass that through dimRed to NMF.

``` r
# works fine
x <- NMF::rmatrix(20,10)
res <- NMF::nmf(x, 2, nrun = 3, 
                .options = list(parallel = FALSE, parallel.required = FALSE))

# still not working
library(dimRed)
#> Loading required package: DRR
#> Loading required package: kernlab
#> 
#> Attaching package: 'kernlab'
#> The following object is masked from 'package:BiocGenerics':
#> 
#>     type
#> Loading required package: CVST
#> Loading required package: Matrix
#> 
#> Attaching package: 'dimRed'
#> The following object is masked from 'package:BiocGenerics':
#> 
#>     as.data.frame
#> The following object is masked from 'package:stats':
#> 
#>     embed
#> The following object is masked from 'package:base':
#> 
#>     as.data.frame
dat <- loadDataSet("Iris")
factorization <- embed(dat, "NNMF", seed = 2432, nrun = 3, 
                       .options = list(parallel = FALSE, parallel.required = FALSE))
#> Warning in matchPars(methodObject, list(...)): Parameter matching: .options is
#> not a standard parameter, ignoring.
#> Error in path.package(pkg): none of the packages are loaded
#> Timing stopped at: 0.002 0 0.001
```

<sup>Created on 2021-04-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I'm not sure _why_ we're using dimRed here, though.

**Comment by juliasilge** [comment]
I figured it out! 🙌 

``` r
## works fine
x <- NMF::rmatrix(20,10)
res <- NMF::nmf(x, rank = 2, seed = 2432, nrun = 3, 
                .options = list(parallel = FALSE, parallel.required = FALSE))

res
#> <Object of class: NMFfitX1 >
#>   Method: brunet 
#>   Runs:  3 
#>   RNG:
#>    10407L, 1876290228L, 1441535525L, -514679646L, 1035839419L, -1172385856L, 1794710721L 
#>   Total timing:
#>    user  system elapsed 
#>   1.411   0.008   1.425


## how to pass to dimRed
factorization <- dimRed::embed(x, "NNMF", seed = 2432, nrun = 3, 
                       options = list(.options = list(parallel = FALSE, parallel.required = FALSE)))

factorization@other.data$w
#>             NNMF1      NNMF2
#>  [1,] 0.679040580 0.33483081
#>  [2,] 0.006579455 1.16730672
#>  [3,] 0.487346402 0.49065375
#>  [4,] 0.370923158 0.32501135
#>  [5,] 1.071137637 0.09591381
#>  [6,] 0.632773970 0.49276241
#>  [7,] 0.843906213 0.05403276
#>  [8,] 0.539627194 0.46336187
#>  [9,] 0.576656852 0.43258154
#> [10,] 0.440890076 0.48271001
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

So I think we should remove the bits that fully load these packages and pass in these `.options`.

🤔 Should we add an argument to this recipe step to let users turn the parallel processing on/off? With a default to "off", to let people use `fit()` easily and parallel over tuning, but offering the "on" option for people who want to use the recipe on its own? Or do we think that is not worth the hassle at the level of use this sees?

**Comment by DavisVaughan** [comment]
Very cool!

I would probably just turn it off unconditionally until someone really needs it
