### ISSUE TITLE
broken themis revdep

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#684]
We made some changes in tidymodels/recipes@a98d3ff09c that results in a reverse dependency breakage for `themis`. 

`test_tidy()` fails for up- and down-sampling due to the names being missing:

For GitHub version: 

```
Browse[2]> waldo::compare(trained, tidy(rec_p, number = 1))
`names(old$terms)` is absent
`names(new$terms)` is a character vector ('class')
```

For CRAN version:

```
Browse[2]> str(tidy(rec_p, number = 1)$terms)
 chr "class"
Browse[2]> str(trained$terms)
 chr "class"
```

**Comment by hfrick** [comment]
The names are coming from  `eval_select_recipes()` and the idea was to make it consistent with `tidyselect::eval_select()` (#654).

**Comment by hfrick** [comment]
I'm closing this issue as Max will PR into {themis}.
