### ISSUE TITLE
step for dummy variables across multiple columns

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#716]
In cases where a row of a data set can have multiple categories spread across columns, a step to find the unique set of categories, then create dummy columns for each. Each row can have multiple 1's in the new dummy variables.

**Comment by EmilHvitfeldt** [comment]
I can take this one! `step_multi_dummy()`?

`NA` should be counted as none right?

**Comment by topepo** [comment]
I think that `step_dummy_multi_label()` (for tab-complete) would be a good idea. 

> `NA` should be counted as none right?

Correct. 

I'm not sure if there is an easy way to define the prefix for the new indicator variables (from the data). 

Just so we are clear, imagine columns for language spoken. There data might look like:

```
lang_1     lang_2     lang_3
English    Italian    NA
Spanish    NA         French
Armenian   English    French
NA         NA         NA
```

We would end up with

```
Armenian English French Italian Spanish
       0       1      0       1       0
       0       0      1       0       1
       1       1      1       0       0
       0       0      0       0       0
```

**Comment by EmilHvitfeldt** [comment]
> I think that step_dummy_multi_label() (for tab-complete) would be a good idea.

Perfect. 

I think a good default for the prefix would be based on the first column selected.

Should the step have a way to deal with a high number of labels? I was thinking of a `threshold` argument like `step_other()` could be useful. Defaulting to 0. You could always `step_other()` each individual column, but It would be nice to do it globally as well.

**Comment by topepo** [comment]
I think that adding a `threshold` argument for an other category would be a great idea.
