### ISSUE TITLE
Error when negation selectors are used in step_select()

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#729]
If you use a negated selection in `step_select()` then the remaining variables will be selected, including the response variable that could be missing later. Don't know if it should be fixed, but this is a case where the user should have used `step_rm()` instead. Maybe a note in the documentation will be enough.

``` r
library(recipes)
library(rsample)

set.seed(1234)
mtcars_split <- initial_split(mtcars)

mtcars_train <- training(mtcars_split)
mtcars_test <- testing(mtcars_split)
mtcars_test$mpg <- NULL

recipe(mpg ~ ., data = mtcars_train) %>%
  step_select(-c(vs, hp)) %>%
  prep() %>%
  bake(new_data = mtcars_test)
#> Error: Can't subset columns that don't exist.
#> x Column `mpg` doesn't exist.
```

<sup>Created on 2021-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by kevin-m-kent** [comment]
Just ran into the same issue. Thanks for raising @EmilHvitfeldt . I almost feel that step_select with negation should throw an error, since as you mentioned there is step_rm, which will accomplish what the user intends (in your example). Never thought of the possibility that it would be selecting the predictor.

**Comment by juliasilge** [comment]
This is definitely as designed, and we don't want to change the behavior of how `eval_select_recipes()` works. This applies to more than just `step_select()` so I added a bit to the documentation for [selections](https://recipes.tidymodels.org/reference/selections.html) to emphasize that something like `-Murder` ignores role information.
