### ISSUE TITLE
An alternative to `tidy` for inspecting recipe with intuitive name

### ISSUE THREAD

**Issue by atusy** [tidymodels/recipes#733]
Currently we need `tidy` function to to inspect recipe steps.
However, I think the name is not intuitive for several reasons

- The name does not contain `step`
    - This also make IDE to suggest the proper function when user guess the function contains `step` as its name.
- Too many `tidy` methods in the help

I'd suggest something like below.
I also add `.tidy` argument so that user can get raw result from the step when `.tidy = FALSE`.

```r
inspect_step <- function(x, number = NA, id = NA, ..., .tidy = TRUE) {
  if (.tidy) {
    return(tidy(x, number, id, ...)
  }
  if (!is.na(number)) {
    return(x$steps[[number]])
  }
  x$steps[[id]]
}
```

**Comment by topepo** [comment]
I don't think that we'll make this change. Although `tidy` has a lot of methods, we've documented the usage of that verb on a recipe object. I don't think that adding another function is the solution. If there is a place that you think that we need to document more, please let us know and we'll add more information.

**Comment by atusy** [comment]
Thanks for your answer, and I understand you.

As I mentioned above, there are too many tidy methods in this package, and that is what I think the root cause of difficulty to find the topic.
I tend to first refer help rather than official site.

Maybe it is nice to mention `tidy` in addition to `prep` and `bake` by `?recipe`.
I read through `?recipe` prior to lookup the list of topics.
