### ISSUE TITLE
Please expose eval_select_recipes

### ISSUE THREAD

**Issue by christiantillich** [tidymodels/recipes#739]
In situations when I’m designing a custom recipe step, exposing eval_select_recipes would help me avoid having to use the `:::` operator to fetch it. As far as I’m aware, users designing custom steps is supported, and this function seems critical to custom steps being able to select just some subset of the input data.

**Comment by DavisVaughan** [comment]
We changed over to `eval_select_recipes()` somewhat recently, so we wanted to be sure it was correct before exposing it for broader usage. I think we are probably at the point where we can do this though.

**Comment by juliasilge** [comment]
Related to tidymodels/tidymodels.org#210
