### ISSUE TITLE
step_dummy renames dummy variable

### ISSUE THREAD

**Issue by PathosEthosLogos** [tidymodels/recipes#748]
Below shows that I created a variable `dummyy` but with `step_dummy(all_nominal())`, it renames the variable to `dummyy_X1`. Although not shown below, this can create problems when original data and preprocessed data (through recipes) do not match on column names, especially when it's multiple dummy variables.

My guess is because `step_dummy()` creates multiple dummy variables when it is a multi level factor variable. However, it should not do anything in this case except convert it to numeric (though that could also be a concern, but I wouldn't know for all the modelling packages out there).

``` r
#rm(list=ls())
library(tidyverse)
library(rsample)
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
library(stacks)
library(baguette)
theme_set(theme_classic())

set.seed(123)

# Generate some data that increases over time
df <- data.frame(yearr = sample(2015:2021, 1000, replace = TRUE),
                 monthh = sample(1:12, 1000, replace = TRUE),
                 dayy = sample(1:29, 1000, replace = TRUE)) |>
  mutate(datee = ymd(paste(yearr, monthh, dayy)),
         weekk = week(datee),
         yy  = sample(10000:20000, 1000, replace = TRUE) + (yearr^2) + (weekk^5),
         dummyy = as.factor(round(sample(0:1, 1000, replace = TRUE)))) |>
  filter(!is.na(datee)) |>
  arrange(-desc(datee))
#> Warning: 1 failed to parse.

folds = df |>
  sliding_period(lookback = Inf, # if Inf, then it's chain
                 period = 'week',
                 index = datee,
                 assess_stop = 1L, # include how many 'periods' in the future for training
                 every = 8L, # group how many 'periods' together
                 step = 2L, # how many 'periods' to move the window
                 skip = 8L) # skip how many first 'periods' for the model for assessment

#analysis(folds$splits[[1]])

###

rec_df = df |>
  recipe(yy ~ .)

rec_generic = rec_df |> # Recipe
  step_dummy(all_nominal()) |> prep() |> bake(new_data = NULL)

names(rec_generic)
#> [1] "yearr"     "monthh"    "dayy"      "datee"     "weekk"     "yy"       
#> [7] "dummyy_X1"
```

<sup>Created on 2021-07-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by juliasilge** [comment]
This is in fact what `step_dummy()` is designed to do, [like you can see in the documentation](https://recipes.tidymodels.org/reference/step_dummy.html).

> `step_dummy()` creates a *specification* of a recipe step that will convert nominal data (e.g. character or factors) into one or more numeric binary model terms for the levels of the original data.

It is designed for use cases like the following:

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
data(Sacramento, package = "modeldata")

rec <- recipe(price ~ type + beds + sqft, data = Sacramento) %>%
   step_dummy(all_nominal_predictors())

rec %>% prep() %>% bake(new_data = NULL)
#> # A tibble: 932 x 5
#>     beds  sqft price type_Multi_Family type_Residential
#>    <int> <int> <int>             <dbl>            <dbl>
#>  1     2   836 59222                 0                1
#>  2     3  1167 68212                 0                1
#>  3     2   796 68880                 0                1
#>  4     2   852 69307                 0                1
#>  5     2   797 81900                 0                1
#>  6     3  1122 89921                 0                0
#>  7     3  1104 90895                 0                1
#>  8     3  1177 91002                 0                1
#>  9     2   941 94905                 0                0
#> 10     3  1146 98937                 0                1
#> # … with 922 more rows
```

<sup>Created on 2021-07-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Notice that the output is two numeric binary model terms, ready for models that require only numeric input.

If you [read through the documentation on selectors](https://recipes.tidymodels.org/dev/reference/selections.html), you can check out how we recommend using dplyr-like selectors to choose, for example, `starts_with("type")`.

It seems like the use case you've shown here might not be the best fit for `step_dummy()`. You might prefer `step_mutate_at()`:

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union

set.seed(123)

# Generate some data that increases over time
df <- data.frame(yearr = sample(2015:2021, 1000, replace = TRUE),
                 monthh = sample(1:12, 1000, replace = TRUE),
                 dayy = sample(1:29, 1000, replace = TRUE)) |>
   mutate(datee = ymd(paste(yearr, monthh, dayy)),
          weekk = week(datee),
          yy  = sample(10000:20000, 1000, replace = TRUE) + (yearr^2) + (weekk^5),
          dummyy = as.factor(round(sample(0:1, 1000, replace = TRUE)))) |>
   filter(!is.na(datee)) |>
   arrange(-desc(datee))
#> Warning: 1 failed to parse.


rec_df = df |>
   recipe(yy ~ .) |>
   step_mutate_at(all_nominal_predictors(), fn = ~as.integer(.) - 1) 

rec_df |> prep() |> bake(new_data = NULL)
#> # A tibble: 999 x 7
#>    yearr monthh  dayy datee      weekk dummyy      yy
#>    <int>  <int> <int> <date>     <dbl>  <dbl>   <dbl>
#>  1  2015      1     1 2015-01-01     1      1 4072966
#>  2  2015      1     5 2015-01-05     1      0 4077715
#>  3  2015      1     8 2015-01-08     2      0 4078440
#>  4  2015      1     9 2015-01-09     2      1 4078469
#>  5  2015      1     9 2015-01-09     2      0 4074786
#>  6  2015      1     9 2015-01-09     2      1 4070957
#>  7  2015      1    11 2015-01-11     2      1 4080111
#>  8  2015      1    14 2015-01-14     2      0 4071471
#>  9  2015      1    15 2015-01-15     3      1 4070485
#> 10  2015      1    20 2015-01-20     3      1 4073482
#> # … with 989 more rows
```

<sup>Created on 2021-07-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by PathosEthosLogos** [comment]
I see, thank you.

Hmm looks like `dummyy` becomes a double though. Converting isn't a problem, but it ought to keep the factor, no? My guess is some of the models from `parsnip_addin()` could interpret that differently. Is this a potential problem?

The part about renaming is indeed mentioned in the documentation though renaming isn't necessary for binary variable. Then maybe this would be more of a feature request ticket to leave the dummy variable alone, though this is going to be a low priority. So in summary, it would be 'convert nominal data (e.g. character or factors) into **two** or more numeric binary model terms'

**Comment by juliasilge** [comment]
If you want a **factor** variable, then you do not want to use `step_dummy()`. This function takes nominal input likes factors and creates **numeric** output. That is the intended goal and design. You can [read more about dummy or indicator variables here](https://www.tmwr.org/recipes.html#dummies). One use case is models that require only numeric input and can't handle factor predictors; we outline [some of those model-to-model differences in this appendix](https://www.tmwr.org/pre-proc-table.html).

I can see that in your particular case the renaming might not feel necessary but even when creating a single numeric binary model term, it is typically important and helpful, for instance to know what the 1 and 0 values correspond to:

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
data(attrition)

attrition %>% count(Gender)
#>   Gender   n
#> 1 Female 588
#> 2   Male 882

rec <-
  recipe(Attrition ~ HourlyRate + Age + Gender, data = attrition) %>%
  step_dummy(Gender)

prep(rec) %>% bake(new_data = NULL)
#> # A tibble: 1,470 x 4
#>    HourlyRate   Age Attrition Gender_Male
#>         <int> <int> <fct>           <dbl>
#>  1         94    41 Yes                 0
#>  2         61    49 No                  1
#>  3         92    37 Yes                 1
#>  4         56    33 No                  0
#>  5         40    27 No                  1
#>  6         79    32 No                  1
#>  7         81    59 No                  0
#>  8         67    30 No                  1
#>  9         44    38 No                  1
#> 10         94    36 No                  1
#> # … with 1,460 more rows
```

<sup>Created on 2021-07-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

If you find it difficult to deal with the renamed variables afterward, we recommend using a selector function like `starts_with("Gender")`.

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌

**Comment by PathosEthosLogos** [comment]
Thank you very much, I really appreciate it, and sorry about the late reply.

Selector function sounds like a good idea actually; also seems tricky with reactive programming in Shiny.
