### ISSUE TITLE
`step_mutate()` shouldn't capture dots with `.named = TRUE`

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/recipes#759]
With `across()` in dplyr 1.0.0, it is becoming more common to have `mutate()` statements that don't have named dots. 

For example, I wanted to use `across()` to close this issue requesting `step_mutate_if()` #193, but the fact that we use `enquos(.named = TRUE)` keeps it from working right:

``` r
library(recipes)

df <- tibble(
  x = c(TRUE, FALSE),
  y = c(1, 2),
  z = c(TRUE, FALSE)
)

rec <- recipe(~., df) %>%
  step_mutate(across(where(is.logical), as.integer))

rec <- prep(rec, df)

bake(rec, new_data = NULL)
#> # A tibble: 2 x 4
#>   x         y z     `across(where(is.logical), as.integer)`$x    $z
#>   <lgl> <dbl> <lgl>                                     <int> <int>
#> 1 TRUE      1 TRUE                                          1     1
#> 2 FALSE     2 FALSE                                         0     0


# Expected output
mutate(df, across(where(is.logical), as.integer))
#> # A tibble: 2 x 3
#>       x     y     z
#>   <int> <dbl> <int>
#> 1     1     1     1
#> 2     0     2     0
```

I think all we need to do is remove the `.named = TRUE` from this line:
https://github.com/tidymodels/recipes/blob/254e7daa5e7d0448cd4be5fa54452ce30be362e7/R/mutate.R#L87

We should check other dplyr steps for this too

**Comment by vspinu** [comment]
sounds like an easy fix :)
