### ISSUE TITLE
Step to add missing columns

### ISSUE THREAD

**Issue by vspinu** [tidymodels/recipes#761]
Often the existence of all columns used during training is not guarantied. 

Would be nice to be able to generate missing columns from the template automatically. Something like `step_add_missing_columns`.

**Comment by DavisVaughan** [comment]
Do you mean that you might call `rec <- recipe(data_template)` to create the recipe specification, then later call `prep(rec, data_training)` with a different data set that might have different columns than `data_template `?

If your recipe specification did something like `step_pca(rec, foo)`, but `foo` was missing from `data_training`, then I would definitely expect to get an error.

How would `step_add_missing_columns()` be useful? Just adding a column of missings for `foo` would probably still result in a failure in `step_pca()`.

We make a fairly strong assumption that if you specify outcome/predictor variables in the recipe, then those are going to be available at training and test time. This assumption is even enforced when you use a recipe inside a workflow (if you try to predict with a dataset that is missing a predictor column, you get an error)

**Comment by vspinu** [comment]
> Do you mean that you might call rec <- recipe(data_template) to create the recipe specification, then later call prep(rec, data_training) with a different data set that might have different columns than data_template ?

No. Prep is with same data. Bake is with different (incomplete) data. 

Productions systems normally operate with jsons which might result in hundreds and thousands of predictors. Normally each prediction entity does not have a complete set of variables. So, one needs to complete them. Given that recipes already stores a template and type data for the entire data set, it seems natural to do it within the recipe pipeline. 

> This assumption is even enforced when you use a recipe inside a workflow (if you try to predict with a dataset that is missing a predictor column, you get an error)

I would presume that if recipe adds all those columns the workflow will be just fine, no? If the workflow does enforce it regardless of the recipe, that's would look like a really bad design to me.

**Comment by EmilHvitfeldt** [comment]
> I don't think that we'll include this in recipes, but you can could easily make a side-package with the step.

Are you saying that the step I proposed in https://github.com/tidymodels/recipes/issues/746 should be in a side-package or the step proposed in this issue should be in a side-package?

**Comment by topepo** [comment]
I'm good with having a step that does random imputation if there are missing values. I don't want to include a step that looks for structurally missing columns and filling them in 100% if noise.

**Comment by vspinu** [comment]
To clarify, the OP is not about imputing anything, it's about adding NA missing columns. This way the resulting dataset could be passed directly to prediction functions which don't mind missing values. 

This is a super useful and very practical feature. Every time I build a production system I have to implement such refilling by keeping track of a prototype/templates myself. So I was pretty surprised this features is not already there in recipes.

**Comment by EmilHvitfeldt** [comment]
Thanks for filing this issue! Unfortunately, we think it's out of scope for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. If you really like this feature, it is fairly easy to get this behavior using a zero-row tibble of the original data and a couple of dplyr functions. See reprex below where I did it with `complete_with_prototype()`.

``` r
library(recipes)

data("ames", package = "modeldata")

ames
#> # A tibble: 2,930 × 74
#>    MS_Sub…¹ MS_Zo…² Lot_F…³ Lot_A…⁴ Street Alley Lot_S…⁵ Land_…⁶ Utili…⁷ Lot_C…⁸
#>  * <fct>    <fct>     <dbl>   <int> <fct>  <fct> <fct>   <fct>   <fct>   <fct>  
#>  1 One_Sto… Reside…     141   31770 Pave   No_A… Slight… Lvl     AllPub  Corner 
#>  2 One_Sto… Reside…      80   11622 Pave   No_A… Regular Lvl     AllPub  Inside 
#>  3 One_Sto… Reside…      81   14267 Pave   No_A… Slight… Lvl     AllPub  Corner 
#>  4 One_Sto… Reside…      93   11160 Pave   No_A… Regular Lvl     AllPub  Corner 
#>  5 Two_Sto… Reside…      74   13830 Pave   No_A… Slight… Lvl     AllPub  Inside 
#>  6 Two_Sto… Reside…      78    9978 Pave   No_A… Slight… Lvl     AllPub  Inside 
#>  7 One_Sto… Reside…      41    4920 Pave   No_A… Regular Lvl     AllPub  Inside 
#>  8 One_Sto… Reside…      43    5005 Pave   No_A… Slight… HLS     AllPub  Inside 
#>  9 One_Sto… Reside…      39    5389 Pave   No_A… Slight… Lvl     AllPub  Inside 
#> 10 Two_Sto… Reside…      60    7500 Pave   No_A… Regular Lvl     AllPub  Inside 
#> # … with 2,920 more rows, 64 more variables: Land_Slope <fct>,
#> #   Neighborhood <fct>, Condition_1 <fct>, Condition_2 <fct>, Bldg_Type <fct>,
#> #   House_Style <fct>, Overall_Cond <fct>, Year_Built <int>,
#> #   Year_Remod_Add <int>, Roof_Style <fct>, Roof_Matl <fct>,
#> #   Exterior_1st <fct>, Exterior_2nd <fct>, Mas_Vnr_Type <fct>,
#> #   Mas_Vnr_Area <dbl>, Exter_Cond <fct>, Foundation <fct>, Bsmt_Cond <fct>,
#> #   Bsmt_Exposure <fct>, BsmtFin_Type_1 <fct>, BsmtFin_SF_1 <dbl>, …

prototype <- dplyr::slice(ames, 0)

rec <- recipe(Sale_Price ~ ., data = ames) |>
  step_unknown(all_nominal_predictors()) |>
  step_dummy(all_nominal_predictors()) |>
  step_zv(all_predictors()) |>
  step_normalize(all_numeric_predictors()) |>
  prep()

set.seed(1234)
incomplete_ames <- sample(ames, 10)

complete_with_prototype <- function(data, ptype) {
  dplyr::left_join(data, ptype, by = names(data)) |> 
    dplyr::relocate(names(ptype))
}

complete_with_prototype(incomplete_ames, prototype)
#> # A tibble: 2,930 × 74
#>    MS_Sub…¹ MS_Zo…² Lot_F…³ Lot_A…⁴ Street Alley Lot_S…⁵ Land_…⁶ Utili…⁷ Lot_C…⁸
#>    <fct>    <fct>     <dbl>   <int> <fct>  <fct> <fct>   <fct>   <fct>   <fct>  
#>  1 <NA>     <NA>         NA   31770 Pave   <NA>  <NA>    <NA>    AllPub  <NA>   
#>  2 <NA>     <NA>         NA   11622 Pave   <NA>  <NA>    <NA>    AllPub  <NA>   
#>  3 <NA>     <NA>         NA   14267 Pave   <NA>  <NA>    <NA>    AllPub  <NA>   
#>  4 <NA>     <NA>         NA   11160 Pave   <NA>  <NA>    <NA>    AllPub  <NA>   
#>  5 <NA>     <NA>         NA   13830 Pave   <NA>  <NA>    <NA>    AllPub  <NA>   
#>  6 <NA>     <NA>         NA    9978 Pave   <NA>  <NA>    <NA>    AllPub  <NA>   
#>  7 <NA>     <NA>         NA    4920 Pave   <NA>  <NA>    <NA>    AllPub  <NA>   
#>  8 <NA>     <NA>         NA    5005 Pave   <NA>  <NA>    <NA>    AllPub  <NA>   
#>  9 <NA>     <NA>         NA    5389 Pave   <NA>  <NA>    <NA>    AllPub  <NA>   
#> 10 <NA>     <NA>         NA    7500 Pave   <NA>  <NA>    <NA>    AllPub  <NA>   
#> # … with 2,920 more rows, 64 more variables: Land_Slope <fct>,
#> #   Neighborhood <fct>, Condition_1 <fct>, Condition_2 <fct>, Bldg_Type <fct>,
#> #   House_Style <fct>, Overall_Cond <fct>, Year_Built <int>,
#> #   Year_Remod_Add <int>, Roof_Style <fct>, Roof_Matl <fct>,
#> #   Exterior_1st <fct>, Exterior_2nd <fct>, Mas_Vnr_Type <fct>,
#> #   Mas_Vnr_Area <dbl>, Exter_Cond <fct>, Foundation <fct>, Bsmt_Cond <fct>,
#> #   Bsmt_Exposure <fct>, BsmtFin_Type_1 <fct>, BsmtFin_SF_1 <dbl>, …

bake(rec, complete_with_prototype(incomplete_ames, prototype))
#> # A tibble: 2,930 × 275
#>    Lot_Frontage Lot_Area Year_…¹ Year_…² Mas_V…³ BsmtF…⁴ BsmtF…⁵ Bsmt_…⁶ Total…⁷
#>           <dbl>    <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
#>  1           NA   2.74        NA      NA      NA      NA      NA      NA      NA
#>  2           NA   0.187       NA      NA      NA      NA      NA      NA      NA
#>  3           NA   0.523       NA      NA      NA      NA      NA      NA      NA
#>  4           NA   0.128       NA      NA      NA      NA      NA      NA      NA
#>  5           NA   0.467       NA      NA      NA      NA      NA      NA      NA
#>  6           NA  -0.0216      NA      NA      NA      NA      NA      NA      NA
#>  7           NA  -0.663       NA      NA      NA      NA      NA      NA      NA
#>  8           NA  -0.653       NA      NA      NA      NA      NA      NA      NA
#>  9           NA  -0.604       NA      NA      NA      NA      NA      NA      NA
#> 10           NA  -0.336       NA      NA      NA      NA      NA      NA      NA
#> # … with 2,920 more rows, 266 more variables: First_Flr_SF <dbl>,
#> #   Second_Flr_SF <dbl>, Gr_Liv_Area <dbl>, Bsmt_Full_Bath <dbl>,
#> #   Bsmt_Half_Bath <dbl>, Full_Bath <dbl>, Half_Bath <dbl>,
#> #   Bedroom_AbvGr <dbl>, Kitchen_AbvGr <dbl>, TotRms_AbvGrd <dbl>,
#> #   Fireplaces <dbl>, Garage_Cars <dbl>, Garage_Area <dbl>, Wood_Deck_SF <dbl>,
#> #   Open_Porch_SF <dbl>, Enclosed_Porch <dbl>, Three_season_porch <dbl>,
#> #   Screen_Porch <dbl>, Pool_Area <dbl>, Misc_Val <dbl>, Mo_Sold <dbl>, …
```

<sup>Created on 2022-12-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
