### ISSUE TITLE
undo deprecation of `step_kpca()`

### ISSUE THREAD

**Issue by hfrick** [tidymodels/recipes#762]
it was deprecated in version 0.1.7

**Comment by topepo** [comment]
I think that I'd like to rescind this. A user did contact me a while back saying that he uses this for other kernels (i.e. not polynomial or RBFs).

**Comment by juliasilge** [comment]
Do we have any [lifecycle](https://lifecycle.r-lib.org/) way to communicate that something is getting un-deprecated? Or should we just take out the deprecation and put it in the documentation? If so, we'll need to carefully make sure this step is up-to-date in terms of recent documentation changes; I know I wasn't as careful with deprecated steps.

**Comment by hfrick** [comment]
note to self from team meeting: take out the deprecation, mention it in the news file, and make sure the docs are up to date
