### ISSUE TITLE
split up reference list of dummy variable steps

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#769]
the [STEP FUNCTIONS - DUMMY VARIABLES AND ENCODINGS](https://recipes.tidymodels.org/reference/index.html#section-step-functions-dummy-variables-and-encodings) reference page is getting a little crowded right now.

Both `step_date()` and `step_holiday()` could be their own section. Since they both deal with date variables.
 
Then I would suggest splitting the rest into the 3 main groups

- takes factor variables and return factor variables
- takes factor variables and return numeric variables
- conversion between different types

## factor2numeric steps

- `step_count()`
- `step_dummy()`
- `step_integer()`
- `step_ordinalscore()`
- `step_regex()`

## factor2factor steps

- `step_novel()`
- `step_other()`
- `step_relevel()`
- `step_unknown()`
- `step_unorder()`

## conversion steps

- `step_bin2factor()` numeric -> factor
- `step_factor2string()` factor -> string
- `step_string2factor()` string -> factor
- `step_num2factor()` numeric -> factor

At last, we have `step_indicate_na()`, which is an odd one out, and could fit a little bit everywhere. factor -> factor + numeric

**Comment by juliasilge** [comment]
We chatted with a few folks and decided that at the current length, we prefer to focus on the similarities of these steps and keep them together. Thanks! 🙌
