### ISSUE TITLE
Error in printing recipe when it has certain step_rm

### ISSUE THREAD

**Issue by NikKrieger** [tidymodels/recipes#781]
The issue happens when you have a lot of variables within `c()`

``` r
print(
  recipes::step_rm(
    recipes::recipe(mtcars),
    !c(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x)
  )
)
#> Data Recipe
#> 
#> Inputs:
#> 
#>   11 variables (no declared roles)
#> 
#> Operations:
#> 
#> Delete terms
#> Warning in max(which(cumsum(adj_wd) < width)): no non-missing arguments to max;
#> returning -Inf
#> 1 items
```

<sup>Created on 2021-09-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by EmilHvitfeldt** [comment]
Can you try to reproduce this error using the developmental version of the package? A fix was added in https://github.com/tidymodels/recipes/pull/721 to deal with this issue.

You can install the development version from GitHub:
```r
# install.packages("devtools")
devtools::install_github("tidymodels/recipes")
```

**Comment by NikKrieger** [comment]
Yes, it is fixed!
