### ISSUE TITLE
Rename the step_normalize()

### ISSUE THREAD

**Issue by czopluoglu** [tidymodels/recipes#785]
Please consider renaming the function `step_normalize()` to avoid confusion and misconception. `normalize` implies that we change the distribution of the variable (like what we do using Box-Cox transformation), however this function only standardize a variable (not changing the characteristics of a distribution). Based on what this function does, I believe `step_standardize()` would be a more appropriate name.

**Comment by juliasilge** [comment]
Related to #551

**Comment by EmilHvitfeldt** [comment]
And here https://github.com/tidymodels/recipes/issues/497

**Comment by juliasilge** [comment]
Thanks so much for your feedback @czopluoglu! 🙌 You can check out some previous discussion in those links above; we still feel like `step_normalize()` is the best choice for tidymodels.
