### ISSUE TITLE
Use of author tag in documentation

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#789]
The author tag isn't used that many times https://github.com/tidymodels/recipes/search?q=author, but it does give a pretty prominent space in the {pkgdown} site (image below), which in the case of `bake()` and `prep()` seems a little redundant since @topepo is also the author of the package itself

<img width="910" alt="Screen Shot 2021-09-11 at 3 51 43 PM" src="https://user-images.githubusercontent.com/14034784/132966344-7c941c73-330a-41c2-a2f8-0f564a47c726.png">

**Comment by DavisVaughan** [comment]
We can probably just remove them everywhere. I don't think we typically use this field very often (yardstick is the only exception I can think of)
