### ISSUE TITLE
use of as_tibble in bake.*() functions

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#798]
It is inconsistent how `bake.*()` steps are ended, with respect to keeping `new_data` as a tibble. 

Some steps like `step_range()` just returns `as_tibble(new_data)`

https://github.com/tidymodels/recipes/blob/788d409b96587a3377b5846df93774dfce511726/R/range.R#L123

other steps like `step_integer()`, tests before,

https://github.com/tidymodels/recipes/blob/788d409b96587a3377b5846df93774dfce511726/R/integer.R#L153-L155

Lastly, there are steps that doesn't end with a call to `as_tibble()` such as `step_relu()`

https://github.com/tidymodels/recipes/blob/788d409b96587a3377b5846df93774dfce511726/R/relu.R#L143-L151

**Comment by DavisVaughan** [comment]
I don't think it ends up mattering too much since after each bake step we convert to a tibble
https://github.com/tidymodels/recipes/blob/77fa788b3fed542c7832fc00a8b9725a165e6a46/R/recipe.R#L580

**Comment by EmilHvitfeldt** [comment]
Neat, then it seems that `as_tibble()` calls inside bake steps are rather superfluous.
