### ISSUE TITLE
Add Spark as a backend for recipes

### ISSUE THREAD

**Issue by xiaoxi-david** [tidymodels/recipes#827]
Could you add Spark as a backend for recipes?

It would make the transition of code from a laptop to a Spark cluster much smoother as dplyr verbs and parsnip models currently work with Spark, but recipes steps don't.

**Comment by juliasilge** [comment]
We don't currently have plans to extend recipes support to Spark, as recipes doesn't really have as fully featured an idea of a computational engine like parsnip. Computations in recipes are currently pretty much all done in R, not with interchangeable backend computational engines. 

This would be a significant investment of developer time/effort so I would not expect to see something like this anytime soon, but we can track interest in this as a feature here in this issue. 👍
