### ISSUE TITLE
Inconsistent documentation for `tidy()` across steps

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#831]
The phrase `when you `tidy()` this step...` is used across all the steps but the way it is linking to `tidy()` is a little different across the steps.

https://github.com/tidymodels/recipes/blob/a81d9998ad3a4e521659e2c16d0694e7d999877f/R/rm.R#L12-L13

https://github.com/tidymodels/recipes/blob/a81d9998ad3a4e521659e2c16d0694e7d999877f/R/pls.R#L57-L58

https://github.com/tidymodels/recipes/blob/a81d9998ad3a4e521659e2c16d0694e7d999877f/man-roxygen/kpca-info.R#L25-L26

**Comment by juliasilge** [comment]
Our current preference would be this:

```r
When you [`tidy()`][tidy.recipe()] this step,
```
