### ISSUE TITLE
parameters finalize not using recipe prepared data

### ISSUE THREAD

**Issue by JensPMB** [tidymodels/recipes#840]
## The problem

I'm having trouble with parameters() %>% finalize(xyz) to correctly set the upper bound for mtry. In https://www.tmwr.org/tuning.html it states the finalize() function can execute the recipe once to obtain the correct dimensions. Using the ames data as outlined in this chapter I can illustrate that mtry is updated to the unprepared data rather than recipe prepared (and hence upper range is above the number of available features.)

## Reproducible example
``` r
require(tidymodels)
#> Loading required package: tidymodels
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip


data(ames)
ames_split <- initial_split(ames, prop = 0.80)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)

ncol1 <- ncol(ames_train) # 74 columns

pca_rec <- 
  recipe(Sale_Price ~ ., data = ames_train) %>% 
  step_pca(all_numeric_predictors(), threshold = .5) # remove some columns, for example by PCA

ncol2 <- ncol(pca_rec %>% prep(ames_train) %>% juice()) # 42 columns

rf_spec <- 
  rand_forest(mtry = tune()) %>% 
  set_engine("ranger")

updated_param <- 
  workflow() %>% 
  add_model(rf_spec) %>% 
  add_recipe(pca_rec) %>% 
  parameters() %>% 
  finalize(ames_train)

n3 <- updated_param %>% pull_dials_object("mtry")

paste("Orig Columns", ncol1, sep = " ")
#> [1] "Orig Columns 74"
paste("Recipe Columns", ncol2, sep = " ")
#> [1] "Recipe Columns 42"
paste("Finalize mtry upper", n3$range$upper, sep=" ")
#> [1] "Finalize mtry upper 74"
```

<sup>Created on 2021-10-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I can solve this by using finalize(mtry(), recipe %>% prep(xyz) %>% juice()) but this requires an extra prep step to obtain the final number of features so was interested to know if the above was a bug or feature.

Thanks.

**Comment by EmilHvitfeldt** [comment]
I'm going to close this issue. We will keep track of this in https://github.com/tidymodels/tune/issues/411
