### ISSUE TITLE
Automatically add the missing columns with NAs when using `predict` function

### ISSUE THREAD

**Issue by albert-ying** [tidymodels/recipes#855]
Sometimes when I'm testing my model on new datasets, I got an error like this.

```
predict(wf, new_data)
Error: The following required columns are missing:...
```

To obtain the prediction, I have to manually add these missing predictors, and fill them with NAs.

Is there any reason why the workflow requires the exact same set of predictors in the new dataset? Alternatively, a better default would be automatically adding these missing predictors with NAs, and imputing them when there is `step_impute_*` in the recipe. And only gives errors when there is no impute step in the workflow.

**Comment by DavisVaughan** [comment]
This has come up before https://github.com/tidymodels/recipes/issues/502

I think it is a very dangerous idea to allow missing predictors to be automatically added to a data frame and filled with NAs. I don't see how that would be useful anyways, what prediction do you get for an `NA` column?

**Comment by albert-ying** [comment]
Hi Davis, what you said makes sense. However, considering I have a Lasso regression model. Say I have 1000 predictors in my training set, while only 10 of them end up meaningful in the model.

In this case, when predicting on a new dataset, those 90 predictors are not important, and can totally be NAs.

But now need to do this tricky thing to extract the original input of the model, and add them to my data filled with `NAs`

```
    predictors = extract_mold(wf)$predictor |>
      colnames()
```

The major disadvantages here are: 1. I have to keep the training data in my model to "know" (couldn't `butcher` them out) what are the full predictor set, even though I don't need 90% of them. 2. Extra trick steps to "prep" the new dataset.

And not just predictors, the `predict` function also requires the new dataset have the same `id` columns.

My idea is that, maybe add a preprocessing function to `prep` the new dataset according to the `workflow` object. Maybe like allow the user to select what default value to fill to the missing columns.

**Comment by topepo** [comment]
> In this case, when predicting on a new dataset, those 90 predictors are not important, and can totally be NAs.

Zero not NA (since NA values make more NA values).

Apart from the issue with IDs, this is a fundamental issue with most R infrastructure. For example, the `terms` objects always require the original set of predictors even if the model does not use them in the prediction function (`rpart` is a great example of this). You would have to refit the model with just these predictors and, depending on the model, you will not get exactly the same estimates. 

Even if we made this change, most models will fail with the proposed solution. It is _very_ frustrating. 

There are some packages (like tidypredict) that translate the model equation into an R (or SQL) expression that can be used independent of the model object. glmnet is _not_ included there but would be an easy pull request if you wanted to make one. 

The stacks package uses glmnet and [converts the prediction equation to an R expression](https://github.com/tidymodels/stacks/blob/main/R/expressions.R) so you could try something like that.

**Comment by EmilHvitfeldt** [comment]
This is also related to the talk in https://github.com/tidymodels/recipes/issues/761. We don't plan on adding functionality to fill non-provided columns inside recipes. 

Recent changes this summer does with with `id` column problem you are described. You can read more about it here https://www.tidyverse.org/blog/2022/07/tidymodels-2022-q2/#non-standard-roles-in-recipes.

Long story short, you can use `update_role_requirements()` to specify that some columns (such as id variables) isn't needed at bake time

``` r
library(tidymodels)

tate_rec <- recipe(year ~ ., data = tate_text) |>
  update_role(id, title, new_role = "id") |>
  update_role_requirements(role = "id", bake = FALSE) |>
  step_dummy_extract(artist, medium, sep = ", ") |>
  prep()

tate_rec |>
  bake(tate_text)
#> # A tibble: 4,284 × 2,678
#>        id title     year artis…¹ artis…² artis…³ artis…⁴ artis…⁵ artis…⁶ artis…⁷
#>     <dbl> <fct>    <dbl>   <int>   <int>   <int>   <int>   <int>   <int>   <int>
#>  1  21926 Proposa…  1990       0       0       1       0       0       0       0
#>  2  20472 Michael   1990       0       0       0       0       0       0       0
#>  3  20474 Geoffrey  1990       0       0       0       0       0       0       0
#>  4  20473 Jake      1990       0       0       0       0       0       0       0
#>  5  20513 To the …  1990       0       0       0       0       0       0       0
#>  6  21389 Phaëthon  1990       0       0       0       0       0       0       0
#>  7 121187 Untitled  1990       0       0       0       0       0       0       0
#>  8  19455 Green V…  1990       0       0       0       0       0       0       0
#>  9  20938 Present…  1990       0       0       0       0       0       0       0
#> 10 105941 Joseph …  1990       0       0       0       0       0       0       0
#> # … with 4,274 more rows, 2,668 more variables: artist_Agnes <int>,
#> #   artist_Ahtila <int>, artist_Ai <int>, artist_Akram <int>,
#> #   artist_Aksel <int>, artist_Al <int>, artist_Al.Ani <int>,
#> #   artist_Alan <int>, artist_Albert <int>, artist_Aleksandra <int>,
#> #   artist_Alex <int>, artist_Alexander <int>, artist_Alexandre.da <int>,
#> #   artist_Alfredo <int>, artist_Alice <int>, artist_Alimpiev <int>,
#> #   artist_Alison <int>, artist_Allen <int>, artist_Allora <int>, …

tate_rec |>
  bake(tate_text |> select(-id, -title))
#> # A tibble: 4,284 × 2,676
#>     year artis…¹ artis…² artis…³ artis…⁴ artis…⁵ artis…⁶ artis…⁷ artis…⁸ artis…⁹
#>    <dbl>   <int>   <int>   <int>   <int>   <int>   <int>   <int>   <int>   <int>
#>  1  1990       0       0       1       0       0       0       0       0       0
#>  2  1990       0       0       0       0       0       0       0       0       0
#>  3  1990       0       0       0       0       0       0       0       0       0
#>  4  1990       0       0       0       0       0       0       0       0       0
#>  5  1990       0       0       0       0       0       0       0       0       0
#>  6  1990       0       0       0       0       0       0       0       0       0
#>  7  1990       0       0       0       0       0       0       0       0       0
#>  8  1990       0       0       0       0       0       0       0       0       0
#>  9  1990       0       0       0       0       0       0       0       0       0
#> 10  1990       0       0       0       0       0       0       0       0       0
#> # … with 4,274 more rows, 2,666 more variables: artist_Ai <int>,
#> #   artist_Akram <int>, artist_Aksel <int>, artist_Al <int>,
#> #   artist_Al.Ani <int>, artist_Alan <int>, artist_Albert <int>,
#> #   artist_Aleksandra <int>, artist_Alex <int>, artist_Alexander <int>,
#> #   artist_Alexandre.da <int>, artist_Alfredo <int>, artist_Alice <int>,
#> #   artist_Alimpiev <int>, artist_Alison <int>, artist_Allen <int>,
#> #   artist_Allora <int>, artist_Almeida <int>, artist_Almond <int>, …
```

<sup>Created on 2022-12-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
