### ISSUE TITLE
`prep(., retain = FALSE)` keeps record of dataset in `environment(steps[[i]]$terms[[j]])[["."]]$template`

### ISSUE THREAD

**Issue by AshesITR** [tidymodels/recipes#859]
According to the docs, `prep(., retain = FALSE)` should _not_ keep the original dataset in the object, causing a smaller object size.
However, the training dataset is only removed from the template slot.
Each step keeps an additional copy in its `terms` environments, in `.$template`.

To see the problem, follow below reprex and see that we can greatly reduce the size, by clearing the template slot of all term environments in the recipe - all while still allowing `bake` to succeed.

This behaviour is particularly problematic when using recipes with large datasets, where it is necessary to strip as much data from the trained recipe as possible for efficient production use.

I'm not certain that destroying the remaining data in `prep(., retain = FALSE)` won't break the original recipe, because the environments are the same. Therefor, if I am not mistaken, a correct fix would need to instead duplicate these terms and then create a new environment with the same parent before deleting the data.

I'm willing to work on a PR. Please let me know which approach you prefer regarding the modification of `environment(recipe$steps[[i]]$terms[[j]])`: in-place or copy?
In-place might affect code which `prep(., retain = FALSE)`'s and then modifies the recipe again to `prep()` a second time.

``` r
library(recipes)
library(pryr)

rec <- recipe(data = dplyr::bind_rows(rep(list(iris), 10)), formula = Species ~ .) %>%
  step_normalize(starts_with("Petal.")) %>%
  step_BoxCox(starts_with("Sepal."))

rec_prepped <- prep(rec)
rec_prepped_noretain <- prep(rec, retain = FALSE)
rec_prepped_stripped <- prep(rec_prepped, retain = FALSE)

# even retain = FALSE keeps data
get(".", envir = environment(rec_prepped_noretain$steps[[1]]$terms[[1]]))$template
#> # A tibble: 1,500 x 5
#...
get(".", envir = environment(rec_prepped_stripped$steps[[1]]$terms[[1]]))$template
#> # A tibble: 1,500 x 5
#...

rec_prepped_truly_stripped <- local({
  r <- recipe(data = dplyr::bind_rows(rep(list(iris), 10)), formula = Species ~ .) %>%
    step_normalize(starts_with("Petal.")) %>%
    step_BoxCox(starts_with("Sepal.")) %>%
    prep() %>%
    prep(retain = FALSE)
  lapply(r$steps, function(step) {
    lapply(step$terms, function(term) {
      env <- environment(term)
      env[["."]]$template <- NULL
    })
  })
  r
})

sapply(
  list(
    rec = rec,
    prep = rec_prepped,
    noretain = rec_prepped_noretain,
    strip = rec_prepped_stripped,
    restrip = rec_prepped_truly_stripped
  ),
  object_size
)
#>      rec     prep noretain    strip  restrip 
#>   123656   132104    78096    78096    31992

baked_sets <- lapply(
  list(
    prep = rec_prepped,
    noretain = rec_prepped_noretain,
    strip = rec_prepped_stripped,
    restrip = rec_prepped_truly_stripped
  ),
  bake,
  new_data = iris
)

vapply(baked_sets, identical, y = baked_sets[[1]], logical(1L))
#>     prep noretain    strip  restrip 
#>     TRUE     TRUE     TRUE     TRUE

serialize_size <- function(x) {
  con <- rawConnection(raw(), "wb")
  on.exit(close(con))
  serialize(x, con)
  length(rawConnectionValue(con))
}

sapply(
  list(
    rec = rec,
    prep = rec_prepped,
    noretain = rec_prepped_noretain,
    strip = rec_prepped_stripped,
    restrip = rec_prepped_truly_stripped,
    dataset = dplyr::bind_rows(rep(list(iris), 10))
  ),
  serialize_size
)
#>      rec     prep noretain    strip  restrip  dataset 
#>   168692   171465   117457   117457    13767    54399
```

<sup>Created on 2021-11-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by juliasilge** [comment]
Ah, that `terms` environment! You are correct that `retain` does not deal with this but the package that we support that _does_ deal with issues like this is [butcher](https://butcher.tidymodels.org/), which does support recipe steps.

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
library(butcher)

rec <- recipe(data = dplyr::bind_rows(rep(list(iris), 10)), formula = Species ~ .) %>%
  step_normalize(starts_with("Petal.")) %>%
  step_BoxCox(starts_with("Sepal."))

rec_prepped <- prep(rec)

lobstr::obj_size(rec_prepped)
#> 128,656 B
lobstr::obj_size(butcher(rec_prepped))
#> 70,320 B
```

<sup>Created on 2021-11-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The other thing to keep in mind is that the R formula is [memory-inefficient when you have a lot of variables](https://rviews.rstudio.com/2017/03/01/the-r-formula-method-the-bad-parts/), so you might want to use a different interface (no formula) for defining your recipe. Check out [this documentation, including the examples](https://recipes.tidymodels.org/reference/recipe.html#defining-recipes).

**Comment by AshesITR** [comment]
Thanks for the pointer, I didn't know of {butcher}. Should I raise an issue there?

NB the "bad" terms seem to stem from the tidy selectors. Is there a way to prevent these from occurring?
Using `recipe(x = dplyr::bind_rows(rep(list(iris), 10)))` without a formula exhibits the same behavior seen here.

**Comment by juliasilge** [comment]
I do believe that tidyselect and the recipe-specific selectors you are using here depend on that infrastructure. We can remove the `terms` environments afterward with butcher but I don't believe we can offer the flexibility you have here without that infrastructure.

**Comment by AshesITR** [comment]
Closing this as the only thing we can do about is is implement https://github.com/tidymodels/butcher/issues/207
