### ISSUE TITLE
Variables vs Columns

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#864]
The words "variable" and "column" are being interchangeably throughout the documentation. Many times used on the same page.

https://github.com/tidymodels/recipes/blob/d4f4155606786ccf381a5b13c558ccacbe4facb8/R/inverse.R#L9

Could this be a source of confusion? Would it be worth fixing? If we were to act on this, I would lean towards using "columns" more often.

**Comment by topepo** [comment]
I don't think that there is a clear way to be consistent. I see those two as synonymous and each has a different relationship with the term "features". I see your point but I don't think that we can standardize on one or the other give how wide variety of things that steps can do.

**Comment by EmilHvitfeldt** [comment]
I'm closing this issue. It doesn't appear that there will be a easy way to do it
