### ISSUE TITLE
Having a `translate_recipe()`  to print a recipe expressed as `dplyr`/`tidyr` code

### ISSUE THREAD

**Issue by emmansh** [tidymodels/recipes#878]
## Feature

The `step_*()` verbs are wrappers for preprocessing tasks. They convey clear meaning and standardize the procedure. However, they obscure the underlying code that is used to carry the procedure. Even if one digs inside the documentation and source code for what each step verb does, it is hard to comprehend what happens under the hood in a certain data set. 

Elsewhere, the `tidyverse` offers a possible solution to this. For example, consider [`show_query()`](https://dplyr.tidyverse.org/reference/explain.html) from `dbplyr` that translates `dplyr` code to `SQL`. Similarly, [`show_query()` works in `dtplyr`](https://dtplyr.tidyverse.org/articles/translation.html) by translating `dplyr` code to `data.table` syntax.

I therefore wonder whether it's feasible to add a similar translation function to translate a recipe to `dplyr` and/or `tidyr` code. The advantage is mainly educational: users could _see_ the code and better _understand_ what is going on under the hood. They may have insights about it, and consequently ideas to improve it or write new `step_*()` verbs that address a preprocessing task slightly differently. 

For example, [this StackOverflow post](https://stackoverflow.com/questions/70379233/how-to-translate-recipesstep-dummy-to-dplyr-tidyr-code) shows a desire to understand how `step_dummy()` works under the hood.

**Comment by juliasilge** [comment]
What allows this for dbplyr, etc, is that code is being generated and then translated; recipes doesn't really work like that. We're not generating code to compute on but rather computing some quantity like a set of means or columns to do something with. It might be helpful to really focus on how recipes learns some transformation from training data and then applies it to other data. A prepped recipe stores in itself whatever we need to be able to apply the transformation to new data.

Take a look at [`step_corr()`](https://github.com/tidymodels/recipes/blob/main/R/corr.R), which computes which variables to remove during `prep()` and then removes those during `bake()`:

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
data(biomass, package = "modeldata")

set.seed(3535)
biomass$duplicate <- biomass$carbon + rnorm(nrow(biomass))
biomass_tr <- biomass[biomass$dataset == "Training",]
biomass_te <- biomass[biomass$dataset == "Testing",]

rec <- recipe(HHV ~ carbon + hydrogen + oxygen + nitrogen +
                sulfur + duplicate,
              data = biomass_tr) %>%
  step_corr(all_numeric_predictors(), threshold = .5)

prepped <- prep(rec, training = biomass_tr)

prepped$steps[[1]]$removals
#> [1] "oxygen" "carbon"
```

<sup>Created on 2022-01-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Or [`step_center()`](https://github.com/tidymodels/recipes/blob/main/R/center.R), which computes means during `prep()` and then subtracts those during `bake()`:

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
data(biomass, package = "modeldata")

set.seed(3535)
biomass$duplicate <- biomass$carbon + rnorm(nrow(biomass))
biomass_tr <- biomass[biomass$dataset == "Training",]
biomass_te <- biomass[biomass$dataset == "Testing",]

rec <- recipe(HHV ~ carbon + hydrogen + oxygen + nitrogen +
                sulfur + duplicate,
              data = biomass_tr) %>%
  step_center(carbon, contains("gen"), -hydrogen)

prepped <- prep(rec, training = biomass_tr)

prepped$steps[[1]]$means
#>    carbon    oxygen  nitrogen 
#> 48.354145 38.524671  1.074592
```

<sup>Created on 2022-01-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
