### ISSUE TITLE
Non-standard column names and step_dummy

### ISSUE THREAD

**Issue by ninohardt** [tidymodels/recipes#879]
## The problem

Non-standard variables names are not supported by `step`* functions. The problem is caused by the use of `str2lang`. I don't quite see where str2lang is called, though.

## Reproducible example

```r
tibble(x=1:10,`variable b`=factor(sample(c('a','b','c'),10,T))) %>%
recipe(~.)%>% step_dummy(`variable b`) %>% prep %>% bake(NULL) 

tibble(x=1:10,`variable b`=factor(sample(c('a','b','c'),10,T))) %>%
  recipe(~.)%>% step_dummy('variable b') %>% prep %>% bake(NULL) 
```
Error:
```r
Error in str2lang(x) : <text>:1:11: unexpected symbol
1: ~variable b
```

**Comment by juliasilge** [comment]
This comes from how base R creates a formula:

``` r
as.formula("~variable b")
#> Error in str2lang(x): <text>:1:11: unexpected symbol
#> 1: ~variable b
#>               ^
```

<sup>Created on 2022-01-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

For a workaround, we recommend that you use [`step_clean_names()` from textrecipes](https://textrecipes.tidymodels.org/reference/step_clean_names.html) (or you could use `janitor::clean_names()` before starting your tidymodels analysis):

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
library(textrecipes)
df <- tibble(x=1:10,`variable b`=factor(sample(c('a','b','c'),10,TRUE)))

recipe(~., data = df) %>% 
  step_clean_names("variable b") %>%
  step_dummy(all_nominal_predictors()) %>% 
  prep() %>% 
  bake(NULL) 
#> # A tibble: 10 × 2
#>        x variable_b
#>    <int> <fct>     
#>  1     1 c         
#>  2     2 b         
#>  3     3 b         
#>  4     4 a         
#>  5     5 a         
#>  6     6 a         
#>  7     7 b         
#>  8     8 a         
#>  9     9 a         
#> 10    10 c
```

<sup>Created on 2022-01-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by topepo** [comment]
You can use non-standard names in formulas and in `model.matrix()`: 

``` r
as.formula("~`variable b`")
#> ~`variable b`
dat <- tibble::tibble(x = 1:10, `variable b` = factor(sample(c('a', 'b', 'c'), 10, TRUE)))
model.matrix(~`variable b`, data = dat)
#>    (Intercept) `variable b`b `variable b`c
#> 1            1             0             1
#> 2            1             1             0
#> 3            1             0             0
#> 4            1             1             0
#> 5            1             1             0
#> 6            1             0             0
#> 7            1             0             1
#> 8            1             0             1
#> 9            1             0             0
#> 10           1             0             1
#> attr(,"assign")
#> [1] 0 1 1
#> attr(,"contrasts")
#> attr(,"contrasts")$`variable b`
#> [1] "contr.treatment"
```

<sup>Created on 2022-01-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I suspect this is related to how we pass the data to `model.matrix()` within `bake.step_dummy()`. We must not be protecting the column name (in the same way that the backticks do).

**Comment by ninohardt** [comment]
Of course, I can either sanitize column names or use the corresponding base function, but I do like my non-standard variable names and I do like the recipe syntax. Max: where is `str2lang` called? I do not see it within the `step_dummy` function.

**Comment by juliasilge** [comment]
@ninohardt `str2lang()` is not called explicitly by `step_dummy()`; it is used [by the base function `as.formula()`](https://github.com/tidymodels/recipes/blob/4960c29551039ab72c5f4b20dd147a7e8e9f44f2/R/dummy.R#L198).

``` r
as.formula("~variable b")
#> Error in str2lang(x): <text>:1:11: unexpected symbol
#> 1: ~variable b
#>               ^
```

<sup>Created on 2022-01-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It happens in `prep` actually, I believe because of how we are using `paste0` and converting something to a character vector. We might be better off using rlang:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

df <- tibble(variable_a = factor(sample(c('a','b','c'),10,TRUE)),
             `variable b` = factor(sample(c('a','b','c'),10,TRUE)))
col_names <- colnames(df)

rlang::new_formula(NULL, rlang::sym(col_names[1]))
#> ~variable_a
rlang::new_formula(NULL, rlang::sym(col_names[2]))
#> ~`variable b`
```

<sup>Created on 2022-01-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I haven't worked through `one_hot` needs yet.
