### ISSUE TITLE
Deprecated rlang functions

### ISSUE THREAD

**Issue by lionel-** [tidymodels/recipes#883]
Just a note that `exiting()` has been deprecated in rlang 0.4.0. rlang 1.0 also deprecates `with_handlers()`.

`with_handlers()` is silently deprecated for now, but `exiting()` has been issuing soft-deprecation warnings (so only testthat) since 0.4.0. Is it possible this isn't covered by unit tests in recipes? https://github.com/tidymodels/recipes/blob/558625689b0b4c87761cd934acc3972ff5e581e6/R/terms-select.R#L120

Oh but this is probably because it's evaluated by pkgload and not by testthat, since it's a top-level call. No urgency but would be nice to fix.

**Comment by topepo** [comment]
I suspect that there are many installs of old recipe versions that use `terms_select()`. If those people update rlang, their recipes code will break. 

We will hard deprecate `terms_select()` in the upcoming version of recipes (maybe release near the end of this month). Can you remove your two functions after we remove `terms_select()`?

**Comment by lionel-** [comment]
oh I wasn't planning on removing these functions from rlang anytime soon, but it would be nice to remove them from recipes in your next release.

It looks like `with_handlers()` is only used with exiting handlers here so it can be replaced by `tryCatch()` and `exiting()` can be simply deleted.
