### ISSUE TITLE
Add week of month (wom) step_date feature

### ISSUE THREAD

**Issue by DoktorMike** [tidymodels/recipes#896]
## Feature

In situations when you want to model the effect of how close you are to the end of the month and your data is of weekly granularity I often use week of month as a variable. I see that day of month (dom) is already there, so I think a week of month (wom) would be very useful as well. I can take a stab at implementing it if there are no concerns regarding adding this feature.

**Comment by tonyk7440** [comment]
Hi @DoktorMike , I think [this](https://business-science.github.io/timetk/reference/step_timeseries_signature.html) should solve this for you, specifically the `date_mweek` column

**Comment by DoktorMike** [comment]
Thanks @tonyk7440 ! It sure does. Closing this.
