### ISSUE TITLE
Feature-wise tuning of common parameters

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/recipes#897]
Hi,

When adding `tune()` to recipe steps, such as for the `deg_free` parameter of `step_ns()`, the default tuning approach is to find the "best" value of `deg_free` (based on some metric) and that `deg_free` is applied to each variable. But it seems to be the more appropriate choice might be to find the best degrees of freedom for each variable independently, as there is often no reason to assume one `deg_free` is going to fit all. However, if I simulate 10 numeric predictors, where 8 have truly linear relationships and 2 are non-linear, the tuning will likely yield `deg_free` of `1` if the following recipe is used:

```r
recipe(Y ~ ., data) %>%
  step_ns(all_numeric_predictors(), deg_free = tune())
```

If I've got many variables that I want to explore non-linear relationships, it is quite verbose to type out each variable in its own step, e.g.:

```r
recipe(Y ~ ., data) %>%
  step_ns(X1, deg_free = tune('dfX1')) %>%
  step_ns(X2, deg_free = tune('dfX2')) %>%
  ...
  step_ns(X10, deg_free = tune('dfX10'))
```
Additionally, if I wanted to restrict each `deg_free` to a smaller set of possible non-linear transforms, I need to verbosely provide the `parameters()` object to `tune_grid()`
```r
  tune_grid(
    object = wflow,
    resamples = rs,
    param_info = parameters(
      dfX1 = deg_free(c(1, 3)),
      dfX2 = deg_free(c(1, 3)),
      ...,
      dfX10 = deg_free(c(1, 3)),
      mixture(), 
      penalty()
    )
  )
```

Is there a better way to allow for feature-wise tuning of a common parameter or is the manual approach shown above the only way?

**Comment by mattwarkentin** [comment]
Thanks for the quick response, @juliasilge. It would take some more thinking, but would it ever make sense to have a second sentinel function, such as `tune_each()`, or something similar, as a shorthand for indicating that you want the tuning done for each selected variable.
```r
recipe(Y ~ ., data) %>%
  step_ns(all_numeric_predictors(), deg_free = tune_each())
```

Then some magic happens behind the scenes to expand it out. The problem with the manual approach is it doesn't scale well to lots of predictors, or when the predictors are unknown because of previous steps.

**Comment by mattwarkentin** [comment]
This has been my probably fragile programmatic solution for the time being:
``` r
library(tidymodels)

tune_each <- function(expr, data, recipe, step, prefix = '') {
  vars <- syms(names(tidyselect::eval_select({{expr}}, data)))
  ids <- as.character(glue::glue('{prefix}{vars}'))
  map2(vars, ids, function(x, y) {
    recipe <<- step(recipe, !!x, deg_free = tune(y))
  })
  recipe
}

data <- 
  matrix(rnorm(100*10), nrow = 100) %>% 
  as_tibble() %>% 
  mutate(
    Y = sample(0:1, 100, TRUE),
    Y = factor(Y)
  )

rec <- recipe(Y ~ ., data)

rec <- tune_each(starts_with('V'), data, rec, step_ns)

rec
#> Recipe
#> 
#> Inputs:
#> 
#>       role #variables
#>    outcome          1
#>  predictor         10
#> 
#> Operations:
#> 
#> Natural Splines on V1
#> Natural Splines on V2
#> Natural Splines on V3
#> Natural Splines on V4
#> Natural Splines on V5
#> Natural Splines on V6
#> Natural Splines on V7
#> Natural Splines on V8
#> Natural Splines on V9
#> Natural Splines on V10
```

**Comment by juliasilge** [comment]
Thank you for sharing your approach here @mattwarkentin! We're going to recommend that you stick with that approach for now if it is working for you. A more general solution to this problem isn't on our priority list at this time, so I'm going to close this; we can see how often folks raise this issue to understand how to prioritize it moving forward.
