### ISSUE TITLE
Package for handling outliers

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/recipes#898]
Hi @juliasilge and @topepo,

I have started to work on #850 (i.e. a package dedicated to handling outliers, *a la* `{themis}`). I have started to add a few common outlier handling approaches, but I wanted to get your thoughts on how outliers, once identified, should actually be handled. I see three main approaches:

1. **Set the outlier to missing**
     + This is perhaps the most straightforward solution. Just set the outlier value to `NA` which can be handled in later steps (e.g. `step_naomit()`, `step_impute_*()`, etc.).
2. **Set the outlier value to the threshold used for identifying the outlier**
    + For this approach, if we consider values beyond the 1st and 99th percentile as outliers, we could assign the 1st and 99th percentile values to the values beyond these thresholds.
3. **Remove/set missing the entire row**
    + This is sort of a special case when an algorithm is used not simply to find outlier values within a single variable, but rather identify entire rows/observations that are considered outliers based on sets of variables.
    + [`{lookout}`](https://sevvandi.github.io/lookout/index.html) would be an example of this scenario, where you use some set of numeric variables to identify outlier observations. Once an outlier is identified, should you **(A)** set the variables for the entire row as missing, **(2)** set the variables used in outlier detection for the entire row as missing, **(C)** remove the entire row from the data frame. 

From an API perspective, I thought maybe it makes sense to have an argument that controls this behaviour for every step, such as via a `method` argument:
```r
## Truncate at some computed thresholds (e.g. 99th percentile)
step_truncate <-
  function(
    recipe,
    ...,
    role = NA,
    trained = FALSE,
    thresholds = NULL,
    method = c('missing', 'replace', 'remove')
    na_rm = TRUE,
    skip = FALSE,
    id = rand_id('outlier')
  ) {
  ...
}
```

I look forward to hearing your thoughts.

**Comment by juliasilge** [comment]
Thanks for your patience on this @mattwarkentin!

Your plan of providing a consistent argument on this for all steps sounds like the right call. Calling it `method` does seem a bit generic to me; have you thought about something like `replace = c("threshold", "missing", "remove")` or similar?

I would strongly suggest making the default choice the one that replaces the outlier with the threshold value. You've probably noticed [what we say about row filtering](https://github.com/tidymodels/recipes/blob/main/man-roxygen/row-ops.R) for many steps (including `step_naomit()`):

> This step can entirely remove observations (rows of data), which can have unintended and/or problematic consequences when applying the step to new data later via [bake()]. Consider whether `skip = TRUE` or `skip = FALSE` is more appropriate in any given use case. In most instances that affect the rows of the data being predicted, this step probably should not be applied at all; instead, execute operations like this outside and before starting a preprocessing [recipe()].

Once you have a recipe step that removes rows, you run into problems when _predicting_, such as you need to when resampling and tuning (different rows end up in the analysis/assessment sets).

If users try to do something like replace outliers with `NA` and then remove `NA` values, they will run into problems when resampling. It's probably good to still have this functionality as an option for use cases outside of, say, tuning a model, but IMO it would not be the best default.

**Comment by juliasilge** [comment]
Thank you for all your thoughtful discussion @mattwarkentin!
