### ISSUE TITLE
Missing release for 0.1.17?

### ISSUE THREAD

**Issue by MichaelChirico** [tidymodels/recipes#902]
I see 0.1.17 on CRAN but no corresponding release on the repo here, is that perhaps an oversight?

**Comment by juliasilge** [comment]
Yes, this is related to #838; seems like that step got missed during the CRAN release.

We definitely all try to do a GH release along with a CRAN release, but can you share what it is you would use that for (your usecase)? [It is possible still](https://github.community/t/create-releases-for-old-commits/872) but I'm not sure if it's a priority for us right now.

**Comment by MichaelChirico** [comment]
it can be useful as a quick way to browse the code as it was for a given release. as we have to import the code source first to use it, we do work with the source a lot.

it's also useful to show the source diff between two releases.

as a workaround we can use the CRAN mirror org, the downside is it adds some separation vs. the true source (e.g. if we need to raise an issue or file a PR)
