### ISSUE TITLE
extract_parameters_set_dials() error

### ISSUE THREAD

**Issue by agwalker82** [tidymodels/recipes#912]
I am working through the Tidy Modeling with R Tutorials (https://www.tmwr.org/) on my local machine. 

In Chapter 15.1 (https://www.tmwr.org/workflow-sets.html#modeling-concrete-strength), the following code snippet is presented:

nnet_param <- 
   nnet_spec %>% 
   extract_parameter_set_dials() %>% 
   update(hidden_units = hidden_units(c(1, 27)))

When I run it, I get the following error message:

Error in UseMethod("extract_parameter_set_dials") : 
  no applicable method for 'extract_parameter_set_dials' applied to an object of class "c('mlp', 'model_spec')"

Fixes I have already tried:
- Updating to the most recent version of RStudio
- Updating to the most recent version of R (4.1.2)
- Updating all of my installed packages

**Comment by hfrick** [comment]
thanks for the issue! did you install the CRAN version of your packages or the development version? `extract_parameter_set_dials()` needs the dev version of most tidymodels packages. 

To extract a parameter set from a model spec as in the above snippet, you need the development version of parsnip and tune. You can install them via 

```
devtools::install_github("tidymodels/parsnip")
devtools::install_github("tidymodels/tune")
```

To be able to use `extract_parameter_set_dials()` with workflows, please install the dev versions of the `workflows` package. We are currently in the process of releasing new versions and TMwR is already working with the new versions.

**Comment by topepo** [comment]
We'll assume that installing the packages fixe the issue
