### ISSUE TITLE
`skip = TRUE` is not the default for `step_naomit`.

### ISSUE THREAD

**Issue by tmastny** [tidymodels/recipes#934]
Hello, this commit https://github.com/tidymodels/recipes/commit/108c14a59a83fe9978a5e633cee07dd8fff6d35a states that `step_filter()`, `step_slice()`, `step_sample()`, and `step_naomit()` will change their default to `skip = TRUE`. 

This resolves  a couple of different issues relating to predictions with these recipe steps: https://github.com/tidymodels/recipes/pull/512#issuecomment-630215281.

However, the change was not applied to `step_naomit`:
https://github.com/tidymodels/recipes/blob/5993319f73c4dd4ac5db0393a427106da230c56d/R/naomit.R#L25-L27

I wanted to see if this was an oversight. I would personally like to see `skip = TRUE` as the default for `step_naomit`.

Thanks for all the help!

**Comment by EmilHvitfeldt** [comment]
Hello @tmastny 👋  Good eyes! this appears to be an oversight. We will get it fixed
