### ISSUE TITLE
`step_mutate()`'s `role` parameter does not take effect for original variables

### ISSUE THREAD

**Issue by zenggyu** [tidymodels/recipes#944]
## The problem

As the title suggests, `step_mutate()`'s `role` parameter does not take effect for original variables. In the following example, perhaps `x1`, `x2` and `x3` should all be assigned with a role of "predictor"?

## Reproducible example

``` r
suppressPackageStartupMessages(library(recipes))

tr <- data.frame(x1 = c(1, 2), x2 = c(3, 4))

rec <- tr |>
  recipe() |>
  step_mutate(x1 = x1 + 1,
              across(c(x2), \(x2) {x2 + 1}),
              x3 = x2 + 1,
              role = "predictor") |>
  prep()

rec$term_info
#> # A tibble: 3 × 4
#>   variable type    role      source  
#>   <chr>    <chr>   <chr>     <chr>   
#> 1 x1       numeric <NA>      original
#> 2 x2       numeric <NA>      original
#> 3 x3       numeric predictor derived
```

<sup>Created on 2022-04-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by zenggyu** [comment]
The current behavior also makes sense, because if we first assign a role to the original variables, we may not want to accidentally update its role. But I think if we explicitly specify the `role` parameter, it should perhaps take effect?

**Comment by juliasilge** [comment]
This does look like a bug to me. 👍 

You probably are familiar with your options, but for the record, in the meantime you can work around like this (or by explicitly using `update_role()`):

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

tr <- data.frame(x1 = c(1, 2), x2 = c(3, 4))

rec <- recipe(~ ., data = tr) |>
    step_mutate(x1 = x1 + 1,
                across(c(x2), \(x2) {x2 + 1}),
                x3 = x2 + 1,
                role = "predictor") |>
    prep()

rec$term_info
#> # A tibble: 3 × 4
#>   variable type    role      source  
#>   <chr>    <chr>   <chr>     <chr>   
#> 1 x1       numeric predictor original
#> 2 x2       numeric predictor original
#> 3 x3       numeric predictor derived
```

<sup>Created on 2022-04-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by EmilHvitfeldt** [comment]
I'm going to close this issue as it appears to be documented behavior.
