### ISSUE TITLE
Feature Request: Imputation

### ISSUE THREAD

**Issue by madprogramer** [tidymodels/recipes#948]
I have been a big fan of tidymodels/tidyverse ever since I discovered them a few months ago. Yet when working with missing data, I have noticed that tidymodels (and recipes) have a few shortcomings. To quote from _[a certain staff blog from the University of Leicester](https://staffblogs.le.ac.uk/teachingr/2020/10/05/on-not-using-tidymodels/)_

> As an example, an important aspect of preparing the data for modelling is the replacement of missing data by imputation. So, tidymodels should have a design that helps us to make use of the many imputation packages already available in R. The problems of tidymodels imputation would exactly mirror those of broom. Lots of external functions offering different types of imputation, with the potential for more functions to be added in the future. So tidymodels needs to provide a framework for coding imputation.

I realize that this is more suitable for a milestone goal rather than a single issue. But if nothing, implementing a few recipe steps to call from [`mice`](https://www.rdocumentation.org/packages/mice/versions/3.14.0/topics/mice) would at least spare many the trouble of having to separate missing-data preprocessing from the tidymodels pipeline. Thoughts or comments?

**Comment by EmilHvitfeldt** [comment]
Hello @madprogramer 👋  Thanks for opening an issue! Have you seen that {recipes} has a number of steps to deal with imputation? https://recipes.tidymodels.org/reference/index.html#step-functions-imputation

If yes, do you have any specific types/methods of imputation that you want to do, but is unable to within recipes?

**Comment by madprogramer** [comment]
My apologies :) I had missed those entirely.

However, multi-imputation still seems to be missing. It's best to probably open a new issue for that.
