### ISSUE TITLE
No case-weights branch?

### ISSUE THREAD

**Issue by szymonkusak** [tidymodels/recipes#991]
Hi there

I wanted to install the version of recipes package which contains case weights feature but I don't see that branch in the repo. In parsnip there is active "feature/case-weights" branch. Few days ago "devtools::install_github("tidymodels/recipes@case-weights")" was working perfectly.

Thanks

**Comment by EmilHvitfeldt** [comment]
Hello! The case weights branch has been merged into the main branch, so you can install it with `devtools::install_github("tidymodels/recipes")`.

**Comment by szymonkusak** [comment]
Thank you, it's working :) Don't forget to change it in the installation instructions on tidymodels blog [.](https://www.tidyverse.org/blog/2022/05/case-weights/).
